### ISSUE TITLE
MemoryVectorStore similaritySearch fails at cosine.ts:13

### ISSUE THREAD

**Issue by tonisives** [langchain-ai/langchainjs#1066]
My code fails on similaritySearch:

```typescript
  const vectorStore = await MemoryVectorStore.fromDocuments(
    docs,
    new CohereEmbeddings(
      { apiKey: COHERE_TOKEN }
    )
  );

  // also tried with k=undefined and k=5
  const resultOne = await vectorStore.similaritySearch("where are the deposits made?", 1);
```

vector storing seems to work
<img width="491" alt="Screenshot 2023-05-01 at 09 33 57" src="https://user-images.githubusercontent.com/1083534/235393551-79da98bd-e2bb-479c-a8a4-a71806c493c7.png">

docs
<img width="575" alt="Screenshot 2023-05-01 at 09 31 35" src="https://user-images.githubusercontent.com/1083534/235393353-4feb7a68-fe47-4585-9188-33f250daf14d.png">

Error:
```
/Users/tonis/workspace/js/docs-ai/node_modules/ml-distance/src/similarities/cosine.ts:13
    p += a[i] * b[i];
                 ^
source-map-support.js:722
TypeError: Cannot read properties of undefined (reading '0')
    at MemoryVectorStore.cosine [as similarity] (/node_modules/ml-distance/src/similarities/cosine.ts:13:18)
    at file:///node_modules/langchain/dist/vectorstores/memory.js:36:30
    at Array.map (<anonymous>)
    at MemoryVectorStore.similaritySearchVectorWithScore (file:///node_modules/langchain/dist/vectorstores/memory.js:35:14)
    at MemoryVectorStore.similaritySearch (file:///node_modules/langchain/dist/vectorstores/base.js:47:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Edit:
It seems to work with `OpenAIEmbeddings`

**Comment by kulaone** [comment]
I believe I have come across a similar issue, although in a different situation. Specifically, I am attempting to utilize CohereEmbeddings in HNSWLib with any of the following chains: ConversationalRetrievalQAChain, VectorDBQAChain, or RetrievalQAChain. 
Regrettably, I am encountering the following error message:
```
file:///Testing/node_modules/langchain/dist/vectorstores/hnswlib.js:86
            this.index.addPoint(vectors[i], docstoreSize + i);

```            
To help with troubleshooting, I have included my code below.

```
import { CohereEmbeddings } from "langchain/embeddings/cohere";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";
import { PDFLoader } from "langchain/document_loaders/fs/pdf";
import { HNSWLib } from "langchain/vectorstores/hnswlib";
import { OpenAI } from "langchain/llms/openai";
import { RetrievalQAChain } from "langchain/chains";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";

const embeddings = new CohereEmbeddings();
// const embeddings = new OpenAIEmbeddings();

const docName = "doc/FILENAME.pdf";
const loader = new PDFLoader(`${docName}`);
const doc = await loader.load();
const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000, chunkOverlap: 200 });
const docs = await textSplitter.splitDocuments(doc);

const CHAT_COMPLETIONS_MODEL = "gpt-3.5-turbo";
const model = new OpenAI({model: CHAT_COMPLETIONS_MODEL,temperature: 0});

const vectorStore = await HNSWLib.fromDocuments(docs, embeddings);
const chain1 = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever());

const query = "What is the name of the company?";
const response = await chain1.call({ query: query });
console.log("🚀 ~ file: test.js:30 ~ response:", response)
```
