### ISSUE TITLE
Error: Missing value for input variable `input_language` in LLMChain call and chain chat history not working

### ISSUE THREAD

**Issue by knyga** [langchain-ai/langchainjs#1161]
While following the basic Quickstart tutorial: https://js.langchain.com/docs/getting-started/guide-chat#model--prompt--llmchain
I encountered an issue with the code provided.

Code:
```
const { LLMChain, ConversationChain } = require("langchain/chains");
const { ChatOpenAI } = require("langchain/chat_models/openai");
const { OpenAI } = require("langchain/llms/openai");
const {
  PromptTemplate,
  SystemMessagePromptTemplate,
  HumanMessagePromptTemplate,
  ChatPromptTemplate,
} = require("langchain/prompts");

async function main() {
  const chat = new ChatOpenAI({
    temperature: 0,
    openAIApiKey: process.env.OPENAI_API_TOKEN,
  });
  const translationPrompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(
      "You are a helpful assistant that translates {input_language} to {output_language}."
    ),
    HumanMessagePromptTemplate.fromTemplate("{text}"),
  ]);

  const responseA = await chat.generatePrompt([
    await translationPrompt.formatPromptValue({
      input_language: "English",
      output_language: "French",
      text: "I love programming.",
    }),
  ]);
  console.log(responseA.generations[0]);

  const chain = new LLMChain({
    prompt: translationPrompt,
    llm: chat,
  });

  const responseB = await chain.call({
    input_language: "English",
    output_language: "French",
    text: "I love programming.",
  });
  console.log(responseB);

  const responseD = await chain.call({
    input: "hi from London, how are you doing today",
  });
  // ERROR
  console.log(responseD);
});

main();
```

Error:
```
Error: Missing value for input variable `input_language`
    at /app/node_modules/langchain/dist/prompts/chat.cjs:190:27
    at Array.reduce (<anonymous>)
    at ChatPromptTemplate.formatMessages (/app/node_modules/langchain/dist/prompts/chat.cjs:188:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatPromptTemplate.formatPromptValue (/app/node_modules/langchain/dist/prompts/chat.cjs:81:32)
    at async LLMChain._call (/app/node_modules/langchain/dist/chains/llm_chain.cjs:82:29)
    at async LLMChain.call (/app/node_modules/langchain/dist/chains/base.cjs:68:28)
```

When I replace the input with a text/input_language/output_language object, the chain doesn't track the context.

Also, chat memory doesn't seem to be working:
```
  const chat = new ChatOpenAI({
    temperature: 0,
    openAIApiKey: process.env.OPENAI_API_TOKEN,
  });
  const chatPrompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(
      "The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know."
    ),
    new MessagesPlaceholder("history"),
    HumanMessagePromptTemplate.fromTemplate("{input}"),
  ]);

  const chain = new ConversationChain({
    memory: new BufferMemory({ returnMessages: true, memoryKey: "history" }),
    prompt: chatPrompt,
    llm: chat,
  });

  const responseA = await chain.call({
    input: "I love programming.",
  });
  console.log(responseA);
  //   {
  //   response: "That's great to hear! Programming is a fascinating field that allows you to create and build all sorts of things using code. What kind of programming do you enjoy doing?"
  // }
  const responseB = await chain.call({
    input: "What do I love to do?",
  });
  console.log(responseB);
  // {
  //   response: "I'm sorry, I don't have enough context to know what you love to do. Could you please provide more information?"
  // }
```
Ref: https://js.langchain.com/docs/getting-started/guide-chat#memory-add-state-to-chains-and-agents

**Comment by Ray0907** [comment]
The code you provided does not have any significant problems. I rewrote your code and it worked for me.

1.
`
  const responseD = await chain.call({
    input_language: "English",
    output_language: "French",
    text: "hi from London, how are you doing today",
  });
  console.log(responseD);
`
2. It worked for me when I tried it with a different prompt.

**Comment by killinsun** [comment]
How about this one? 🙇 

```js
const chatPrompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(
        "The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know."
    ),
    new MessagesPlaceholder("history"),
    HumanMessagePromptTemplate.fromTemplate("{input}"),
  ]);

  const conversation_chain = new ConversationChain({
    memory: new BufferMemory({ returnMessages: true, memoryKey: "history" }),
    prompt: chatPrompt,
    llm: chat,
  });

  const responseD = await conversation_chain.call({
    input: "hi from London, how are you doing today",
  });

  console.log(responseD);
  /*
  { text: "J'adore la programmation." }
   */

  const responseE = await conversation_chain.call({
    input: "Where am I?",
  });

  console.log(responseE);
  /*
  {
  response: "As an AI language model, I don't have access to your physical location. However, you mentioned that you are from London, so I assume that you are currently in London. Is that correct?"
  }
   */
```
