### ISSUE TITLE
Error parsing SyntaxError using the SelfQueryRetriever

### ISSUE THREAD

**Issue by ladrians** [langchain-ai/langchainjs#1480]
I am testing the `SelfQuery` Retriever option with some code as follows and gpt 3.5 turbo.

```ts
      const attributeInfo: AttributeInfo[] = getAttributeInfo(options?.retriever?.metadata || '');        
      retriever = SelfQueryRetriever.fromLLM({
        llm: model,
        documentContents: SELF_QUERY_DOC_CONTENTS,
        vectorStore: vectorStore,
        attributeInfo,
        structuredQueryTranslator: new BasicTranslator(),
      });
      retriever.verbose = verbose;
      retriever.searchParams = {
        k: k,
        filter: filter,
      };
```

currently have `year` and `quarter` filters defined, if I set the following question `what is the Q2 2021 revenue?` I get the following error:

```
Error: Error parsing SyntaxError: [1:20]: Unexpected token: 'identifier': eq("quarter", 2) and eq("year", "2021")
 at ExpressionParser.parse (C:\test\node_modules\langchain\dist\output_parsers\expression.js:41:19)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 at QueryTransformer.parse (C:\test\node_modules\langchain\dist\chains\query_constructor\parser.js:93:25)
 at StructuredQueryOutputParser.parserFunction (C:\test\node_modules\langchain\dist\chains\query_constructor\index.js:44:38) 
 at LLMChain._getFinalOutput (C:\test\node_modules\langchain\dist\chains\llm_chain.js:66:31)
 at LLMChain._call (C:\test\node_modules\langchain\dist\chains\llm_chain.js:94:31)
 at LLMChain.call (C:\test\node_modules\langchain\dist\chains\base.js:65:28)
 at SelfQueryRetriever.getRelevantDocuments (C:\test\node_modules\langchain\dist\retrievers\self_query\index.js:45:55)       
 at ConversationalRetrievalQAChain._call (C:\test\node_modules\langchain\dist\chains\conversational_retrieval_chain.js:105:22)
 at ConversationalRetrievalQAChain.call (C:\test\node_modules\langchain\dist\chains\base.js:65:28)
```

Using the `verbose` option noticed the large prompt used for generating and parsing the initial query, but couldn't figure out a way to overide it using the current methods available? Is there a way to try/error the prompt to see if it improves?

**Comment by ladrians** [comment]
OK, please do not close the ticket yet, I will be checking the case on September, is it OK?

**Comment by ladrians** [comment]
I could retest this case using version `0.0.160`, it still returns an error. This is the return from selfquery for the filters

```json\n{\n    \"query\": \"revenue\",\n    \"filter\": \"eq(\\\"quarter\\\", 2) and eq(\\\"year\\\", 2021)\"\n}\n```

with similar exception processing 'eq("quarter", 2) and eq("year", 2021)'

```typescript
Error: Error parsing SyntaxError: Expected " ", "(", ".", "[", "\t", "\x0B", "\x0C", " ", "", or end of input but "a" found.: eq("quarter", 2) 
and eq("year", 2021)
    at ExpressionParser.parse (C:\test\cdk\node_modules\langchain\dist\output_parsers\expression.cjs:89:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async QueryTransformer.parse (C:\test\cdk\node_modules\langchain\dist\chains\query_constructor\parser.cjs:117:25)      
    at async StructuredQueryOutputParser.outputProcessor (C:\test\cdk\node_modules\langchain\dist\chains\query_constructor\index.cjs:64:34)
    at async LLMChain._getFinalOutput (C:\test\cdk\node_modules\langchain\dist\chains\llm_chain.cjs:96:31)
    at async LLMChain._call (C:\test\cdk\node_modules\langchain\dist\chains\llm_chain.cjs:126:31)
    at async LLMChain.call (C:\test\cdk\node_modules\langchain\dist\chains\base.cjs:104:28)
    at async SelfQueryRetriever._getRelevantDocuments (C:\test\cdk\node_modules\langchain\dist\retrievers\self_query\index.cjs:69:55)
    at async SelfQueryRetriever.getRelevantDocuments (C:\test\cdk\node_modules\langchain\dist\schema\retriever.cjs:69:29)     
    at async ConversationalRetrievalQAChain._call (C:\test\cdk\node_modules\langchain\dist\chains\conversational_retrieval_chain.cjs:140:22)
```
thanks

**Comment by ladrians** [comment]
I got back to a project trying to use this feature. Now using `langchain`: `0.0.214`, can confirm that the problem continues.

```
json\n{\n    \"query\": \"revenue\",\n    \"filter\": \"eq(\\\"quarter\\\", 2) and eq(\\\"year\\\", 2021)\"\n}\n
...
SyntaxError: Expected " ", "(", ".", "[", "\t", "\x0B", "\x0C", " ", "﻿", or end of input but "a" found.: eq("quarter", 2) and eq("year", 2021)

```

Is there planned an option to enable changing the default Prompt to modify it and try to get it solved?
Havent checked the LCEL yet, is there a walkthrough on how to convert this retriever to a pipelined one to try with manual prompts? In my case I am using a `ConversationalQA` chain with a selfQueryRetriever.

Any other ideas are welcome, thanks

**Comment by jacoblee93** [comment]
Apologies for not getting back to you sooner - yes a new chain is definitely on the roadmap. Will aim to get that done ASAP if nobody beats me to it

**Comment by jacoblee93** [comment]
Still on the TODO list!

**Comment by ladrians** [comment]
I updated to `0.1.36` and at least I can modify the first part of the prompt, not perfect but it goes in the needed direction

```typescript
selfQueryVectorstoreInstance.lc_kwargs.queryConstructor.first.prefix = "desired value here");
```

**Comment by D4RK5IDE** [comment]
have same problem with new FunctionalTranslator(). I get error: Error parsing SyntaxError: Expected " ", "$", "'", "(", ".", "0", "[", "\"", "\t", "\x0B", "\x0C", "_", "false", "null", "true", "{", " ", "", [1-9], [A-Z], or [a-z] but end of input found.
