### ISSUE TITLE
Network error in ConversationRetrievalQAChain

### ISSUE THREAD

**Issue by haardikk21** [langchain-ai/langchainjs#1517]
I'm getting the same issue as https://github.com/hwchase17/langchainjs/issues/739 but it's happening on the latest langchainjs version.

I'm running a NextJS 12 server with a streaming API endpoint inside a serverful node.js environment (not hosted on Vercel - so no serverless or edge)

It works when I'm running it locally - but when I deploy it to my host (Render.com) I get the exact same error as #739 

I'm using Node LTS - 18.16.0 with NextJs 12 and LangchainJs 0.0.89

It happens on the `/v1/chat/completions` endpoint 

----

```
AxiosError: Network Error
    at createError (file:///opt/render/project/src/node_modules/.pnpm/langchain@0.0.89_@aws-sdk+client-s3@3.315.0_axios@1.3.5/node_modules/langchain/dist/util/axios-fetch-adapter.js:349:16)
    at getResponse (file:///opt/render/project/src/node_modules/.pnpm/langchain@0.0.89_@aws-sdk+client-s3@3.315.0_axios@1.3.5/node_modules/langchain/dist/util/axios-fetch-adapter.js:205:16)
    at async fetchAdapter (file:///opt/render/project/src/node_modules/.pnpm/langchain@0.0.89_@aws-sdk+client-s3@3.315.0_axios@1.3.5/node_modules/langchain/dist/util/axios-fetch-adapter.js:176:18) {
  code: 'ERR_NETWORK',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [AsyncFunction: fetchAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer REDACTED'
    },
    method: 'post',
    responseType: 'stream',
    onmessage: [Function: onmessage],
    data: `{"model":"gpt-4","temperature":0,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"stream":true,"messages":[{"role":"user","content":"Hello"}]}`,
    url: 'https://api.openai.com/v1/chat/completions'
  },
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  attemptNumber: 7,
  retriesLeft: 0
}
```

**Comment by haardikk21** [comment]
I was able to reproduce this locally by running the Next.js app as `pnpm build && pnpm start` instead of in dev-mode like `pnpm dev`

After playing and adding more logs to `axios-fetch-adapter.js` - I got to this error:

```
{
  baseURL: undefined,
  requestedURL: 'https://api.openai.com/v1/chat/completions'
}
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/node-fetch/index.js:1:63531)
    at /home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/node-fetch/index.js:1:65062
    at new Promise (<anonymous>)
    at fetch (/home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/node-fetch/index.js:1:64996)
    at getResponse (file:///home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/langchain@0.0.89_@aws-sdk+client-s3@3.315.0_axios@1.4.0/node_modules/langchain/dist/util/axios-fetch-adapter.js:199:26)
    at fetchAdapter (file:///home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/langchain@0.0.89_@aws-sdk+client-s3@3.315.0_axios@1.4.0/node_modules/langchain/dist/util/axios-fetch-adapter.js:178:24)
    at dispatchRequest (/home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/haardik/Developer/LearnWeb3/www-v2/node_modules/.pnpm/openai@3.2.1/node_modules/openai/dist/common.js:149:22
    ```
