### ISSUE TITLE
ReferenceError: Property 'TextEncoder' doesn't exist

### ISSUE THREAD

**Issue by pbxqdown** [langchain-ai/langchainjs#1521]
I'm trying to use langchainjs in react native app. Ran into following error:
```
 WARN  Possible Unhandled Promise Rejection (id: 1):
ReferenceError: Property 'TextEncoder' doesn't exist
ReferenceError: Property 'TextEncoder' doesn't exist
    at createRequest (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:105116:26)
    at ?anon_0_ (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:105016:34)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4644:26)
    at _next (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4663:29)
    at anonymous (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4668:14)
    at tryCallTwo (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4660:25)
    at apply (native)
    at fetchAdapter (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:105012:31)
    at dispatchRequest (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:103837:19)
    at request (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:103701:32)
    at apply (native)
    at wrap (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:103621:22)
    at anonymous (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:104678:27)
    at anonymous (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:103235:25)
    at tryCallOne (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29744:26)
    at _callTimer (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29663:17)
    at _callReactNativeMicrotasksPass (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29693:17)
    at callReactNativeMicrotasks (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29856:44)
    at __callReactNativeMicrotasks (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2793:46)
    at anonymous (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2605:45)
    at __guard (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2777:15)
    at flushedQueue (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2604:21)
    at callFunctionReturnFlushedQueue (http://192.168.1.2:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2589:33)
```
Source code:
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import { OpenAI } from "langchain/llms/openai";

async function callOpenAI() {
  const model = new OpenAI({ openAIApiKey: "sk-...", temperature: 0.9 });
  const res = await model.call(
    "What would be a good company name a company that makes colorful socks?"
  );
  console.log(res);
}

export default function App() {
  console.log("hello world!");
  callOpenAI();

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app?!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

**Comment by pbxqdown** [comment]
Hey @borel, I think this is the main react native app entry point and can not use await.
I'm switching to option that calls openai in a backend server now. For the above issue, I'm guessing it is because react native doesn't have nodejs runtime included.

**Comment by vbarda** [comment]
running into the same issue with react native

**Comment by vbarda** [comment]
actually, I got it working! @pbxqdown see this issue https://github.com/hapijs/joi/issues/2141#issuecomment-558429490

**Comment by pbxqdown** [comment]
It would be nice if langchain.js does auto importing.
