### ISSUE TITLE
Parse Errors from Structured Tool are not handled by LLM

### ISSUE THREAD

**Issue by deefactorial** [langchain-ai/langchainjs#1653]
When an LLM produces invalid input for a structured tool, the Structured Tool exits with a parsing error from the schema parser.
The error should be caught by the tool and the run manager should handle the schema error by re-evaluating the input to the tool to conform to the tool schema specification. This would allow the operation to not be interrupted by invalid input to the tool.

specifically on this line.
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/tools/base.ts#L38

```
[chain/error] [1:chain:agent_executor] [59.99s] Chain run errored with error: "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"issueType\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"issueNumber\"\n    ],\n    \"message\": \"Required\"\n  }\n]"
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "issueType"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "undefined",
    "path": [
      "issueNumber"
    ],
    "message": "Required"
  }
]
    at Object.get error [as error] (file:///node_modules/zod/lib/index.mjs:537:31)
    at ZodObject.parseAsync (file://node_modules/zod/lib/index.mjs:659:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DynamicStructuredTool.call (file://node_modules/langchain/dist/tools/base.js:18:24)
    at async file:///node_modules/langchain/dist/agents/executor.js:98:23
    at async Promise.all (index 0)
    at async AgentExecutor._call (file:///node_modules/langchain/dist/agents/executor.js:94:30)
    at async AgentExecutor.call (file://node_modules/langchain/dist/chains/base.js:65:28)
    at async file:///src/issues.ts:47:26
    at async Promise.all (index 0) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}
```

**Comment by deanmikan** [comment]
+1

Very annoying that it errors instead of the agent continuing by reading the error message and reevaluating it's input and giving it another crack with better input.

**Comment by Negan1911** [comment]
If you're using `OutputFixingParser` and seeing this issue, I created a PR for this one: https://github.com/hwchase17/langchainjs/pull/2027
