### ISSUE TITLE
Error on HNSWLib

### ISSUE THREAD

**Issue by tomasantunes** [langchain-ai/langchainjs#1669]
Occasionally I get this error when using HNSWLib.fromDocuments() method.

```
C:\Users\UTILIZADOR\Documents\nc-chatbot\node_modules\langchain\dist\vectorstores\hnswlib.cjs:90
            this.index.addPoint(vectors[i], docstoreSize + i);
                       ^

TypeError: Invalid the first argument type, must be an Array.
    at HNSWLib.addVectors (C:\Users\UTILIZADOR\Documents\nc-chatbot\node_modules\langchain\dist\vectorstores\hnswlib.cjs:90:24)
    at async HNSWLib.fromDocuments (C:\Users\UTILIZADOR\Documents\nc-chatbot\node_modules\langchain\dist\vectorstores\hnswlib.cjs:168:9)
    at async loadWebsiteTextFiles2 (C:\Users\UTILIZADOR\Documents\nc-chatbot\app.js:73:17)
```

**Comment by tomasantunes** [comment]
I made a fix that ignores the error.

```
        var count = 0;
        for (let i = 0; i < vectors.length; i += 1) {
            if (Array.isArray(vectors[i])) {
                this.index.addPoint(vectors[i], docstoreSize + count);
                toSave[docstoreSize + count] = documents[i];
                count++;
            }
        }
```

**Comment by DittoDuckPenguin** [comment]
```
file:///home/ubuntu/AI/node_modules/langchain/dist/vectorstores/hnswlib.js:111
            this.index.addPoint(vectors[i], docstoreSize + i);
                       ^

TypeError: A number was expected
    at HNSWLib.addVectors (file:///home/ubuntu/AI/node_modules/langchain/dist/vectorstores/hnswlib.js:111:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HNSWLib.fromDocuments (file:///home/ubuntu/AI/node_modules/langchain/dist/vectorstores/hnswlib.js:258:9)
    at async file:///home/ubuntu/AI/index.js:26:21

Node.js v20.6.0
```

Having the same error apparently.

- Ubuntu 20.04.5 LTS
