### ISSUE TITLE
TypeError: message.choices is not iterable

### ISSUE THREAD

**Issue by AlexXi19** [langchain-ai/langchainjs#1715]
Getting this intermittent error on certain inputs, has anyone else seen this? 
```
Jun 21 05:10:26 ip-172-31-23-86 web: "TypeError: message.choices is not iterable\n    at onmessage (/var/app/current/node_modules/langchain/dist/chat_models/openai.cjs:296:56)\n    at onLine (/var/app/current/node_modules/langchain/dist/util/event-source-parse.cjs:133:24)\n    at onChunk (/var/app/current/node_modules/langchain/dist/util/event-source-parse.cjs:96:13)\n    at getBytes (/var/app/current/node_modules/langchain/dist/util/event-source-parse.cjs:31:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getResponse (/var/app/current/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:244:13)\n    at async fetchAdapter (/var/app/current/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:181:18)\n    at async RetryOperation._fn (/var/app/current/node_modules/p-retry/index.js:50:12)"
```

**Comment by shinnqy** [comment]
Got `TypeError: data.choices is not iterable`

**Comment by CWXDEV** [comment]
what version of langchain are you on?

there was a change: #1696

this should fix it, at least i have not had the issue since updating

**Comment by AlexXi19** [comment]
Upgraded to version `0.0.96` seems to have solved it. Thanks!

**Comment by shinnqy** [comment]
No, I hit this in `0.0.96`.

**Comment by shinnqy** [comment]
Then I overwrite the function of this lib.

**Comment by shinnqy** [comment]
There are bugs when call completion API.
