### ISSUE TITLE
DynamicStructuredTool: Zod Error, Expected object, received string

### ISSUE THREAD

**Issue by asontha** [langchain-ai/langchainjs#1723]
Trying out Dynamic Structured Tools for the first time and running into this error. Using the exact DynamicStructuredTool provided here:

https://js.langchain.com/docs/modules/agents/agents/action/structured_chat

Any advice?

**Comment by josharsh** [comment]
Hey, could you share the error you are getting here?

**Comment by asontha** [comment]
```
Loaded agent.
Your message: what is a random number between 5 and 10?
Executing with input "what is a random number between 5 and 10?"...
[chain/start] [1:chain:agent_executor] Entering Chain run with input: {
  "input": "what is a random number between 5 and 10?",
  "chat_history": []
}
[chain/start] [1:chain:agent_executor > 2:chain:llm_chain] Entering Chain run with input: {
  "input": "what is a random number between 5 and 10?",
  "chat_history": [],
  "agent_scratchpad": [],
  "stop": [
    "Observation:"
  ]
}
[llm/start] [1:chain:agent_executor > 2:chain:llm_chain > 3:llm:openai] Entering LLM run with input: {
  "prompts": [
    "[{\"type\":\"system\",\"data\":{\"content\":\"Assistant is a large language model trained by OpenAI.\\n\\nAssistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.\\n\\nAssistant is constantly learning and improving, and its capabilities are constantly evolving. It is able to process and understand large amounts of text, and can use this knowledge to provide accurate and informative responses to a wide range of questions. Additionally, Assistant is able to generate its own text based on the input it receives, allowing it to engage in discussions and provide explanations and descriptions on a wide range of topics.\\n\\nOverall, Assistant is a powerful system that can help with a wide range of tasks and provide valuable insights and information on a wide range of topics. Whether you need help with a specific question or just want to have a conversation about a particular topic, Assistant is here to assist. However, above all else, all responses must adhere to the format of RESPONSE FORMAT INSTRUCTIONS.\"}},{\"type\":\"human\",\"data\":{\"content\":\"TOOLS\\n------\\nAssistant can ask the user to use tools to look up information that may be helpful in answering the users original question. The tools the human can use are:\\n\\nrandom-number-generator: generates a random number between two input numbers\\n\\nRESPONSE FORMAT INSTRUCTIONS\\n----------------------------\\n\\nOutput a JSON markdown code snippet containing a valid JSON object in one of two formats:\\n\\n**Option 1:**\\nUse this if you want the human to use a tool.\\nMarkdown code snippet formatted in the following schema:\\n\\n```json\\n{\\n    \\\"action\\\": string, // The action to take. Must be one of [random-number-generator]\\n    \\\"action_input\\\": string // The input to the action. May be a stringified object.\\n}\\n```\\n\\n**Option #2:**\\nUse this if you want to respond directly and conversationally to the human. Markdown code snippet formatted in the following schema:\\n\\n```json\\n{\\n    \\\"action\\\": \\\"Final Answer\\\",\\n    \\\"action_input\\\": string // You should put what you want to return to use here and make sure to use valid json newline characters.\\n}\\n```\\n\\nFor both options, remember to always include the surrounding markdown code snippet delimiters (begin with \\\"```json\\\" and end with \\\"```\\\")!\\n\\n\\nUSER'S INPUT\\n--------------------\\nHere is the user's input (remember to respond with a markdown code snippet of a json blob with a single action, and NOTHING else):\\n\\nwhat is a random number between 5 and 10?\"}}]"
  ]
}
[llm/end] [1:chain:agent_executor > 2:chain:llm_chain > 3:llm:openai] [5.50s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": "```json\n{\n    \"action\": \"random-number-generator\",\n    \"action_input\": \"{\\\"min\\\": 5, \\\"max\\\": 10}\"\n}\n```"
      }
    ]
  ]
}
[chain/end] [1:chain:agent_executor > 2:chain:llm_chain] [5.50s] Exiting Chain run with output: {
  "text": "```json\n{\n    \"action\": \"random-number-generator\",\n    \"action_input\": \"{\\\"min\\\": 5, \\\"max\\\": 10}\"\n}\n```"
}
[agent/action] [1:chain:agent_executor] Agent selected action: {
  "tool": "random-number-generator",
  "toolInput": "{\"min\": 5, \"max\": 10}",
  "log": "```json\n{\n    \"action\": \"random-number-generator\",\n    \"action_input\": \"{\\\"min\\\": 5, \\\"max\\\": 10}\"\n}\n```"
}
[chain/error] [1:chain:agent_executor] [5.50s] Chain run errored with error: "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"string\",\n    \"path\": [],\n    \"message\": \"Expected object, received string\"\n  }\n]"
/.../node_modules/zod/lib/types.js:43
                const error = new ZodError_1.ZodError(ctx.common.issues);
                              ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]
    at get error [as error] (/.../node_modules/zod/lib/types.js:43:31)
    at ZodObject.parseAsync (/.../node_modules/zod/lib/types.js:164:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DynamicStructuredTool.call (/.../node_modules/langchain/dist/tools/base.cjs:21:24)
    at async /.../node_modules/langchain/dist/agents/executor.cjs:101:23
    at async Promise.all (index 0)
    at async AgentExecutor._call (/.../node_modules/langchain/dist/agents/executor.cjs:97:30)
    at async AgentExecutor.call (/.../node_modules/langchain/dist/chains/base.cjs:68:28)
    at async run (/.../index.js:44:20) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'string',
      path: [],
      message: 'Expected object, received string'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'string',
      path: [],
      message: 'Expected object, received string'
    }
  ]
}

Node.js v18.12.1
```

**Comment by asontha** [comment]
I'm using `gpt-4`

**Comment by khanguslee** [comment]
I am also experiencing the same error when I use the `StructuredOutputParser` to generate from a zod schema. Feeding this back to the parser, i get the error. 
```ts
const channelParser = StructuredOutputParser.fromZodSchema(z.record(z.string(), ChannelSchema));
```
This also happens when I feed the value into the `OutputFixingParser`, after the model generates a new 'valid' schema, passing it into the parser errors too.

```ts
async function fixOutputParser(parser, badInput) {
    try {
        await parser.parse(badInput);
    } catch (e) {
        //console.log("Failed to parse bad output: ", e);
        const fixParser = OutputFixingParser.fromLLM(
            model,
            parser
          );
      const output = await fixParser.parse(badInput);
      console.log("Fixed output: ", output);
    }
}

console.log(channelParser)
await fixOutputParser(channelParser, generatedChannelsWithZod);
```

Note that `generatedChannelsWithZod` is what is generated by the model previously with a prompt template using `channelParser.getFormatInstructions()`.

I am also using gpt-4.

**Comment by khanguslee** [comment]
After looking into this a bit more, I could avoid my error if I wrap `generatedChannelsWithZod` with `JSON.parse`.

```ts
await fixOutputParser(channelParser, JSON.parse(generatedChannelsWithZod));
```

**Comment by asontha** [comment]
Just an update here, I ended up upgrading my langchain version from 0.0.92 to 0.0.96 and also changed my agent type from `chat-conversational-react-description` to `openai-functions` and everything is working as expected. Still not sure exactly what's happening here but regardless, even the inputs that it was generating for the supplied tool were wrong even if the parsing was working as expected.

**Comment by Crizzooo** [comment]
@asontha  Im also frequently experiencing  "expected object, received string" when using `StructuredChatAgent` and Structured Tools.

The LLM (gpt4) seems to sometimes ignore the schema of a tool and just pass a string as the action_input

This makes me want to try `openai-functions` instead, but I am receiving 404s when using `OpenAIAgent` instead of `StructuredChatAgent`

---

This headache makes me lose confidence that I can actually build an advanced assistant within my application (e.g looks up data, tells user about whats going wrong with something in our app, and asks them if theyd like to take an action that it will use another tool to process on our backend) 😢

**Comment by Crizzooo** [comment]
Confirmed that switching to `openai-functions` has made tool calls _a lot_ more reliable than any implementation Ive tried so far!

Now to figure out how to build a cohesive chat experience that uses many different self-help agents for various data domains of our application 😅

**Comment by manuel-84** [comment]
I had this problem too and I found in a hacky workaround meanwhile waiting for resolution: specify in the tool's description how the input should be, like :

`description: 'Useful to answer questions about specific books/pages. Input should be an Object with question, bookTitle and pageNumber'`
