### ISSUE TITLE
Unstructured: headers timeout

### ISSUE THREAD

**Issue by thundo** [langchain-ai/langchainjs#1856]
I'm using Unstructured loader for parsing a OCR-heavy pdf with

```ts
const options = {
        apiKey: 'MY_API_KEY',
        apiUrl: 'http://localhost:8800/general/v0/general',
        strategy: 'ocr_only',
    };

const loader = new UnstructuredLoader(
        filePath,
        options,
    );

const text = await loader.load();
 ```

The text extraction takes several minutes (>5'), so that the internal node `fetch`/`undici` call fails with

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at async UnstructuredLoader._partition (file:///D:/my_project/node_modules/langchain/dist/document_loaders/fs/unstructured.js:81:26)
    at async UnstructuredLoader.load (file:///D:/my_project/node_modules/langchain/dist/document_loaders/fs/unstructured.js:99:26)
    at async loadUnstructured (file:///D:/my_project/my_code.js:68:18)
    at async file:///D:/my_project/my_code.js:107:18 {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (D:\my_project\node_modules\undici\lib\client.js:931:28)
      at Timeout.onTimeout [as _onTimeout] (D:\my_project\node_modules\undici\lib\timers.js:20:13)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
```

Given that a long extraction time may totally be possible in this environment, I'd like to pass a timeout option to the loader (and to the underlying `fetch`/`undici`). Should I add a PR for that or are there other options?

Thanks

**Comment by teh23** [comment]
If someone as me facing this error (in my case in ollama llm) u can in codebase install undici and add this: 
 ```js
 import { Agent } from "undici";
 
 globalThis[Symbol.for("undici.globalDispatcher.1")] = new Agent({
  headersTimeout: 1000 * 60 * 60 * 24,
});```

**Comment by fejdraus** [comment]
Why not use 'node-fetch'?

```npm install node-fetch```

Add code

```async loadNodeFetch() {
    const fetch = (await import('node-fetch')).default;
    return fetch;
}```
    
add to the _partition function

```const fetch = await this.loadNodeFetch();```

and that's it, it will work correctly, the timeout is infinite.

**Comment by medic-code** [comment]
@thundo can this issue be closed ?
