### ISSUE TITLE
Error when using model 'sentence-transformers/all-MiniLM-L6-v2' with HuggingFaceInferenceEmbeddings

### ISSUE THREAD

**Issue by bent10** [langchain-ai/langchainjs#1911]
I encountered an issue while attempting to use the model `'sentence-transformers/all-MiniLM-L6-v2'` (and also on several other models) with `HuggingFaceInferenceEmbeddings` in my code. I followed a similar example from the [documentation](https://js.langchain.com/docs/modules/prompts/example_selectors/#select-by-similarity), but instead of using `OpenAIEmbeddings`, I used `HuggingFaceInferenceEmbeddings`. However, I received the following error message:

```bash
throw new Error(output.error);
            ^

Error: SentenceSimilarityInputsCheck expected dict not list: `__root__` in `parameters`
    at HfInference.request (file:///.../node_modules/@huggingface/inference/dist/index.mjs:425:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HfInference.featureExtraction (file:///.../node_modules/@huggingface/inference/dist/index.mjs:264:17)
    at RetryOperation._fn (/.../node_modules/p-retry/index.js:50:12) {
  attemptNumber: 2,
  retriesLeft: 0
}

Node.js v18.12.0
```

**Reproduction Code:**

```js
import { HuggingFaceInferenceEmbeddings } from 'langchain/embeddings/hf'
import {
  SemanticSimilarityExampleSelector,
  PromptTemplate,
  FewShotPromptTemplate
} from 'langchain/prompts'
import { HNSWLib } from 'langchain/vectorstores/hnswlib'

const examplePrompt = new PromptTemplate({
  inputVariables: ['input', 'output'],
  template: 'Input: {input}\nOutput: {output}'
})

const exampleSelector = await SemanticSimilarityExampleSelector.fromExamples(
  [
    { input: 'happy', output: 'sad' },
    { input: 'tall', output: 'short' },
    { input: 'energetic', output: 'lethargic' },
    { input: 'sunny', output: 'gloomy' },
    { input: 'windy', output: 'calm' }
  ],
  new HuggingFaceInferenceEmbeddings({
    model: 'sentence-transformers/all-MiniLM-L6-v2',
    maxRetries: 1
  }),
  HNSWLib,
  { k: 1 }
)

const dynamicPrompt = new FewShotPromptTemplate({
  exampleSelector,
  examplePrompt,
  prefix: 'Give the antonym of every input',
  suffix: 'Input: {adjective}\nOutput:',
  inputVariables: ['adjective']
})

// Input is about the weather, so should select eg. the sunny/gloomy example
console.log(await dynamicPrompt.format({ adjective: 'rainy' }))

// Input is a measurement, so should select the tall/short example
console.log(await dynamicPrompt.format({ adjective: 'large' })
```

I would appreciate any assistance or guidance on resolving this issue. Thank you!

**Comment by ElijahJohnson5** [comment]
I am having the same issue!
