### ISSUE TITLE
Error using Generative Agents with Pinecone Store

### ISSUE THREAD

**Issue by sebas5384** [langchain-ai/langchainjs#1993]
I'm using the example though after changing to use a Pinecone Store for the memory and I'm receiving this error:

```
error running simulation: TypeError: Cannot read properties of undefined (reading 'metadata')
    at TimeWeightedVectorStoreRetriever.getCombinedScore (file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:201:62)
    at file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:161:25
    at Array.map (<anonymous>)
    at TimeWeightedVectorStoreRetriever.computeResults (file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:159:14)
    at TimeWeightedVectorStoreRetriever.getRelevantDocuments (file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:99:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Simulation (file:///Users/../../ai-langchain/agent-generative.ts:119:5)
    at async runSimulation (file:///Users/../../ai-langchain/agent-generative.ts:153:5)
    at async file:///Users/../../ai-langchain/agent-generative.ts:160:1
file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:201
        const hoursPassed = this.getHoursPassed(nowMsec, doc.metadata[LAST_ACCESSED_AT_KEY]);
                                                             ^
TypeError: Cannot read properties of undefined (reading 'metadata')
    at TimeWeightedVectorStoreRetriever.getCombinedScore (file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:201:62)
    at file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:161:25
    at Array.map (<anonymous>)
    at TimeWeightedVectorStoreRetriever.computeResults (file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:159:14)
    at TimeWeightedVectorStoreRetriever.getRelevantDocuments (file:///Users/../../ai-langchainmodules/langchain/dist/retrievers/time_weighted.js:99:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Simulation (file:///Users/../../ai-langchain/agent-generative.ts:119:5)
    at async runSimulation (file:///Users/../../ai-langchain/agent-generative.ts:153:5)
    at async file:///Users/../../ai-langchain/agent-generative.ts:160:1
```

Here's how I'm initializing the memory retriever:
```js
const pineconeClient = new PineconeClient();
  await pineconeClient.init({
    apiKey: process.env.PINECONE_API_KEY,
    environment: process.env.PINECONE_ENVIRONMENT,
  });
  const pineconeIndex = pineconeClient.Index(process.env.PINECONE_INDEX);

  const createNewMemoryRetriever = async () => {
    // Create a new, demo in-memory vector store retriever unique to the agent.
    // Better results can be achieved with a more sophisticatd vector store.
    // const vectorStore = new MemoryVectorStore(new OpenAIEmbeddings());
    const vectorStore = new PineconeStore(new OpenAIEmbeddings(), {
      pineconeIndex,
      namespace: "observations",
    });

    const retriever = new TimeWeightedVectorStoreRetriever({
      vectorStore,
      otherScoreKeys: ["importance"],
      k: 15,
    });

    return retriever;
  };
```

I made some debug and it seems that the buffer from Time Weighted Retrieved is empty and when there's already documents in the store it fails to load it into memory. Also the `importance` key is not being persisted in within the document in the store.

Similar error: https://github.com/hwchase17/langchainjs/issues/1906

I feel like I'm missing some step to fill the `memoryStream` or something like that.

Help?

**Comment by sebas5384** [comment]
I made a patch just to be able to keep going and seems to be working:

```js
/**
     * Get salient documents and their scores based on the query
     * @param query - The query to search for
     * @returns An object containing salient documents and their scores
     */
    async getSalientDocuments(query) {
        const docAndScores = await this.vectorStore.similaritySearchWithScore(query, this.searchKwargs);
        const results = {};
        for (const [fetchedDoc, score] of docAndScores) {
            const bufferIdx = fetchedDoc.metadata[BUFFER_IDX];
            if (bufferIdx === undefined) {
                throw new Error(`Found a document in the vector store that is missing required metadata. This retriever only supports vector stores with documents that have been added through the "addDocuments" method on a TimeWeightedVectorStoreRetriever, not directly added or loaded into the backing vector store.`);
            }

            // <CHANGE>
            // Load to the memory stream if it doesn't exist.
            if (!this.memoryStream[bufferIdx]) {
              this.memoryStream[bufferIdx] = fetchedDoc;
            }
            // </CHANGE>

            const doc = this.memoryStream[bufferIdx];
            results[bufferIdx] = { doc, score };
        }
        return results;
    }
```

My objective here is to have a Roleplay Agent which will have unique and private conversations with users were the memory from the Agent is same for all users though each one would have their own conversations and not being part of the Agent, maybe this is not the best application to Generative Agents since I discover that every conversation with the Agent would be saved as part of the contexto for every user interacting with the Roleplay Agent.

**Comment by MaxLeiter** [comment]
This doesn't seem like an AI SDK issue so I'm going to close it. Best of luck with your problem!
