### ISSUE TITLE
Azure OpenAI call gets Bad Authorization header

### ISSUE THREAD

**Issue by zeason** [langchain-ai/langchainjs#2079]
I have following code worked until yesterday.
```
const chat = new ChatOpenAI({
		azureOpenAIApiDeploymentName: process.env.DEPLOYMENT_NAME,
		azureOpenAIApiKey: process.env.API_KEY,
		azureOpenAIApiInstanceName: 'gundam',
		azureOpenAIApiVersion: '2023-03-15-preview',
		azureOpenAIBasePath: `${endpoint}/openai/deployments`,
		temperature: 0,
	});
	const chatPrompt = ChatPromptTemplate.fromPromptMessages([
		HumanMessagePromptTemplate.fromTemplate('{input}'),
	]);
	const chain = new ConversationChain({
		llm: chat,
		prompt: chatPrompt,
	});
	process.stdout.write(`Chatbot: `);
	const res = await chain.call({ input: 'Hello?' });
	console.log(res.response);
```

But today I get the following error:
```
The sample encountered an error: Error: Request failed with status code 401
    at createError (C:\Users\Eason_Chen\IdeaProjects\azureopenai\node_modules\openai\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Eason_Chen\IdeaProjects\azureopenai\node_modules\openai\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Eason_Chen\IdeaProjects\azureopenai\node_modules\openai\node_modules\axios\lib\adapters\http.js:322:11)    
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.3.0',
      Authorization: 'Bearer undefined',
      'api-key': '{api-key}',
      'Content-Length': 162
    },
    method: 'post',
    params: { 'api-version': '2023-03-15-preview' },
    data: '{"model":"gpt-3.5-turbo","temperature":0,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"stream":false,"messages":[{"role":"user","content":"hello"}]}',
    url: 'https://{host}/openai/deployments/gpt-35-turbo/chat/completions'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 162,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: '{host}',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '{host}',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 5,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: OpenAI/NodeJS/3.3.0\r\n' +
      'Authorization: Bearer undefined\r\n' +
      'api-key: {api-key}\r\n' +
      'Content-Length: 162\r\n' +
      'Host: {host}\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://{host}/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '{host}',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 162,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://{host}/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      authorization: [Array],
      'api-key': [Array],
      'content-length': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Wed, 26 Jul 2023 02:46:51 GMT',
      'content-length': '24',
      connection: 'close',
      'strict-transport-security': 'max-age=15724800; includeSubDomains'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      params: [Object],
      data: '{"model":"gpt-3.5-turbo","temperature":0,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"stream":false,"messages":[{"role":"user","content":"hello"}]}',
      url: 'https://{host}/openai/deployments/gpt-35-turbo/chat/completions'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 162,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.3.0\r\n' +
        'Authorization: Bearer undefined\r\n' +
        'api-key: {api-key}\r\n' +
        'Content-Length: 162\r\n' +
        'Host: {host}\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '{host}',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: 'Bad Authorization header'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 1,
  retriesLeft: 6
}
```

and my dependencies:
```
"dependencies": {
    "axios": "^1.4.0",
    "dotenv": "^16.3.1",
    "langchain": "^0.0.117",
    "openai": "^3.3.0",
    "typeorm": "^0.3.17",
    "typescript": "^5.1.6"
  },
```

**Comment by pavelpiha** [comment]
I have similar problem and the problem in `completions`
I have 404 error

```
[1] node_modules\axios\lib\core\createError.js:16
[1]   var error = new Error(message);
[1]               ^
[1] 
[1] Error: Request failed with status code 404
[1]     at createError (D:\demo\ws-ai-server\node_modules\axios\lib\core\createError.js:16:15)
[1]     at settle (D:\demo\ws-ai-server\node_modules\axios\lib\core\settle.js:17:12)
[1]     at IncomingMessage.handleStreamEnd (D:\demo\ws-ai-server\node_modules\axios\lib\adapters\http.js:322:11)
[1]     at IncomingMessage.emit (node:events:526:35)
[1]     at endReadableNT (node:internal/streams/readable:1359:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[1]   config: {
[1]     transitional: {
[1]       silentJSONParsing: true,
[1]       forcedJSONParsing: true,
[1]       clarifyTimeoutError: false
[1]     },

...
       _requestBodyBuffers: [],
[1]       _onNativeResponse: [Function (anonymous)],
[1]       _currentRequest: [Circular *2],
[1]       _currentUrl: 'https://test.openai.azure.com/openai/deployments/**completions**?api-version=test',
[1]       [Symbol(kCapture)]: false
```
Any ideas how to remove **completions** from request?

**Comment by Franckegao** [comment]
@zeason Have you figured this out？I got the same error.

**Comment by zeason** [comment]
> @zeason Have you figured this out？I got the same error.

@Franckegao It turns out that this issue was caused by our endpoint provider changing the backend, introduced more strict http header check.
You may consult to your provider as well.
