### ISSUE TITLE
langchain.js module issue

### ISSUE THREAD

**Issue by Pavel-Piha** [langchain-ai/langchainjs#2092]
Could someone suggest me how to to make it work? 

```
[1] const langchain_js_1 = require("llama-node/dist/extensions/langchain.js");
[1]                        ^
[1]
[1] Error [ERR_REQUIRE_ESM]: require() of ES Module D:\test-server\node_modules\llama-node\dist\extensions\langchain.js from D:\test-server\dist\src\chat-service.js not supported.
[1] Instead change the require of langchain.js in D:\test-server\dist\src\chat-service.js to a dynamic import() which is available in all CommonJS modules.
[1]     at Object.<anonymous> (D:\test-server\dist\src\chat-service.js:8:24)
[1]     at Object.<anonymous> (D:\test-server\dist\index.js:5:24) {
[1]   code: 'ERR_REQUIRE_ESM'
```
I want to use Typescript and ES6 modules in my project

here is my tsconfig.json

```
{
  "compilerOptions": {
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "skipLibCheck": true,
    "target": "esNext",
    "module": "commonjs",
    "lib": ["ESNext"]
  },
  "exclude": ["node_modules"]
}

```

**Comment by jacoblee93** [comment]
Hey @Pavel-Piha - apologies for the delay!

I have this set as my `tsconfig.json` for my test project:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2019",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true
  }
}
```

**Comment by 7emretelli** [comment]
@Pavel-Piha ,
Try importing dynamically like the example below:
```
const LLamaCpp = await import("langchain/llms/llama_cpp")
const model = new LLamaCpp.LlamaCpp({ modelPath: "llamaPath" });
```

**Comment by 7emretelli** [comment]
> Could someone suggest me how to to make it work?
> 
> ```
> [1] const langchain_js_1 = require("llama-node/dist/extensions/langchain.js");
> [1]                        ^
> [1]
> [1] Error [ERR_REQUIRE_ESM]: require() of ES Module D:\test-server\node_modules\llama-node\dist\extensions\langchain.js from D:\test-server\dist\src\chat-service.js not supported.
> [1] Instead change the require of langchain.js in D:\test-server\dist\src\chat-service.js to a dynamic import() which is available in all CommonJS modules.
> [1]     at Object.<anonymous> (D:\test-server\dist\src\chat-service.js:8:24)
> [1]     at Object.<anonymous> (D:\test-server\dist\index.js:5:24) {
> [1]   code: 'ERR_REQUIRE_ESM'
> ```
> 
> I want to use Typescript and ES6 modules in my project
> 
> here is my tsconfig.json
> 
> ```
> {
>   "compilerOptions": {
>     "outDir": "./dist",
>     "esModuleInterop": true,
>     "forceConsistentCasingInFileNames": true,
>     "strict": false,
>     "skipLibCheck": true,
>     "target": "esNext",
>     "module": "commonjs",
>     "lib": ["ESNext"]
>   },
>   "exclude": ["node_modules"]
> }
> ```

Try importing dynamically like the example below:

```
const LLamaCpp = await import("langchain/llms/llama_cpp")
const model = new LLamaCpp.LlamaCpp({ modelPath: "llamaPath" });
```

**Comment by anamariadem** [comment]
Has anyone found a fix for this using `es2021`? I keep experiencing this issue.

**Comment by jacoblee93** [comment]
So I've just set up a brand new project and it looks like `node-llama-cpp` doesn't work with CommonJS due to a top level await.

Can you try with a fresh project and the following config:

`tsconfig.json`
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "skipLibCheck": true,
    "target": "esNext",
    "module": "commonjs",
    "lib": ["ESNext"]
  },
  "exclude": ["node_modules"]
}
```

`package.json`
```
{
  "name": "tsproject",
  "packageManager": "yarn@3.5.1",
  "type": "module",
  "devDependencies": {
    "ts-node": "^10.9.1",
    "tsx": "^3.14.0",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "langchain": "^0.0.168",
    "node-llama-cpp": "^2.7.3"
  }
}
```

**Comment by anamariadem** [comment]
We have NestJS on backend, that comes with a specific tsconfig, if we switch it to type:"module" in package.json it won't work. There's a thread about this here https://github.com/nestjs/nest/issues/10267

**Comment by mhuckstepp** [comment]
I was able to work around this using the following import style in a `.js` file 

```
const getLlama = async () => {
  const { LLamaCpp } = await import('llama-node/dist/llm/llama-cpp.js');
  const { LLM } = await import('llama-node');
  const llama = new LLM(LLamaCpp);
  return llama;
};
```

**Comment by deeeed** [comment]
@mhuckstepp would you have a repo to see? I did try a similar setup but still get the `Error [ERR_REQUIRE_ESM]: require() of ES Module /` error

**Comment by mhuckstepp** [comment]
@deeeed Here is my setup 

``` 
package.json

{
  "name": "strava-image",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "tsc && node dist/index.js",
    "build": "react-scripts build && tsc",
    "test": "jest",
    "build:server": "tsc",
    "dev:server": "ts-node-dev --respawn --transpile-only server/index.ts",
    "start:client": "react-scripts start",
    "test:client": "react-scripts test",
    "dev:client": "react-scripts start",
    "build:client": "react-scripts build"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@googlemaps/polyline-codec": "^1.0.28",
    "@llama-node/llama-cpp": "^0.1.6",
    "@mui/material": "^5.3.1",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.5.1",
    "canvas": "^2.11.2",
    "dayjs": "^1.11.10",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "jimp": "^0.22.10",
    "llama-node": "^0.1.6",
    "mongodb": "4.1",
    "promise-queue": "^2.2.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.1",
    "react-scripts": "^5.0.1",
    "styled-components": "^5.3.3",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "ts-node-dev": "^2.0.0",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.16.7",
    "@types/express": "^4.17.19",
    "@types/jest": "^29.5.5",
    "@types/node": "^20.8.6",
    "@types/supertest": "^2.0.14",
    "eslint": "8.51.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "husky": "^7.0.4",
    "jest": "^29.7.0",
    "lint-staged": "^12.3.2",
    "nodemon": "^3.0.1",
    "prettier": "^2.6.0",
    "supertest": "^6.3.3",
    "typescript": "^4"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
--------
tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "noImplicitAny": false,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": "."
  },
  "include": ["server/**/*"],
  "exclude": ["./dist", "__tests__", "jest.config.js"]
}
--------------------
llama.js
const getLlama = async () => {
  const { LLamaCpp } = await import('llama-node/dist/llm/llama-cpp.js');
  const { LLM } = await import('llama-node');
  const llama = new LLM(LLamaCpp);
  return llama;
};

const config = {
  modelPath: './models/airoboros-13b-gpt4.ggmlv3.q4_0.bin',
  enableLogging: true,
  nCtx: 1024,
  seed: 0,
  f16Kv: false,
  logitsAll: false,
  vocabOnly: false,
  useMlock: false,
  embedding: false,
  useMmap: true,
  nGpuLayers: 0,
};

const getAiText = async (prompt) => {
  try {
    console.log('Loading model, prompt:', prompt);
    const llama = await getLlama();
    await llama.load(config);
    console.log('Loaded model ');
    let responseText = '';
    await llama.createCompletion(
      {
        nThreads: 4,
        nTokPredict: 2048,
        topK: 40,
        topP: 0.1,
        temp: 0.2,
        repeatPenalty: 1,
        prompt,
      },
      (response) => {
        console.log({ response });
        if (response.token && response.completed === false) {
          responseText += response.token;
        }
      },
    );
    return responseText;
  } catch (e) {
    console.log(e);
  }
};

module.exports = { getAiText };
```

**Comment by mikjee** [comment]
I faced the same issue, while using import in my TS project. I tried using tsc, ts-node and nodemon, but none of those worked, however I was able to make it work with [tsx](https://github.com/privatenumber/tsx).
