### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'usage')

### ISSUE THREAD

**Issue by beacoding** [langchain-ai/langchainjs#2104]
```
TypeError: Cannot read properties of undefined (reading 'usage')
    at (node_modules/langchain/dist/chat_models/openai.js:419:118)
    at (node_modules/langchain/dist/chat_models/base.js:45:24)
    at (node_modules/langchain/dist/chains/llm_chain.js:118:32)
    at (node_modules/langchain/dist/chains/base.js:87:27)
```

Looks like it's trying to access `data.usage` but no handling if data is undefined

https://github.com/hwchase17/langchainjs/blob/efc486f1f7ee0f553e459b51f2a3a2ab6d221bf9/langchain/src/llms/openai.ts#L398C28-L398C28

**Comment by lxcid** [comment]
faced this issue but its intermittent.
