### ISSUE TITLE
MyScaleStore Broken

### ISSUE THREAD

**Issue by josiahbryan** [langchain-ai/langchainjs#2204]
Using versions:
```
"@clickhouse/client": "^0.2.0",
"langchain": "^0.0.124",
```

Node:
```
% node -v
v20.5.0
```

When running:
```
const vectorStore = await MyScaleStore.fromExistingIndex(embeddings, connectionDetails);
```

I get the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:274:3)
    at ClientRequest.once (node:events:648:3)
    at new ClientRequest (node:_http_client:239:10)
    at Proxy.request (node:https:377:10)
    at Proxy.<anonymous> (/Users/josiahbryan/devel/rubber/backend/node_modules/proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at Proxy.<anonymous> (/Users/josiahbryan/devel/rubber/backend/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
    at NodeHttpsConnection.createClientRequest (/Users/josiahbryan/devel/rubber/backend/node_modules/@clickhouse/client/dist/connection/node_https_connection.js:40:32)
    at /Users/josiahbryan/devel/rubber/backend/node_modules/@clickhouse/client/dist/connection/node_base_connection.js:85:34
    at new Promise (<anonymous>)
    at NodeHttpsConnection._request (/Users/josiahbryan/devel/rubber/backend/node_modules/@clickhouse/client/dist/connection/node_base_connection.js:83:16)
    at NodeHttpsConnection.request (/Users/josiahbryan/devel/rubber/backend/node_modules/@clickhouse/client/dist/connection/node_base_connection.js:64:31)
    at NodeHttpsConnection.exec (/Users/josiahbryan/devel/rubber/backend/node_modules/@clickhouse/client/dist/connection/node_base_connection.js:280:35)
    at ClickHouseClient.exec (/Users/josiahbryan/devel/rubber/backend/node_modules/@clickhouse/client-common/dist/client.js:98:38)
    at MyScaleStore.initialize (/Users/josiahbryan/devel/rubber/backend/node_modules/langchain/dist/vectorstores/myscale.js:141:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MyScaleStore.fromExistingIndex (/Users/josiahbryan/devel/rubber/backend/node_modules/langchain/dist/vectorstores/myscale.js:122:9)
    at async getMyScaleStore (/Users/josiahbryan/devel/rubber/backend/src/services/chatbot/utils/graph/node-indexer.js:147:22)
    at async /Users/josiahbryan/devel/rubber/backend/src/services/chatbot/utils/graph/node-indexer.js:638:22
    at async mainWrap (/Users/josiahbryan/devel/rubber/backend/src/utils/script-cli.js:96:2) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by jacoblee93** [comment]
Will have a look tomorrow, thanks!
