### ISSUE TITLE
Using ChatPrompt breaks StructuredOutputParser parser

### ISSUE THREAD

**Issue by pietrobolcato** [langchain-ai/langchainjs#2214]
Hey there, I am trying to generate a simple list of quotes, using langchain with GPT-4. I coded the same logic both in Langchain python and in Langchain JS, but I am getting the problem that in the latter, I can't use ChatPrompt without breaking the StructuredOutputParser parser, getting errors like:

```
OutputParserException [Error]: Failed to parse. Text: "[{"lc":1,"type":"constructor","id":["langchain","schema","AssistantMessage"],"kwargs":{"content":"```json\n{\n    \"quotes\": [\n        \"The only way to do great work is to love what you do.\",\n        \"Success usually comes to those who are too busy to be looking for it.\",\n        \"The harder you work for something, the greater you'll feel when you achieve it.\"\n    ]\n}\n```","additional_kwargs":{}}}]". Error: SyntaxError: Unexpected token '\', "\n{\n    \"... is not valid JSON
    at StructuredOutputParser.parse (C:\Users\pietr\Documents\Kittl\code\langchain_js\node_modules\langchain\dist\output_parsers\structured.cjs:58:19)
    at main (C:\Users\pietr\Documents\Kittl\code\langchain_js\test_chain2.js:52:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  output: '[{"lc":1,"type":"constructor","id":["langchain","schema","AssistantMessage"],"kwargs":{"content":"```json\\n{\\n    \\"quotes\\": [\\n        \\"The only way to do great work is to love what you do.\\",\\n        \\"Success usually comes to those who are too busy to be looking for it.\\",\\n        \\"The harder you work for something, the greater you\'ll feel when you achieve it.\\"\\n    ]\\n}\\n```","additional_kwargs":{}}}]'
}
```

My code is the following:

```javascript
// imports
const { OpenAI } = require("langchain/llms/openai");
const { StructuredOutputParser } = require("langchain/output_parsers");
const {
  PromptTemplate,
  HumanMessagePromptTemplate,
  SystemMessagePromptTemplate,
  ChatPromptTemplate,
} = require("langchain/prompts");
const { LLMChain } = require("langchain/chains");
const { z } = require("zod");

async function main() {
  // instantiate model
  const model = new OpenAI({
    temperature: 0.85,
    modelName: "gpt-4",
  });

  // define output schema
  const parser = StructuredOutputParser.fromZodSchema(
    z.object({
      quotes: z.array(z.string()).describe("list of quotes"),
    })
  );

  // create template
  const formatInstructions = parser.getFormatInstructions();

  const prompt = new PromptTemplate({
    template:
      "Answer the user query.\n{format_instructions}\nGive me {num_output} quotes.\n",
    inputVariables: ["num_output"],
    partialVariables: { format_instructions: formatInstructions },
  });

  // create prompts
  const systemPrompt = SystemMessagePromptTemplate.fromTemplate(
    "You are a helpful assistant that writes creative quotes, following instructions."
  );
  const userPrompt = new HumanMessagePromptTemplate({ prompt: prompt });
  const chatPrompt = ChatPromptTemplate.fromPromptMessages([
    systemPrompt,
    userPrompt,
  ]);
  
  // run chain
  const chain = new LLMChain({
    llm: model,
    prompt: chatPrompt,
  });

  const output = await chain.call({
    num_output: 3,
  });
  
  // show parsed results
  console.log(await parser.parse(output.text));
}

main();
```

The strange thing is, if I change:

```javascript
const chain = new LLMChain({
    llm: model,
    prompt: chatPrompt,
  });
```

to:

```javascript
const chain = new LLMChain({
    llm: model,
    prompt: prompt,
  });
```

So not using `ChatPromptTemplate ` but `PromptTemplate`, it works. Is this intended? How is it possible to specify a system message and still get the output parsed correctly?

Thanks a lot in advance!

**Comment by pietrobolcato** [comment]
For reference, this is the corresponding working python code:

```python
class Quote(BaseModel):
    quotes: List[str] = Field(description="list of quotes")

def perform_inference_chat_model(
    model_name: str,
    temperature: float,
    num_output: int,
) -> None:
    """Perform inference using a chat-based model."""
    model = ChatOpenAI(model_name=model_name, temperature=temperature)

    # setup parser and templates
    parser = PydanticOutputParser(pydantic_object=Quote)

    prompt = PromptTemplate(
        template="Answer the user query.\n{format_instructions}\nGive me {num_output} quotes.\n",
        input_variables=["num_output"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )

    # format chat prompt
    system_prompt = SystemMessage(content="You are a helpful assistant that writes creative quotes, following instructions.")
    user_prompt = HumanMessagePromptTemplate(prompt=prompt)

    chat_prompt = ChatPromptTemplate.from_messages([system_prompt, user_prompt])

    # create chain
    chain = LLMChain(llm=model, prompt=chat_prompt)

    # perform inference
    output = chain.run(
        num_output=num_output,
        tone=tone,
        niche=niche,
        length=length
    ) 

    # show results
    parsed_output = parser.parse(output)
    print(parsed_output)
```

This gets parsed always correctly, and it does use `ChatPromptTemplate`.

**Comment by babeal** [comment]
After debugging, the conversion of the ChatPromptTemplate to an actual string prompt results in a serialization of the entire ChatPromptValue object which breaks the contract with the base LLM classes. See `/prompts/chat.ts` ChatPromptValue.toString() method as is results in a serialization of the prompt object. I maybe wrong but it seems that the ChatPromptTemplate can only be used with chat_models as I don't see a way the standard LLM classes work. It's a very strange implementation.
