### ISSUE TITLE
Issues when trying to use in a VisualStudio Code Extension

### ISSUE THREAD

**Issue by lintonye** [langchain-ai/langchainjs#230]
Hi, 

I'm trying to figure out how to use LangChain in a VisualStudio Code extension. I'm aware that the lib currently doesn't support this environment, but maybe someone could give some pointers and I could hopefully create a PR?

Got this error whenever I try to import `OpenAIChat`: 

```
Error: ENOENT: no such file or directory, open '/vscode-chatgpt/out/encoder.json'
    at Object.openSync (/vscode-chatgpt/lib/fs.js:585:3)
    at Object.func [as openSync] (/vscode-chatgpt/lib/electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (/vscode-chatgpt/lib/fs.js:453:35)
    at Object.e.readFileSync (/vscode-chatgpt/lib/electron/js2c/asar_bundle.js:5:9160)
    at node_modules/gpt-3-encoder/Encoder.js (/vscode-chatgpt/node_modules/gpt-3-encoder/Encoder.js:5:31)
    at __require (/vscode-chatgpt/out/extension.js:12:50)
    at node_modules/gpt-3-encoder/index.js (/vscode-chatgpt/node_modules/gpt-3-encoder/index.js:1:28)
    at __require (/vscode-chatgpt/out/extension.js:12:50)
    at node_modules/langchain/dist/llms/base.js (/vscode-chatgpt/node_modules/langchain/src/llms/base.ts:1:24)
    at init_base (/vscode-chatgpt/out/extension.js:9:56)
    at node_modules/langchain/dist/llms/index.js (/vscode-chatgpt/node_modules/langchain/src/llms/index.ts:1:1)
    at __init (/vscode-chatgpt/out/extension.js:9:56)
    at node_modules/langchain/llms.js (/vscode-chatgpt/node_modules/langchain/llms.js:1:1)
    at __init (/vscode-chatgpt/out/extension.js:9:56)
    at /vscode-chatgpt/src/chatgpt-view-provider.ts:142:33
    at ChatGptViewProvider.sendApiRequest (/vscode-chatgpt/src/chatgpt-view-provider.ts:142:27) {errno: -2, syscall: 'open', code: 'ENOENT', path: '/vscode-chatgpt/out/encoder.json', stack: 'Error: ENOENT: no such file or directory, ope…-chatgpt/src/chatgpt-view-provider.ts:142:27)', …}
rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open '/vscode-chatgpt/out/encoder.json'
stack trace: Error: ENOENT: no such file or directory, open '/vscode-chatgpt/out/encoder.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at node_modules/gpt-3-encoder/Encoder.js (/vscode-chatgpt/node_modules/gpt-3-encoder/Encoder.js:5:31)
    at __require (/vscode-chatgpt/out/extension.js:12:50)
    at node_modules/gpt-3-encoder/index.js (/vscode-chatgpt/node_modules/gpt-3-encoder/index.js:1:28)
    at __require (/vscode-chatgpt/out/extension.js:12:50)
    at node_modules/langchain/dist/llms/base.js (/vscode-chatgpt/node_modules/langchain/src/llms/base.ts:1:24)
    at init_base (/vscode-chatgpt/out/extension.js:9:56)
    at node_modules/langchain/dist/llms/index.js (/vscode-chatgpt/node_modules/langchain/src/llms/index.ts:1:1)
    at __init (/vscode-chatgpt/out/extension.js:9:56)
    at node_modules/langchain/llms.js (/vscode-chatgpt/node_modules/langchain/llms.js:1:1)
    at __init (/vscode-chatgpt/out/extension.js:9:56)
    at /vscode-chatgpt/src/chatgpt-view-provider.ts:142:33
    at ChatGptViewProvider.sendApiRequest (/vscode-chatgpt/src/chatgpt-view-provider.ts:142:27)
```

Here's my `tsconfig.json`:

```json
{
	"compilerOptions": {
		"module": "NodeNext",
		"target": "ES2020",
		"lib": [
			"ES2020"
		],
		"sourceMap": true,
		"rootDir": "src",
		"strict": true /* enable all strict type-checking options */
	}
}
```

I'm using dynamic imports as the extension uses commonJS:

```ts
			const { PromptTemplate } = await import("langchain/prompts");
			const { OpenAIChat } = await import("langchain/llms");
			const { LLMChain } = await import("langchain");
```

**Comment by lintonye** [comment]
Update: I actually got it working:
1. copy two files `vocab.bpe` and `encoder.json` from `node_modules/gpt3-encoder` to `out`
2. add `node-fetch` to deps and follow [these instructions](https://github.com/node-fetch/node-fetch#providing-global-access)

**Comment by nfcampos** [comment]
Hi @lintonye great that you got it working! we've switched out that gpt3-encoder dependency in the latest version, if you try to update to 0.0.23 that might work too

**Comment by lintonye** [comment]
Thanks @nfcampos. Yup after updating to the latest, that error went away. However, I got a similar issue when trying to use `HNSWLib`. The error is "Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`", even though I've already installed it. Copying that to `out` doesn't solve the problem unfortunately. I think it's because it couldn't find the dependency, right?

```ts
            const { HNSWLib } = await import('langchain/vectorstores');
            const vectorDb = await HNSWLib.fromDocuments(docs, embeddings);
```

**Comment by lintonye** [comment]
Update: 0.0.26 added some new deps which cause issue as well.

**Comment by nfcampos** [comment]
@lintonye on hnswlib, that's a node-only dependency as it uses some native bindings, not sure if it would correctly in VSCode? 
On 0.0.26, do you know which dependency?

**Comment by lintonye** [comment]
@nfcampos A whole bunch of errors after installing 0.0.33

```
✘ [ERROR] No matching export in "node_modules/langchain/dist/cache.js" for import "getKey"

    node_modules/langchain/dist/llms/base.js:3:9:
      3 │ import { getKey, InMemoryCache } from "../cache.js";
        ╵          ~~~~~~

1 error
[watch] build finished
[watch] build started (change: "node_modules/langchain/dist/document_loaders/pdf.js.map")
✘ [ERROR] Could not resolve "./chat/index.js"

    node_modules/langchain/dist/agents/index.js:4:26:
      4 │ export { ChatAgent } from "./chat/index.js";
        ╵                           ~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./sql_db/sql_db_chain.js"

    node_modules/langchain/dist/chains/index.js:10:34:
      10 │ export { SqlDatabaseChain, } from "./sql_db/sql_db_chain.js";
         ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./chat_convo/index.js"

    node_modules/langchain/dist/agents/initialize.js:3:40:
      3 │ import { ChatConversationalAgent } from "./chat_convo/index.js";
        ╵                                         ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./chat/index.js"

    node_modules/langchain/dist/agents/initialize.js:4:26:
      4 │ import { ChatAgent } from "./chat/index.js";
        ╵                           ~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./selectors/LengthBasedExampleSelector.js"

    node_modules/langchain/dist/prompts/index.js:3:43:
      3 │ ...eSelector } from "./selectors/LengthBasedExampleSelector.js";
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./selectors/SemanticSimilarityExampleSelector.js"

    node_modules/langchain/dist/prompts/index.js:4:50:
      4 │ ...or } from "./selectors/SemanticSimilarityExampleSelector.js";
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

6 errors
[watch] build finished
[watch] build started (change: "node_modules/langchain/dist/agents/tools/dadjokeapi.js")
✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the
  bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "aws-sdk"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
      76 │   const AWS = require('aws-sdk');
         ╵                       ~~~~~~~~~

  You can mark the path "aws-sdk" as external to exclude it from the
  bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of
  bundle-time.

✘ [ERROR] Could not resolve "mkdirp"

    node_modules/typeorm/driver/better-sqlite3/BetterSqlite3Driver.js:5:49:
      5 │ const mkdirp_1 = tslib_1.__importDefault(require("mkdirp"));
        ╵                                                  ~~~~~~~~

  The module "./dist/cjs/src/index-cjs.js" was not found on the file
  system:

    node_modules/typeorm/node_modules/mkdirp/package.json:26:19:
      26 │         "default": "./dist/cjs/src/index-cjs.js"
         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "mkdirp" as external to exclude it from the
  bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "mkdirp"

    node_modules/typeorm/driver/sqlite/SqliteDriver.js:5:49:
      5 │ const mkdirp_1 = tslib_1.__importDefault(require("mkdirp"));
        ╵                                                  ~~~~~~~~

  The module "./dist/cjs/src/index-cjs.js" was not found on the file
  system:

    node_modules/typeorm/node_modules/mkdirp/package.json:26:19:
      26 │         "default": "./dist/cjs/src/index-cjs.js"
         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "mkdirp" as external to exclude it from the
  bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

5 errors
[watch] build finished
[watch] build started (change: "node_modules/langchain/dist/agents/agent_toolkits/openapi/prompt.js")
✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the
  bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "aws-sdk"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
      76 │   const AWS = require('aws-sdk');
         ╵                       ~~~~~~~~~

  You can mark the path "aws-sdk" as external to exclude it from the
  bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of
  bundle-time.

3 errors
[watch] build finished
```

**Comment by nfcampos** [comment]
Hi @lintonye is it possible there is some local issue in your installation? If you look on npm for version 0.0.33 here https://www.npmjs.com/package/langchain?activeTab=explore and browse to the file `list/llms/base.js` referenced in your first error, it does not contain the import printed in your error.

Can you maybe reinstall, it looks like somehow you have some old version installed instead perhaps?
