### ISSUE TITLE
AzureOpenAI Content Filter Error cause unhandled error

### ISSUE THREAD

**Issue by xMHW** [langchain-ai/langchainjs#2346]
```api:dev: /Users/hwmin414/**/node_modules/.pnpm/langchain@0.0.131_@aws-sdk+client-s3@3.382.0_@supabase+supabase-js@2.31.0_axios@1.4.0_cheerio_esyesgfxlqlyse2qn4tpgidyoy/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:356
api:dev:         return new axios_1.default.AxiosError(message, axios_1.default.AxiosError[code], config, request, response);
api:dev:                ^
api:dev: AxiosError: Request failed with status code 400 and body {"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}
api:dev:     at createError (/Users/hwmin414/**/node_modules/.pnpm/langchain@0.0.131_@aws-sdk+client-s3@3.382.0_@supabase+supabase-js@2.31.0_axios@1.4.0_cheerio_esyesgfxlqlyse2qn4tpgidyoy/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:356:16)
api:dev:     at settle (/Users/hwmin414/**/node_modules/.pnpm/langchain@0.0.131_@aws-sdk+client-s3@3.382.0_@supabase+supabase-js@2.31.0_axios@1.4.0_cheerio_esyesgfxlqlyse2qn4tpgidyoy/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:38:16)
api:dev:     at /Users/hwmin414/**/node_modules/.pnpm/langchain@0.0.131_@aws-sdk+client-s3@3.382.0_@supabase+supabase-js@2.31.0_axios@1.4.0_cheerio_esyesgfxlqlyse2qn4tpgidyoy/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:190:19
api:dev:     at new Promise (<anonymous>)
api:dev:     at fetchAdapter (/Users/hwmin414/**/node_modules/.pnpm/langchain@0.0.131_@aws-sdk+client-s3@3.382.0_@supabase+supabase-js@2.31.0_axios@1.4.0_cheerio_esyesgfxlqlyse2qn4tpgidyoy/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:182:12)
api:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:     at RetryOperation._fn (/Users/hwmin414/**/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)
```

Langchain version 0.0.131
OpenAI version 3.3.0

AzureOpenAI Chat model keeps faults with the above no matter how I wrap call functions with error handlers(try catch, promise.catch, ...)
It keeps causing my NestJS process to die.

I have no clue where to debug this. Just don't recommend me to try with other input(I knew it worked well for the other cases).
I need help with how I can catch this error.

**Comment by jacoblee93** [comment]
This will be hopefully resolved when we integrate the new OpenAI SDK (#2389)

**Comment by guidorietbroek** [comment]
This should be handled by the fallback, right? Otherwise the fallback has no point?

**Comment by willemmulder** [comment]
In general a Content Filter Error should not cause an unhandled error. If the error was properly handled, retry- and fallback-mechanisms would work.
