### ISSUE TITLE
TypeError fails  Chroma SimilaritySearches in OpenAIEmbeddings.

### ISSUE THREAD

**Issue by fhagstroem72** [langchain-ai/langchainjs#2570]
In short, the function

async embedQuery(text)     allows for 'any' type to sent.  Fails when using Chroma... 

langchain/dist/embeddings/openai.js:164
            input: this.stripNewLines ? text.replace(/\n/g, " ") : text,
                                             ^
TypeError: text.replace is not a function

--
    at OpenAIEmbeddings.embedQuery (file:///Users/fred/GPT/jsclient/node_modules/langchain/dist/embeddings/openai.js:164:46)
    at Chroma.similaritySearch (file:///Users/fred/GPT/jsclient/node_modules/langchain/dist/vectorstores/base.js:103:90)
--

**Comment by jacoblee93** [comment]
Can you share code so that I can repro? I don't quite understand the issue at the moment - it's typed to take a string:

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/embeddings/openai.ts#L184
