### ISSUE TITLE
[BUG] TypeError: promptMessage.inputVariables is not iterable

### ISSUE THREAD

**Issue by Pickupppp** [langchain-ai/langchainjs#2632]
environment:

`"langchain": "^0.0.138",`

when I running the following code, it occurs an Exception:

```
const { ChatPromptTemplate } = require("langchain/prompts");

const chatPrompt = ChatPromptTemplate.fromPromptMessages([
  [
    "system",
    "You are a helpful assistant that translates {input_language} to {output_language}.",
  ],
  ["human", "{text}"],
]);
```

```
C:\Users\xxx\Desktop\work\nodejs-demo\node_modules\langchain\dist\prompts\chat.cjs:338
            for (const inputVariable of promptMessage.inputVariables) {
                                                      ^

TypeError: promptMessage.inputVariables is not iterable
    at ChatPromptTemplate.fromPromptMessages (C:\Users\xxx\Desktop\work\nodejs-demo\node_modules\langchain\dist\prompts\chat.cjs:338:55)
    at Object.<anonymous> (C:\Users\xxx\Desktop\work\nodejs-demo\test.js:7:39)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by jacoblee93** [comment]
Hey @Pickupppp, support for message likes (like that tuple) was added in 0.0.144 - can you upgrade and try again?

https://github.com/langchain-ai/langchainjs/releases/tag/0.0.144

**Comment by miniboxhaha** [comment]
same issue. and the response seem not correct
first **https://reference.langchain.com/javascript/classes/_langchain_core.prompts.ChatPromptTemplate.html#fromtemplate** shows ChatPromptTemplate in @langchain/core/prompts, not langchain/prompts
secont **https://docs.langchain.com/oss/javascript/migrate/langchain-v1#dropped-node-18-support** shows there is no mehtod ChatPromptTemplate.fromPromptMessages
