### ISSUE TITLE
PineconeClient is deprecated.

### ISSUE THREAD

**Issue by toypilot** [langchain-ai/langchainjs#2643]
Hello. 
Pinecone node libaray is upgrade to v1
There is a problem with that.
```typescript
export { Pinecone } from './pinecone';
export { Index } from './data';
export * as Errors from './errors';
export type { CollectionDescription, CollectionList, CollectionName, ConfigureIndexOptions, CreateCollectionOptions, CreateIndexOptions, DeleteCollectionOptions, DeleteIndexOptions, DescribeCollectionOptions, DescribeIndexOptions, IndexDescription, IndexList, IndexName, PartialIndexDescription, PartialCollectionDescription, } from './control';
export type { DeleteManyByFilterOptions, DeleteManyByRecordIdOptions, DeleteManyOptions, DeleteOneOptions, DescribeIndexStatsOptions, FetchOptions, FetchResponse, IndexStatsDescription, IndexStatsNamespaceSummary, PineconeConfiguration, PineconeRecord, UpdateOptions, QueryByRecordId, QueryByVectorValues, QueryOptions, QueryResponse, QueryShared, RecordId, RecordMetadata, RecordMetadataValue, RecordSparseValues, RecordValues, ScoredPineconeRecord, } from './data';
export { PineconeClient } from './v0';
export { utils } from './v0/utils';
export { CreateCollectionRequest, CreateRequest, DeleteRequest, IndexMeta, PatchRequest, QueryRequest, QueryVector, ScoredVector, UpdateRequest, UpsertRequest, Vector, } from './pinecone-generated-ts-fetch';
``` 

As you can see, PineconeClient and utils are deprecated.
As a result, PineconeStore can not be created.
I am using these versions.
"langchain": "^0.0.150"
"@pinecone-database/pinecone": "^1.0.1"

Please, fix this error,

**Comment by LukasGaebler** [comment]
Any updates on this? Does someone know if somebody is looking at this?

**Comment by srikanthcanny** [comment]
Isn't this fixed in #2648?

**Comment by RodrigoLegendre** [comment]
Not fixed as of 2023-10-15.

I still get:
```
TS2740: Type  Index<RecordMetadata>  is missing the following properties from type  VectorOperationsApi :  _deleteRaw, _delete, delete1Raw, delete1 , and  16  more.
pinecone.d.ts(8, 5): The expected type comes from property  pineconeIndex  which is declared here on type  PineconeLibArgs 
```

on the `pineconeIndex: index,` on:
```
await PineconeStore.fromDocuments(docs, embeddings, {
    pineconeIndex: index,
    namespace: PINECONE_NAME_SPACE,
    textKey: 'text',
});
```

where:
`const index = client.Index(PINECONE_INDEX_NAME);`
and
`client: Pinecone` (not `PineconeClient`)

I have no idea how to fix it.

**Comment by RodrigoLegendre** [comment]
The Typescript definitions for `VectorOperationsApi` are still using the deprecated `PineconeClient` as ReturnType for `index()`?

pinecone.d.ts:
```
type VectorOperationsApi = ReturnType<import("@pinecone-database/pinecone").PineconeClient["Index"]>;
export interface PineconeLibArgs extends AsyncCallerParams {
    pineconeIndex: VectorOperationsApi;
    textKey?: string;
    namespace?: string;
    filter?: PineconeMetadata;
}
```

**Comment by aditya0shah** [comment]
Is there any updates on this? Or rather updated ways to get around this error? `PineconeStore.fromTexts()` also has the same issue of not being able to pass `index` (`const index = pinecone.Index("index-name")`)to `pineconeIndex` inside of dbConfig.

**Comment by richard523** [comment]
```
await PineconeStore.fromDocuments(docs, embeddings, {
            pineconeIndex: index,
            namespace: namespace
            // maxConcurrency: 5, // Maximum number of batch requests to allow at once. Each batch is 1000 vectors.
          });
```
          
```
error PineconeNotFoundError: A call to https://api.pinecone.io/indexes/pdf-chat-serverless returned HTTP status 404.
    at mapHttpStatusError (/home/chard_unix/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/@pinecone-database+pinecone@2.1.0/node_modules/@pinecone-database/pinecone/dist/errors/http.js:183:20)
    at /home/chard_unix/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/@pinecone-database+pinecone@2.1.0/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:65:50
    at step (/home/chard_unix/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/@pinecone-database+pinecone@2.1.0/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:33:23)
    at Object.next (/home/chard_unix/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/@pinecone-database+pinecone@2.1.0/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:14:53)
    at fulfilled (/home/chard_unix/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/@pinecone-database+pinecone@2.1.0/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: undefined,
  attemptNumber: 7,
  retriesLeft: 0
```
I get a 404 timeout error for this one. Exceeding the ratelimits maybe.

**Comment by richard523** [comment]
```
await PineconeStore.fromDocuments(docs, embeddings, {
            pineconeIndex: index,
            namespace: namespace
            // maxConcurrency: 5, // Maximum number of batch requests to allow at once. Each batch is 1000 vectors.
          });
```
```
error PineconeNotFoundError: A call to https://api.pinecone.io/indexes/pdf-chat-serverless returned HTTP status 404.
```

I'm getting different error though.
