### ISSUE TITLE
gpt-3.5-turbo-instruct fails in langchain

### ISSUE THREAD

**Issue by BingruLin** [langchain-ai/langchainjs#2665]
OpenAI has recently released  gpt-3.5-turbo-instruct which is a completion model rather than chat model just like text-davinci-003.
But when I use gpt-3.5-turbo-instruct through langchain@0.0.150, the request fails and my code is as below:
```
const llm = new OpenAI({
  openAIApiKey: openAiConfig.apiKey,
  maxTokens: 2000,
  temperature: 0,
  modelName: "gpt-3.5-turbo-instruct"
}, {
  basePath: openAiConfig.basePath,
});

const chain = new LLMChain({
  llm,
  prompt: myPromptTemplate,
});

const res = await chain.call();
```

and the error is
```
NotFoundError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
    at APIError.generate (/Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/_openai@4.4.0@openai/error.js:55:14)
    at OpenAI.makeStatusError (/Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/_openai@4.4.0@openai/core.js:312:29)
    at OpenAI.makeRequest (/Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/_openai@4.4.0@openai/core.js:352:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/_langchain@0.0.150@langchain/dist/llms/openai-chat.cjs:385:29
    at async RetryOperation._fn (/Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/_p-retry@4.6.2@p-retry/index.js:50:12) {
```

I think the reason is code in langchain:
```
if (fields?.modelName?.startsWith("gpt-3.5-turbo") ||
    fields?.modelName?.startsWith("gpt-4") ||
    fields?.modelName?.startsWith("gpt-4-32k")) {
    // eslint-disable-next-line no-constructor-return, @typescript-eslint/no-explicit-any
    return new OpenAIChat(fields, configuration);
}
```

**Comment by jacoblee93** [comment]
Yes, this will be fixed in 0.0.151 which I will cut in the next 10 minutes!

**Comment by BingruLin** [comment]
thank you!

**Comment by jacoblee93** [comment]
Live as 0.0.151!
