### ISSUE TITLE
`TypeError: text.replace is not a function`

### ISSUE THREAD

**Issue by dmitrizzle** [langchain-ai/langchainjs#2736]
I'm getting `TypeError: text.replace is not a function` error when trying to run with Redis. I'm using Node 18 in Docker (I looked at #810 and that doesn't solve the issue for me).

Here's what I'm trying to run:
```javascript
      const vectorStore = new RedisVectorStore(new OpenAIEmbeddings(), {
        redisClient: client,
        indexName: REDIS_INDEX_NAME,
      });

      const parser = StructuredOutputParser.fromNamesAndDescriptions({
        answer: "Answer: ",
      });
      const formatInstructions = parser.getFormatInstructions();

      const template = `${PROMPT_PERSONA}\n Question: {question}`;
      const query = new PromptTemplate({
        template,
        inputVariables: ["question"],
        partialVariables: { format_instructions: formatInstructions },
      });

      const model = new OpenAI({ temperature: 0 });
      const chain = RetrievalQAChain.fromLLM(
        model,
        vectorStore.asRetriever(1),
        {
          returnSourceDocuments: true,
        }
      );
      const chainRes = await chain.call({ query });

      const result = await chain.call({
        chainRes,
      });
```

Am I doing something wrong?
Thanks for your help!

**Edit:** stack trace below.
```
 TypeError: text.replace is not a function
    at OpenAIEmbeddings.embedQuery (file:///node_modules/langchain/dist/embeddings/openai.js:164:46)
    at RedisVectorStore.similaritySearch (file:///node_modules/langchain/dist/vectorstores/base.js:103:90)
    at VectorStoreRetriever._getRelevantDocuments (file:///node_modules/langchain/dist/vectorstores/base.js:68:33)
    at VectorStoreRetriever.getRelevantDocuments (file:///node_modules/langchain/dist/schema/retriever.js:66:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetrievalQAChain._call (file:///node_modules/langchain/dist/chains/retrieval_qa.js:55:22)
    at async RetrievalQAChain.call (file:///node_modules/langchain/dist/chains/base.js:101:28)
    at async file:///app/index.js:43:24
```

**Edit 2:** line 43 in `app/index.js` is `const chainRes = await chain.call({ query });` in the block above.

**Comment by hmbrg** [comment]
How did you fix this? Running into the same issue here...
