### ISSUE TITLE
NextJS Edge runtime fs module error implementing ChatBedrock 

### ISSUE THREAD

**Issue by blackmouth** [langchain-ai/langchainjs#2769]
I ran into an issue implementing the latest Bedrock chat model running with NextJS edge runtime.

```error
Error: The edge runtime does not support Node.js 'fs' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at (node_modules/next/dist/esm/server/web/globals.js:29:18)
    at (node_modules/@smithy/shared-ini-file-loader/dist-es/getSSOTokenFromFile.js:3:16)
```

My implementation is as follows with the new ChatBedrock api. This setup works fine if it's replaced with any other chat model.

```javascript

const llm = new ChatBedrock({
                model: "anthropic.claude-v2",
                region: "us-west-2",
                maxTokens:streamSettings.max_tokens,
                temperature: streamSettings.temperature,
                stopSequences: ["\n\nHuman:"],
                credentials:{
                    accessKeyId: process.env.APP_ACCESS_KEY_ID,
                    secretAccessKey: process.env.APP_SECRET_ACCESS_KEY
                },
                // modelKwargs: {},
              });
                          
              llm.call((streamSettings.messages)
                  .filter(m => m.role !== 'system')
                  .map(m =>
                    m.role == 'user'
                      ? new HumanMessage(m.content)
                      : new AIMessage(m.content)
                  ),
                {},
                [handlers],
              )
              .catch(console.error);
              
            return newStreamingTextResponse(stream);

````

 #2746

**Comment by jacoblee93** [comment]
Yeah this probably won't work on Edge at the moment - we can look into what it would take to add it

**Comment by jacoblee93** [comment]
Oh, we added a separate web entrypoint - apologies for not following up!

https://js.langchain.com/docs/integrations/chat/bedrock#setup
