### ISSUE TITLE
Notion vectorStore integration breaks when importing a database with an empty row

### ISSUE THREAD

**Issue by natalie-bb** [langchain-ai/langchainjs#2807]
file:///Users/natalie/chatbot/node_modules/langchain/dist/embeddings/openai.js:139
        const batches = chunkArray(this.stripNewLines ? texts.map((t) => t.replace(/\n/g, " ")) : texts, this.batchSize);
                                                              ^
TypeError: Cannot read properties of undefined (reading 'replace')
    at file:///Users/natalie/chatbot/node_modules/langchain/dist/embeddings/openai.js:139:76
    at Array.map (<anonymous>)
    at OpenAIEmbeddings.embedDocuments (file:///Users/natalie/chatbot/node_modules/langchain/dist/embeddings/openai.js:139:63)
    at HNSWLib.addDocuments (file:///Users/natalie/chatbot/node_modules/langchain/dist/vectorstores/hnswlib.js:48:54)
    at Function.fromDocuments (file:///Users/natalie/chatbot/node_modules/langchain/dist/vectorstores/hnswlib.js:258:24)
    at file:///Users/natalie/chatbot/tools/vectorStores/restaurants.ts:27:46
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by jacoblee93** [comment]
@skarard can you have a look at this one?

**Comment by skarard** [comment]
Sure.

**Comment by skarard** [comment]
I was able to reproduce the bug and it opens a pretty solid question.

First the bug:
```typescript
/**
 * Interface for interacting with a document.
 */
export class Document<
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Metadata extends Record<string, any> = Record<string, any>
> implements DocumentInput
{
  pageContent: string;

  metadata: Metadata;

  constructor(fields: DocumentInput<Metadata>) {
    this.pageContent = fields.pageContent
      ? fields.pageContent.toString()
      : this.pageContent;
    this.metadata = fields.metadata ?? ({} as Metadata);
  }
}
```

The constructor for the Document class will set `pageContent` to `undefined` if it's falsy (e.g. an empty string).

A Notion page contains properties that the `NotionAPILoader` store as metadata. Often in a Notion database, a page will not have any contents and the pages properties are where the data is stored.

@natalie-bb a work around to get the script working for now is to replace the `undefined` `pageContent` with an empty string.
```typescript
const workaroundDocs = docs.map(
  (doc) => ({ ...doc, pageContent: doc.pageContent ?? "" } as Document)
);
```

Your code may want to look something like this...
```typescript
const loader = new NotionAPILoader({...});

const docs = await loader.load();

const workaroundDocs = docs.map(
  (doc) => ({ ...doc, pageContent: doc.pageContent ?? "" } as Document)
);

const vectorStore = await HNSWLib.fromDocuments(workaroundDocs, embeddings);
```

@jacoblee93 Should the `Document` class store an empty string if `pageContent` is an empty string?

**Comment by jacoblee93** [comment]
IMO no - it would never get retrieved

**Comment by skarard** [comment]
@natalie-bb I'm going to add a little more context which might not be obvious.

The database properties are not used when running the embeddings, this is to say the only searchable data is `pageContent`, the properties can be used to filter or do a database query (if your vector store supports that).

Something that may be closer to having similar searchable Notion properties is to add the properties as a header to `pageContent`

```typescript
  const workaroundDocs = docs.map(
    (doc) =>
      ({
        ...doc,
        pageContent: `---\n${yaml.dump(doc.metadata.properties)}---\n${doc.pageContent ?? ""}`,
      } as Document)
  );
```

**Comment by skarard** [comment]
> IMO no - it would never get retrieved

Ok, if I understand you correctly, this would mean that HNSWLib will need to support `pageContent` as `undefined`?

**Comment by natalie-bb** [comment]
As a workaround, I simply deleted the empty row.

The error was somewhat obtuse, and it wasn't immediately obvious to me that I needed to do that.

**Comment by jacoblee93** [comment]
> > IMO no - it would never get retrieved
> 
> @jacoblee93 Ok, if I understand you correctly, this would mean that HNSWLib will need to support `pageContent` as `undefined`?

What I mean is it shouldn't be created at all - `pageContent` is a required field:

https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document.ts#L18

**Comment by skarard** [comment]
> > > IMO no - it would never get retrieved
> > 
> > @jacoblee93 Ok, if I understand you correctly, this would mean that HNSWLib will need to support `pageContent` as `undefined`?
> 
> What I mean is it shouldn't be created at all - `pageContent` is a required field:
> 
> https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document.ts#L18

Thank you for your clarification.

The typing for the `Document` class currently suggests that an empty string is a valid `pageContents` but sets this to `undefined` breaking the fields typing. 

Therefore the correct behaviour is for the Document class constructor is to throw an error when page contents are  `string.length == 0`. I'll throw in a new PR for this, you're welcome to close it if you hate the idea. 

I'll also update the NotionAPILoader to check that `pageContents.length > 0` so that a page would not be created. I'll link the issue to this PR.

The adjacent topic for the NotionAPILoader; I plan to create a NotionAPILoaderOption to add the page properties as front matter to page contents (yaml). The default will be the current behaviour, to not add anything. I'll create a new PR for this.
