### ISSUE TITLE
Build error when instantiating FirestoreChatMessageHistory

### ISSUE THREAD

**Issue by Rastamafugg** [langchain-ai/langchainjs#2869]
My langchain setting in my package.json is:
`		"langchain": "^0.0.164"`

When I add code to try to instantiate a new BufferMemory object like this:
```
    const memory = new BufferMemory({
        chatHistory: new FirestoreChatMessageHistory({
            collectionName: "chathistory",
            sessionId,
            userId,
            config: { projectId: "langchain-prompt-tool", credential: admin.credential.cert(JSON.parse(FIREBASE_ADMIN_KEY)) },
        }),
    });

```
I get this error at build time:

```
[commonjs--resolver] Missing "./dist/stores/message/firestore" specifier in "langchain" package                       
error during build:                                                                                                   
Error: Missing "./dist/stores/message/firestore" specifier in "langchain" package                                     
    at e (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:25) 
    at n (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:627)
    at o (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:1297)
    at resolveExportsOrImports (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:28712:20)
    at resolveDeepImport (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:28731:31)
    at tryNodeResolve (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Object.resolveId (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.handler (file:///C:/Users/19029/Development/prompt-tool/node_modules/vite/dist/node/chunks/dep-df561101.js:48234:19)
    at file:///C:/Users/19029/Development/prompt-tool/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by Rastamafugg** [comment]
[This is my Github project branch](https://github.com/Modern-Democracy/prompt-tool/tree/master) I'm working on that is demonstrating the issue.

**Comment by jacoblee93** [comment]
Use `langchain/stores/message/firestore` instead of `langchain/dist/stores/message/firestore`:

https://github.com/Modern-Democracy/prompt-tool/blob/master/src/routes/api/memory-chat/%2Bserver.ts#L7C44-L7C83

**Comment by Rastamafugg** [comment]
Thanks, I overlooked that value in the import.  Now I have to figure out why Webstorm autocomplete set the import path that way!
