### ISSUE TITLE
JSONLoader load each object in array of objects into pagecontent

### ISSUE THREAD

**Issue by kaykhan** [langchain-ai/langchainjs#3071]
I have a json dataset i want to ask questions, i am using the retrieval example to ask it questions such as "What was Lin's revenue" however i dont get any results i believe the json loader is not loading the entire object into the page content. You see i am attempting to combine both the name nad revenue togeather so that it should give me the correct result, but it looks like it comes up in a seperate document so asking that question either gives no result or the wrong result.

ideally the pageContent would contain the entire object?

```
  Document {
    pageContent: 'Kildale',
    metadata: { source: './sales_slim.json', line: 38 }
  },
  Document {
    pageContent: 'Lin',
    metadata: { source: './sales_slim.json', line: 39 }
  },
  Document {
    pageContent: 'De Ambrosi',
    metadata: { source: './sales_slim.json', line: 40 }
  }
```

**code:**
```
import { HNSWLib } from "langchain/vectorstores/hnswlib";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";
import * as fs from "fs";
import {
    RunnablePassthrough,
    RunnableSequence,
} from "langchain/schema/runnable";
import { StringOutputParser } from "langchain/schema/output_parser";
import {
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
} from "langchain/prompts";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { formatDocumentsAsString } from "langchain/util/document";
import { JSONLoader } from "langchain/document_loaders/fs/json";

async function main() {
    // Initialize the LLM to use to answer the question.
    const model = new ChatOpenAI({});
    const text = fs.readFileSync("state_of_the_union.txt", "utf8");
    const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000 });
    //const docs = await textSplitter.createDocuments([text]);

    const loader = new JSONLoader("./sales_slim.json", ["/first_name", "/revenue"]);
    const docs = await loader.load();
    console.log(docs);

    // Create a vector store from the documents.

    const vectorStore = await HNSWLib.fromDocuments(docs, new OpenAIEmbeddings());

    // Initialize a retriever wrapper around the vector store
    const vectorStoreRetriever = vectorStore.asRetriever();

    // Create a system & human prompt for the chat model
    const SYSTEM_TEMPLATE = `Use the following pieces of context to answer the question at the end.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
----------------
{context}`;
    const messages = [
        SystemMessagePromptTemplate.fromTemplate(SYSTEM_TEMPLATE),
        HumanMessagePromptTemplate.fromTemplate("{question}"),
    ];
    const prompt = ChatPromptTemplate.fromMessages(messages);

    const chain = RunnableSequence.from([
        {
            context: vectorStoreRetriever.pipe(formatDocumentsAsString),
            question: new RunnablePassthrough(),
        },
        prompt,
        model,
        new StringOutputParser(),
    ]);

    const answer = await chain.invoke("What was Lin's revenue?");

    console.log({ answer });
}

main();

```

**dataset**
```
[{"date":"2022-03-06 11:06:48","first_name":"Benji","last_name":"Colt","email_address":"bcolt0@spotify.com","Product":"Bread - 10 Grain","category":"Shoes","source":"promotions","street_address":"22 Hoard Parkway","city":"New Orleans","state":"Louisiana","postal_code":"70165","country":"United States","returned":"false","revenue":"$106.30","cost":"$7.10","Repeat Customer?":true,"age":71,"number_of_sales":49326},
{"date":"2022-10-16 17:05:31","first_name":"Lotte","last_name":"Collymore","email_address":"lcollymore1@scribd.com","Product":"Lettuce - Boston Bib","category":"Books","source":"mobile","street_address":"99060 Clarendon Plaza","city":"Fort Worth","state":"Texas","postal_code":"76192","country":"United States","returned":"true","revenue":"$120.85","cost":"$6.34","Repeat Customer?":true,"age":50,"number_of_sales":35773},
{"date":"2022-02-11 13:18:45","first_name":"Ambrose","last_name":"Finnigan","email_address":"afinnigan2@digg.com","Product":"Beer - Fruli","category":"Outdoors","source":"paid social","street_address":"589 Arapahoe Point","city":"Raleigh","state":"North Carolina","postal_code":"27690","country":"United States","returned":"true","revenue":"$50.18","cost":"$6.36","Repeat Customer?":true,"age":73,"number_of_sales":59537},
{"date":"2022-03-02 21:15:18","first_name":"Caressa","last_name":"Yeomans","email_address":"cyeomans3@dagondesign.com","Product":"Loquat","category":"Garden","source":"paid search","street_address":"128 Mayfield Street","city":"Richmond","state":"Virginia","postal_code":"23285","country":"United States","returned":"true","revenue":"$182.99","cost":"$4.05","Repeat Customer?":false,"age":21,"number_of_sales":12242},
{"date":"2022-08-25 21:29:30","first_name":"Woodrow","last_name":"Henighan","email_address":"whenighan4@ft.com","Product":"Gooseberry","category":"Industrial","source":"promotions","street_address":"96049 Debs Pass","city":"Fort Worth","state":"Texas","postal_code":"76178","country":"United States","returned":"false","revenue":"$216.26","cost":"$9.59","Repeat Customer?":false,"age":70,"number_of_sales":59699},
{"date":"2022-09-19 16:35:12","first_name":"Chev","last_name":"Shalcras","email_address":"cshalcras5@baidu.com","Product":"Cocoa Feuilletine","category":"Computers","source":"paid search","street_address":"671 Thompson Terrace","city":"New York City","state":"New York","postal_code":"10060","country":"United States","returned":"true","revenue":"$183.58","cost":"$4.67","Repeat Customer?":true,"age":21,"number_of_sales":40803},
{"date":"2022-11-29 03:17:50","first_name":"Erin","last_name":"Meak","email_address":"emeak6@printfriendly.com","Product":"Swordfish Loin Portions","category":"Grocery","source":"direct","street_address":"2 Eagan Parkway","city":"Atlanta","state":"Georgia","postal_code":"30311","country":"United States","returned":"true","revenue":"$238.29","cost":"$2.26","Repeat Customer?":true,"age":48,"number_of_sales":67034},
{"date":"2022-06-06 03:07:16","first_name":"Ketty","last_name":"Korn","email_address":"kkorn7@auda.org.au","Product":"Paper - Brown Paper Mini Cups","category":"Garden","source":"mobile","street_address":"0786 Talmadge Circle","city":"Washington","state":"District of Columbia","postal_code":"20420","country":"United States","returned":"true","revenue":"$83.91","cost":"$6.52","Repeat Customer?":false,"age":61,"number_of_sales":38836},
{"date":"2022-09-23 17:35:44","first_name":"Terrel","last_name":"Dancey","email_address":"tdancey8@macromedia.com","Product":"Wine - White Cab Sauv.on","category":"Baby","source":"paid social","street_address":"1230 Sundown Avenue","city":"Salinas","state":"California","postal_code":"93907","country":"United States","returned":"true","revenue":"$163.58","cost":"$6.75","Repeat Customer?":false,"age":47,"number_of_sales":5015},
{"date":"2022-12-17 17:12:04","first_name":"Agnella","last_name":"Dimelow","email_address":"adimelow9@economist.com","Product":"Lemonade - Kiwi, 591 Ml","category":"Tools","source":"paid social","street_address":"95 Mccormick Crossing","city":"Washington","state":"District of Columbia","postal_code":"20580","country":"United States","returned":"true","revenue":"$143.74","cost":"$8.07","Repeat Customer?":true,"age":66,"number_of_sales":35717},
{"date":"2022-03-21 06:24:12","first_name":"Wilbur","last_name":"Northern","email_address":"wnortherna@yale.edu","Product":"Liners - Banana, Paper","category":"Garden","source":"video","street_address":"3851 Portage Road","city":"San Diego","state":"California","postal_code":"92153","country":"United States","returned":"true","revenue":"$176.57","cost":"$2.54","Repeat Customer?":false,"age":41,"number_of_sales":89492},
{"date":"2022-06-01 21:50:00","first_name":"Andy","last_name":"Tiesman","email_address":"atiesmanb@storify.com","Product":"Chinese Foods - Chicken Wing","category":"Music","source":"promotions","street_address":"49 Amoth Court","city":"Montgomery","state":"Alabama","postal_code":"36195","country":"United States","returned":"true","revenue":"$202.31","cost":"$2.39","Repeat Customer?":false,"age":25,"number_of_sales":82705},
{"date":"2022-02-20 09:56:54","first_name":"Jonathan","last_name":"Orred","email_address":"jorredc@stanford.edu","Product":"Veal - Knuckle","category":"Computers","source":"paid social","street_address":"77398 Luster Hill","city":"Phoenix","state":"Arizona","postal_code":"85010","country":"United States","returned":"true","revenue":"$214.51","cost":"$5.21","Repeat Customer?":false,"age":50,"number_of_sales":80392},
{"date":"2022-08-28 08:25:21","first_name":"Mathilda","last_name":"Hay","email_address":"mhayd@cbslocal.com","Product":"Peach - Fresh","category":"Grocery","source":"paid search","street_address":"47 Dunning Lane","city":"Atlanta","state":"Georgia","postal_code":"31106","country":"United States","returned":"true","revenue":"$245.28","cost":"$7.38","Repeat Customer?":false,"age":31,"number_of_sales":35733},
{"date":"2022-03-02 04:48:39","first_name":"Sargent","last_name":"Evered","email_address":"severede@devhub.com","Product":"Bagelers - Cinn / Brown Sugar","category":"Electronics","source":"video","street_address":"4284 Manufacturers Street","city":"Portland","state":"Maine","postal_code":"04109","country":"United States","returned":"true","revenue":"$162.85","cost":"$7.47","Repeat Customer?":true,"age":30,"number_of_sales":53644},
{"date":"2022-09-04 01:55:15","first_name":"Richie","last_name":"Atwell","email_address":"ratwellf@statcounter.com","Product":"Bread - Flat Bread","category":"Outdoors","source":"promotions","street_address":"328 Dwight Parkway","city":"Corpus Christi","state":"Texas","postal_code":"78465","country":"United States","returned":"false","revenue":"$71.89","cost":"$5.49","Repeat Customer?":true,"age":57,"number_of_sales":87537},
{"date":"2022-09-23 13:04:19","first_name":"Giles","last_name":"Hayter","email_address":"ghayterg@meetup.com","Product":"Chinese Foods - Cantonese","category":"Automotive","source":"paid search","street_address":"8178 Eastwood Way","city":"Denton","state":"Texas","postal_code":"76205","country":"United States","returned":"true","revenue":"$131.65","cost":"$6.78","Repeat Customer?":false,"age":27,"number_of_sales":22787},
{"date":"2022-10-30 14:17:02","first_name":"Franky","last_name":"Andrioletti","email_address":"fandriolettih@google.es","Product":"Barramundi","category":"Jewelry","source":"video","street_address":"60 Sherman Plaza","city":"Dayton","state":"Ohio","postal_code":"45490","country":"United States","returned":"false","revenue":"$17.91","cost":"$4.53","Repeat Customer?":false,"age":73,"number_of_sales":45414},
{"date":"2022-11-22 14:53:53","first_name":"Whit","last_name":"Kildale","email_address":"wkildalei@linkedin.com","Product":"Apple - Royal Gala","category":"Music","source":"promotions","street_address":"3 Sunbrook Way","city":"Washington","state":"District of Columbia","postal_code":"20268","country":"United States","returned":"true","revenue":"$256.24","cost":"$6.21","Repeat Customer?":false,"age":26,"number_of_sales":11033},
{"date":"2022-07-03 03:36:48","first_name":"Lin","last_name":"De Ambrosi","email_address":"ldeambrosij@hatena.ne.jp","Product":"Squid - Breaded","category":"Movies","source":"video","street_address":"9150 Barby Drive","city":"Crawfordsville","state":"Indiana","postal_code":"47937","country":"United States","returned":"false","revenue":"$172.29","cost":"$6.52","Repeat Customer?":true,"age":55,"number_of_sales":43321}
]
```

**Comment by kaykhan** [comment]
I believe i need to do something like this - https://github.com/langchain-ai/langchain/discussions/6378

not sure how with .js version of langchain

**Comment by kaykhan** [comment]
If i ommit the JSONPointer

```
    const loader = new JSONLoader("./sales_slim.json");
```

I get

```
  Document {
    pageContent: '2022-09-19 16:35:12',
    metadata: { source: './sales_slim.json', line: 76 }
  },
  Document {
    pageContent: 'Chev',
    metadata: { source: './sales_slim.json', line: 77 }
  },
  Document {
    pageContent: 'Shalcras',
    metadata: { source: './sales_slim.json', line: 78 }
  },
  Document {
    pageContent: 'cshalcras5@baidu.com',
    metadata: { source: './sales_slim.json', line: 79 }
  },
  Document {
    pageContent: 'Cocoa Feuilletine',
    metadata: { source: './sales_slim.json', line: 80 }
  },
  Document {
    pageContent: 'Computers',
    metadata: { source: './sales_slim.json', line: 81 }
  },
  Document {
    pageContent: 'paid search',
    metadata: { source: './sales_slim.json', line: 82 }
  },
  Document {
    pageContent: '671 Thompson Terrace',
    metadata: { source: './sales_slim.json', line: 83 }
  },
  Document {
    pageContent: 'New York City',
    metadata: { source: './sales_slim.json', line: 84 }
  },
  Document {
    pageContent: 'New York',
    metadata: { source: './sales_slim.json', line: 85 }
  },
```

**Comment by kaykhan** [comment]
The CSVLoader works correctly, why does the JSONLoader not load all the fields and values into the PageContent?

```
const loader = new CSVLoader("./sales_slim.csv");
```
```
  Document {
    pageContent: 'date: 2022-07-03 03:36:48\n' +
      'first_name: Lin\n' +
      'last_name: De Ambrosi\n' +
      'email_address: ldeambrosij@hatena.ne.jp\n' +
      'Product: Squid - Breaded\n' +
      'category: Movies\n' +
      'source: video\n' +
      'street_address: 9150 Barby Drive\n' +
      'city: Crawfordsville\n' +
      'state: Indiana\n' +
      'postal_code: 47937\n' +
      'country: United States\n' +
      'returned: false\n' +
      'revenue: $172.29\n' +
      'cost: $6.52\n' +
      'Repeat Customer?: true\n' +
      'age: 55\n' +
      'number_of_sales: 43321',
    metadata: { source: './sales_slim.csv', line: 20 }
  }
```

**Comment by jacoblee93** [comment]
Sorry you're running into this - are you able to try the Unstructured loader for now?

https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/file_loaders/unstructured

**Comment by kaykhan** [comment]
> Sorry you're running into this - are you able to try the Unstructured loader for now?
> 
> https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/file_loaders/unstructured

Hey thanks for the suggestion unfortuantly i run into a different issue when using the UnstructuredLoader.

```
  const loader = new UnstructuredLoader("./sales_slim.json");
  const docs = await loader.load();

```

> > tsx retrieval.ts
> 
> (node:2878227) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> /home/kay/checkpoint/geeiq-ai/node_modules/langchain/dist/document_loaders/fs/unstructured.cjs:189
>             throw new Error(`Failed to partition file ${this.filePath} with error ${response.status} and message ${await response.text()}`);
>                   ^
> 
> 
> Error: Failed to partition file ./sales_slim.json with error 401 and message {"detail":"API key is missing, please provide an API key in the header."}
>     at UnstructuredLoader._partition (/home/kay/checkpoint/-ai/node_modules/langchain/dist/document_loaders/fs/unstructured.cjs:189:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at UnstructuredLoader.load (/home/kay/checkpoint/-ai/node_modules/langchain/dist/document_loaders/fs/unstructured.cjs:198:26)
>     at main (/home/kay/checkpoint/-ai/retrieval.ts:31:16)
> 
> Node.js v18.12.1

**Comment by AnthonyHad** [comment]
I am having the exact same issue. The unstructured loader is not working as well.

**Comment by AnthonyHad** [comment]
@kaykhan Were you able to solve this? I might just turn my JSON into a CSV..

**Comment by kaykhan** [comment]
@AnthonyHad No i was not able to solve this, there are also problems with the CSV Loader.

Ideally we want the JSONLoader to be fixed as the Document pageContent and its structure plays a big part in the outcome/result you will eventually get

**Comment by AnthonyHad** [comment]
@kaykhan Thanks for your feedback 🙏 . Will update here if I find a way but highly doubt this.

**Comment by indrabasak** [comment]
The JSONLoader issue raised by @kaykhan is still relevant.
