### ISSUE TITLE
Unable to insert vector embeddings to postgres using langchain and pgvector

### ISSUE THREAD

**Issue by Shbhom** [langchain-ai/langchainjs#3157]
### Issue Title:
Uploading Vector Embeddings to PostgreSQL Results in "Error inserting: invalid byte sequence for encoding 'UTF8': 0x00"

### Issue Description:
I have implemented an endpoint that allows users to upload text files, and then I create documents from those text files. These documents can be uploaded to either Pinecone or PostgreSQL databases. While the Pinecone upload works fine, I encounter an issue when trying to upload vector embeddings to PostgreSQL.

### Steps to Reproduce:
1. Create an endpoint that accepts text files using multer middleware.
2. Create document objects from the text files.
3. Attempt to upload these documents to a PostgreSQL database using the following configuration:

```ts
export async function uploader(req: Request, res: Response, next: NextFunction) {
    try {
        const { to } = req.query
        if (!to || typeof to !== "string") {
            throw new ErrorHandler("invalid queryParam or type eror", 400)
        }
        const txt = req.files
        if (!txt || !Array.isArray(txt)) {
        //allowed uploading multiple files so multer will return an array
            throw new ErrorHandler("no pdf file found", 400)
        }
        let loader
        let docs: Document[] = []
        for (let i = 0; i < txt.length; i++) {
            const element = txt[i];
            const data = await fs.readFile(path.resolve(element.path), { encoding: "utf-8" })
            const doc = new Document({ pageContent: data, metadata: { source: element.filename } })
            docs.push(doc)
        }
        console.log(docs)
        if (to === "pinecone") {
            const index = pine.Index(process.env.PINE_INDEX!)
            await PineconeStore.fromDocuments(docs, embeddings, { pineconeIndex: index, }).then(() => {
                console.log(`total docs uploaded : ${docs.length}`)
            })
            await clearDir("./uploads")
            return res.status(200).json({
                message: "docs uploaded succesfully"
            })

        } else if (to === "postgres") {
            const config = {
                postgresConnectionOptions: {
                    type: "postgres",
                    host: "127.0.0.1",
                    port: 5432,
                    user: "root",
                    password: "root",
                    database: "vectorstore",
                } as PoolConfig,
                tableName: "Docs",
                columns: {
                    idColumnName: "id",
                    vectorColumnName: "vector",
                    contentColumnName: "content",
                    metadataColumnName: "metadata",
                },
            };

            let pgVectorStore = await PGVectorStore.fromDocuments(docs, embeddings, config)
            return res.status(200).json({
                message: "successfully uploaded to Pgvector"
            })
        } else {
            throw new ErrorHandler("invalid query Param", 400)
        }
    } catch (err: any) {
        return next(err)
    } finally {
        clearDir(path.resolve("./uploads"))
    }
}
```

4. Use the following docker command to run the PostgreSQL database (replace 'use_any' with actual values):

```shell
docker run -d --rm -p 5432:5432 -v ./data:/var/lib/postgresql/data -e POSTGRES_USER= use_any -e POSTGRES_PASSWORD=use_any -e POSTGRES_DB=use_any --name vectorstore ankane/pgvector
```

### Expected Behavior:
I expect the vector embeddings to be uploaded to the PostgreSQL database without any issues.

### Actual Behavior:
When attempting to upload the vector embeddings to PostgreSQL, I consistently encounter the following error message:

```json
{
    "message": "Error inserting: invalid byte sequence for encoding 'UTF8': 0x00"
}
```

### Additional Information:
- I have reviewed the LangChain.js documentation [here](https://js.langchain.com/docs/integrations/vectorstores/pgvector) for integrating with PostgreSQL and followed the provided instructions.
- I have used the recommended Docker command to run the PostgreSQL database.
- The issue seems to be related to PostgreSQL's inability to store NULL ('\0x00') characters in text fields.

### Environment:
- Node.js version: 20.9.0
- PostgreSQL version:PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1)
- LangChain.js version:^0.0.166

### Reproducibility:
- [x] The issue is consistently reproducible.
- [ ] The issue occurs randomly.

### Proposed Solutions:
- Investigate the cause of the "invalid byte sequence for encoding 'UTF8': 0x00" error when inserting vector embeddings into PostgreSQL.
- Provide guidance or solutions to resolve this issue.

### Screenshot or Error Logs:
Error Logs:
```shell
error: invalid byte sequence for encoding "UTF8": 0x00
    at /home/shubhom/projects/js-ts/earningsPineconeEndpoint/node_modules/.pnpm/pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PGVectorStore.addVectors (/home/shubhom/projects/js-ts/earningsPineconeEndpoint/node_modules/.pnpm/langchain@0.0.166_@huggingface+inference@1.8.0_@pinecone-database+pinecone@1.1.1_pg@8.11.3/node_modules/langchain/dist/vectorstores/pgvector.cjs:172:17)
    at Function.fromDocuments (/home/shubhom/projects/js-ts/earningsPineconeEndpoint/node_modules/.pnpm/langchain@0.0.166_@huggingface+inference@1.8.0_@pinecone-database+pinecone@1.1.1_pg@8.11.3/node_modules/langchain/dist/vectorstores/pgvector.cjs:264:9) {
  length: 146,
  severity: 'ERROR',
  code: '22021',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'unnamed portal parameter $1',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'mbutils.c',
  line: '1665',
  routine: 'report_invalid_encoding'
}
```

**Comment by Shbhom** [comment]
Unable to use the solution @dosubot gave as I'm getting a type error vector doesn't exist on type Document<Record<string, any>>.
