### ISSUE TITLE
Illegal invocation with `langchain/llms/bedrock/web` on Cloudflare Worker

### ISSUE THREAD

**Issue by Manouchehri** [langchain-ai/langchainjs#3187]
```typescript
declare type Env = {
  ENVIRONMENT: "dev" | "production";
  BEDROCK_AWS_ACCESS_KEY_ID: string;
  BEDROCK_AWS_SECRET_ACCESS_KEY: string;
};

import { Bedrock } from "langchain/llms/bedrock/web";

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const model = new Bedrock({
      model: "anthropic.claude-v2",
      region: "us-east-1",
      credentials: {
        accessKeyId: env.BEDROCK_AWS_ACCESS_KEY_ID,
        secretAccessKey: env.BEDROCK_AWS_SECRET_ACCESS_KEY
      },
      streaming: false,
      verbose: true
    });
    console.log(model);
    const text = "Human: What would be a good company name for a company that makes colorful socks?";
  
    console.log(text);
    const llmResult = await model.invoke(text);
  
    console.log(llmResult);
    return new Response(llmResult);
  },
};
```

```
Bedrock {
  lc_serializable: true,
  lc_kwargs: Object,
  lc_runnable: true,
  verbose: true,
  callbacks: undefined
  ...
}
Human: What would be a good company name for a company that makes colorful socks?
[llm/start] [1:llm:Bedrock] Entering LLM run with input: {
  "prompts": [
    "Human: What would be a good company name for a company that makes colorful socks?"
  ]
}
[llm/error] [1:llm:Bedrock] [18ms] LLM run errored with error: "Illegal invocation"
[mf:err] TypeError: Illegal invocation
    at Object.apply (/private/var/folders/wd/0gfsfmwx4b91h52nfbbfrb5m0000gn/T/tmp-831-V0NWW140FaH9/checked-fetch.js:28:18)
    at null.<anonymous> (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/langchain/dist/llms/bedrock/web.js:204:105)
    at onFailedAttempt (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/langchain/dist/util/async_caller.js:89:50)
    at RetryOperation._fn (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/p-retry/index.js:50:18)
    at RetryOperation.attempt (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/retry/lib/retry_operation.js:116:8)
    at null.<anonymous> (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/p-retry/index.js:48:12)
    at [object Object]
    at pRetry (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/p-retry/index.js:39:36)
    at queue.add.throwOnTimeout (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/langchain/dist/util/async_caller.js:89:37)
    at run (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/p-queue/dist/index.js:157:104)
```

<img width="1405" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/7232674/218fd2c2-2f88-48cc-88a2-7b23cb31f121">

**Comment by Manouchehri** [comment]
I was following the docs at: https://js.langchain.com/docs/integrations/llms/bedrock

**Comment by Manouchehri** [comment]
It's this bit of code that seems to be causing the issue, not sure why.

https://github.com/langchain-ai/langchainjs/blob/0524fb6a0d0b4d99c494803e5cb254f312cd6ff9/langchain/src/llms/bedrock/web.ts#L210-L220

**Comment by Manouchehri** [comment]
@jacoblee93 Sorry for the random ping, thought you might have some experience with this. 😄

**Comment by jacoblee93** [comment]
I wonder if it's trying to use a secure context - will see if I can get to the bottom of it!

**Comment by jacoblee93** [comment]
But also CC @mhart

**Comment by Manouchehri** [comment]
So this makes zero sense to me... but defining my own fetch function removes the error. (It's super ugly though.)


```
declare type Env = {
  ENVIRONMENT: "dev" | "production";
  BEDROCK_AWS_ACCESS_KEY_ID: string;
  BEDROCK_AWS_SECRET_ACCESS_KEY: string;
};

import { Bedrock } from "langchain/llms/bedrock/web";

function myFetch(input: RequestInfo, init?: RequestInit<CfProperties<unknown>> | undefined): Promise<Response> {
  console.log("myFetch", input, init);
  return fetch(input, init);
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const model = new Bedrock({
      model: "anthropic.claude-v2",
      region: "us-east-1",
      credentials: {
        accessKeyId: env.BEDROCK_AWS_ACCESS_KEY_ID,
        secretAccessKey: env.BEDROCK_AWS_SECRET_ACCESS_KEY
      },
      streaming: false,
      verbose: true,
      fetchFn: myFetch
    });
    console.log(model);
    const text = "Human: What would be a good company name for a company that makes colorful socks?";
  
    console.log(text);
    const llmResult = await model.invoke(text);
  
    console.log(llmResult);
    return new Response(llmResult);
  },
};
```

**Comment by jacoblee93** [comment]
Could be the signed fetch package doing something funny?

**Comment by Manouchehri** [comment]
https://github.com/cloudflare/workers-sdk/issues/3478

Might be related to this. Still not sure how to fix it though.

**Comment by dqbd** [comment]
Thanks for flagging the issue! Binding `fetch` with `globalThis` should work fine for on `wrangler dev`.

**Comment by Manouchehri** [comment]
Mind showing an example? =) I thought I had already tried that and ended up with the same error.

**Comment by Manouchehri** [comment]
Yeah, this was my attempt that doesn't work (same error as before):

```typescript
const model_ant = new BedrockChat({
  model: "anthropic.claude-v2",
  region: "us-east-1",
  credentials: {
    accessKeyId: env.BEDROCK_AWS_ACCESS_KEY_ID,
    secretAccessKey: env.BEDROCK_AWS_SECRET_ACCESS_KEY
  },
  fetchFn: globalThis.fetch,
  maxTokens: 2048,
  verbose: true,
  maxRetries: 0,
  temperature: 0
});
```

**Comment by Manouchehri** [comment]
Thanks, I can confirm #3302 fixed it!

**Comment by jacoblee93** [comment]
Thanks again for the report!
