### ISSUE TITLE
TypeError: fetch failed while updating langchain from 0.0.131 to 0.0.181

### ISSUE THREAD

**Issue by sarfudheen** [langchain-ai/langchainjs#3261]
I have the following nodeje code which works fine with the langchain version 0.0.131 when I updated my langchain version to 0.0.181, I'm getting   	 
Error while responding to Query: What is the captial of USA: Details :**TypeError: fetch failed**
```
import { ConversationChain } from 'langchain/chains';
import { ChatOpenAI } from 'langchain/chat_models/openai';
import {
  ChatPromptTemplate,
  SystemMessagePromptTemplate,
  MessagesPlaceholder,
  HumanMessagePromptTemplate,
  PromptTemplate
} from 'langchain/prompts';
public async retrivalQAQuery(payload:any){
//const query ='What is the capital of USA?';
const llmModel= new ChatOpenAI({
  temperature: 0,
  azureOpenAIApiKey: XXXX,
  azureOpenAIApiInstanceName: XXXX,
  azureOpenAIApiVersion: XXXXX,
  azureOpenAIApiDeploymentName:XXX,
  streaming: true,
  verbose: false
});

const prompts = ChatPromptTemplate.fromPromptMessages([
  SystemMessagePromptTemplate.fromTemplate('Demo Prompt from User')
]);
prompts.promptMessages.push(
  new MessagesPlaceholder('chat_history'),
  HumanMessagePromptTemplate.fromTemplate(`{question}`)
);

const memory = MotorheadMemory // from local motorhead memory

const chain = new ConversationChain({
  memory: memory,
  prompt: prompt,
  llm: llmModel
});
let response ='';
try{

const resp = await chain.call(
   {
      question: payload.query,
      chat_history: memory,
      signal: payload.abortController.signal
    },
    [
      {
        handleLLMNewToken(token: string, idx, runId, parentRunId) {
          response += token;
        }
      }
    ]
  );

}catch(error:any){	   console.error(`Error while responding to Query: ${payload.query}: Details :${error}`); 
}
console.log(response);
}  
```

**Comment by jacoblee93** [comment]
Can you tell me a bit about your local environment? Are you using Node 16 by any chance?

**Comment by sarfudheen** [comment]
Hello Jacoblee93, 
My node version 18.x. Same code works fine in langchain 0.0.131.

**Comment by jacoblee93** [comment]
Ah ok, any additional stack trace?

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by sarfudheen** [comment]
My stack trace 
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at async RetryOperation._fn (D:\user\ai\node_modules\p-retry\index.js:50:12) {cause: Error: read ECONNRESET
    at TCP.onStreamRead…nternal/stream_base_commons:217:20)
    at TC…, stack: 'TypeError: fetch failed
    at Object.fetch (…\ai\node_modules\p-retry\index.js:50:12)', message: 'fetch failed'}
```

**Comment by sarfudheen** [comment]
We did not have this issue after migrating our application vers langchain v0.0.203. So I'm closing this issue
