### ISSUE TITLE
Conversion issue in `createOpenAPIChain`?

### ISSUE THREAD

**Issue by Manouchehri** [langchain-ai/langchainjs#3266]
Looks like there's an unexpected `.` in the API function name somehow, can't trace down where the `.` -> `_` replacement is supposed to be happening in langchainjs.

```
[llm/error] [1:llm:ChatOpenAI] [2.18s] LLM run errored with error: "400 '_api_v1_0.0/weather_get' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'"
A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #3)
[mf:err] Error: 400 '_api_v1_0.0/weather_get' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'
    at APIError.generate (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/openai/src/error.ts:66:14)
    at OpenAI.makeStatusError (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/openai/src/core.ts:358:21)
    at OpenAI.makeRequest (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/openai/src/core.ts:416:24)
    at null.<anonymous> (async index.js:18794:25)
    at async RetryOperation._fn (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/p-retry/index.js:50:12)
```

Code to reproduce:

```typescript
const chain = await createOpenAPIChain("https://caymanweather.aimoda.dev/openapi.json", {
  llm: model
});

const result = await chainapi.run(`What's the current weather in Cayman?`);
```

**Comment by Manouchehri** [comment]
@dosubot The OpenAPI spec is:

```json
{"openapi":"3.0.0","info":{"version":"1.0.0","title":"Cayman Weather API (unofficial)"},"tags":[{"name":"language","description":"en"}],"components":{"schemas":{},"parameters":{}},"paths":{"/api/v1.0.0/weather":{"get":{"operationid":"get_weather","responses":{"200":{"description":"Fetch weather data from the Cayman Weather site.","content":{"application/json":{"schema":{"type":"object","properties":{}}}}},"404":{"description":"Unable to fetch the weather data","content":{"application/json":{"schema":{"type":"object","properties":{"message":{"type":"string"}}}}}},"500":{"description":"Unexpected internal server error.","content":{"application/json":{"schema":{"type":"object","properties":{"status_code":{"type":"number","description":"Original error code.","example":504},"message":{"type":"string"}}}}}}}}}}}
```

You can also download it from https://caymanweather.aimoda.dev/openapi.json
