### ISSUE TITLE
Punycode deprecated message

### ISSUE THREAD

**Issue by nickworks** [langchain-ai/langchainjs#3284]
I keep getting a **"[DEP0040] Deprecation Warning: The `punycode` module is deprecated."** Is there a way I can fix this?

File:
```
// demo.js
import { LLMChain } from "langchain/chains";
```

CLI:
```
node --trace-deprecation demo.js
```

Error:
```
(node:4804) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/nick/projects/ai/langchain-cookbook/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

**Comment by nickworks** [comment]
I'm using Node v21.1.0 (according to node -v)
I'm using Langchain 0.0.186 (according to package-lock.json)

In package.json, I have the following dependencies:
```
"dependencies": {
    "@tensorflow-models/universal-sentence-encoder": "^1.3.3",
    "@tensorflow/tfjs-converter": "^3.6.0",
    "@tensorflow/tfjs-core": "^3.6.0",
    "@tensorflow/tfjs-node": "^4.10.0",
    "cheerio": "^1.0.0-rc.12",
    "langchain": "^0.0.186"
  }
```

**Comment by bakertn** [comment]
I am getting the same issue.  Vanilla getting started code from your lanchain getting started docs.  No direct mention of punycode.  
node v21.7.0
Just installed langchain js TODAY.  Latest version.  Also ran npm update.  Completely up to date. 

(base) PS C:\Users\lbake\VSCode Projects\langchainjs> node --trace-deprecation app.js
(node:4792) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:104:7)
    at Module._load (node:internal/modules/cjs/loader:999:17)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\lbake\VSCode Projects\langchainjs\node_modules\whatwg-url\lib\url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
Why did the ice cream cone go to therapy? Because it had too many toppings!

Then ran this to check the whatwg-url

(base) PS C:\Users\lbake\VSCode Projects\langchainjs> npm list whatwg-url
your-package-name@1.0.0 C:\Users\lbake\VSCode Projects\LangChainJS
└─┬ @langchain/openai@0.0.18
  └─┬ openai@4.28.4
    └─┬ node-fetch@2.7.0
      └── whatwg-url@5.0.0
      
      
      This is the getting started code I am executing
      
 import { ChatOpenAI } from "@langchain/openai";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";

const prompt = ChatPromptTemplate.fromMessages([
  ["human", "Tell me a short joke about {topic}"],
]);
const model = new ChatOpenAI({});
const outputParser = new StringOutputParser();

const chain = prompt.pipe(model).pipe(outputParser);

const response = await chain.invoke({
  topic: "ice cream",
});
console.log(response);
/**
Why did the ice cream go to the gym?
Because it wanted to get a little "cone"ditioning!
 */
      
      
      
      
    So I echo the previous post.  Why is there a deprecated library in this project.  Please fix ASAP.  Extremely annoying.  
    
    New install of everything, NODE, LangChain, today.   All new.  So this is a "current" issue.

**Comment by jason-allen-oneal** [comment]
Same here. Fresh install of langchain on node 22.6.

(node:1821801) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:98:7)
    at Module._load (node:internal/modules/cjs/loader:1099:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:125:16)
    at Object.<anonymous> (/var/www/test/node_modules/whatwg-url/lib/url-state-machine.js:2:18)

**Comment by ladrians** [comment]
same issue here using `v22.0.9` version, so far added `--no-deprecation` not to show it.
