### ISSUE TITLE
Unable to Use intfloat/multilingual-e5-large with HuggingFace Transformers

### ISSUE THREAD

**Issue by ishikawa-atsuki-valuesccg** [langchain-ai/langchainjs#3334]
I am reaching out for assistance with an issue I'm experiencing while trying to use the intfloat/multilingual-e5-large model in a TypeScript project in my local environment. I am utilizing LangChain.js and HuggingFace Transformers, and I hope you can provide some guidance or a solution.

Environment:

Node.js version: 20.9.0
npm version: 10.1.0
LangChain version: 0.0.192
@xenova/transformers version: 2.8.0

Code:
I am using the following code snippet:

```javascript
import { HuggingFaceTransformersEmbeddings } from 'langchain/embeddings/hf_transformers';

const model = new HuggingFaceTransformersEmbeddings({
    modelName: 'intfloat/multilingual-e5-large',
});

// Embed queries
const res = await model.embedQuery(
    'What would be a good company name for a company that makes colorful socks?'
);
console.log(res);
```

Error:
However, I am receiving this error:

```javascript
file:///home/my_user/my_project/node_modules/@xenova/transformers/src/utils/hub.js:240
    throw Error(`${message}: "${remoteURL}".`);
          ^

Error: Could not locate file: "https://huggingface.co/intfloat/multilingual-e5-large/resolve/main/onnx/model_quantized.onnx".
    at handleError (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/utils/hub.js:240:11)
    at getModelFile (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/utils/hub.js:473:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async constructSession (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/models.js:119:18)
    at async Promise.all (index 1)
    at async BertModel.from_pretrained (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/models.js:760:20)
    at async AutoModel.from_pretrained (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/models.js:3960:20)
    at async Promise.all (index 1)
    at async loadItems (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/pipelines.js:2368:5)
    at async pipeline (file:///home/atsuki/verfication-langchain/node_modules/@xenova/transformers/src/pipelines.js:2314:19)

Node.js v20.9.0
```

It seems that there might be an issue related to Transformers.js, so it might be more appropriate to reach out to the Hugging Face team. However, if you have any advice on how to use the model locally, or any other suggestions, I would be very grateful for your guidance.

**Comment by ishikawa-atsuki-valuesccg** [comment]
@zdarova 
I'm sorry, but I ended up not trying to use intfloat/multilingual-e5-large with JavaScript, so I couldn't get it to work at that time. I'm not sure if it has become workable since then.

**Comment by qsdhj** [comment]
I tried this:
```python
model_name = "intfloat/multilingual-e5-large-instruct"

model_kwargs = {'device': 'cuda',
                   }
query_instruction = "Given a web search query, retrieve relevant passages that answer the query:"
encode_kwargs = {'normalize_embeddings': True}

hf = HuggingFaceInstructEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
    # query_instruction=query_instruction
```
And get this error
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx/.cache\\torch\\sentence_transformers\\intfloat_multilingual-e5-large-instruct\\sentence_xlnet_config.json'
```

**Comment by juerware** [comment]
> I tried this:
> 
> ```python
> model_name = "intfloat/multilingual-e5-large-instruct"
> 
> model_kwargs = {'device': 'cuda',
>                    }
> query_instruction = "Given a web search query, retrieve relevant passages that answer the query:"
> encode_kwargs = {'normalize_embeddings': True}
> 
> hf = HuggingFaceInstructEmbeddings(
>     model_name=model_name,
>     model_kwargs=model_kwargs,
>     encode_kwargs=encode_kwargs,
>     # query_instruction=query_instruction
> ```
> 
> And get this error
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx/.cache\\torch\\sentence_transformers\\intfloat_multilingual-e5-large-instruct\\sentence_xlnet_config.json'
> ```

I have the same problem right now

**Comment by lucasalvarezlacasa** [comment]
I have the same problem. Are there any updates on this?
