### ISSUE TITLE
Input values have 1 keys, you must specify an input key or pass only 1 key as input

### ISSUE THREAD

**Issue by andreasjoensson** [langchain-ai/langchainjs#3403]
Hey when using the OpenAIAgentTokenBufferMemory i receive the following error: `Error occurred: Error: input values have 1 keys, you must specify an input key or pass only 1 key as input.

This is a bit weird because i was following the tutorial from the langchain documentation: https://js.langchain.com/docs/use_cases/question_answering/conversational_retrieval_agents#creating-from-components, and my code is pretty much identical to the tutorial.

Any help would  be appreciated, i use AzureOpenAI if that makes a difference?

    at getInputValue (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain-core\dist\schema\memory.cjs:31:15)
    at OpenAIAgentTokenBufferMemory.saveContext (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\agents\toolkits\conversational_retrieval\token_buffer_memory.cjs:105:56)
    at AgentExecutor.call (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\chains\base.cjs:120:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error processing chat: Error: input values have 1 keys, you must specify an input key or pass only 1 key as input
    at getInputValue (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain-core\dist\schema\memory.cjs:31:15)
    at OpenAIAgentTokenBufferMemory.saveContext (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\agents\toolkits\conversational_retrieval\token_buffer_memory.cjs:105:56)`

This is my code: 
`import { initializeAgentExecutorWithOptions } from 'langchain/agents'
import { Chroma } from 'langchain/vectorstores/chroma'
import { OpenAIEmbeddings } from 'langchain/embeddings/openai'
import { createRetrieverTool } from 'langchain/agents/toolkits'
import { ChatOpenAI } from 'langchain/chat_models/openai'
import { OpenAIAgentTokenBufferMemory } from 'langchain/agents/toolkits'
import { HumanMessage, AIMessage } from 'langchain/schema'
import { ChatMessageHistory } from 'langchain/memory'
import { Request, Response } from 'express'
import { shippingTool } from './templates/Shipping'

export const runChatbot = async (
  input: string,
  chatbotID: string,
  company: string,
  previousMessages: (HumanMessage | AIMessage)[],
  res: Response,
  req: Request
) => {
  try {
    const vectorStore = await Chroma.fromExistingCollection(
      new OpenAIEmbeddings({
        azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
        azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
        azureOpenAIApiDeploymentName:
          process.env.AZURE_OPENAI_API_DEPLOYMENT_EMBEDDING_NAME,
        azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME
      }),
      {
        collectionName: chatbotID,
        url: 'chromadb url'
      }
    )

    const retriever = vectorStore.asRetriever()

    const model = new ChatOpenAI({
      temperature: 0,
      azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
      azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
      azureOpenAIApiDeploymentName:
        process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME,
      azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME,
      streaming: true
    })

    const tool = createRetrieverTool(retriever, {
      name: `search_${company}_state`,
      description: `Søger efter virksomheds informationer eller dokumenter vedrørende ${company}`
    })

    const chatHistory = new ChatMessageHistory(previousMessages)

    const memory = new OpenAIAgentTokenBufferMemory({
      llm: model,
      memoryKey: 'chat_history',
      outputKey: 'output',
      chatHistory
    })

    const tools = [tool, shippingTool]

    const executor = await initializeAgentExecutorWithOptions(tools, model, {
      agentType: 'openai-functions',
      memory,
      returnIntermediateSteps: true,
      agentArgs: {
        prefix:
          'Du er en AI-Assistent for webshoppen Spacebox der sælger lys til gamere. Brug din viden om Spacebox og dets sortiment til at hjælpe kunderne. Du kan også bruge værktøjer til at finde nøjagtige oplysninger, hvis du er usikker. Hvis du ikke har svaret, bedes du undlade at give et svar på spørgsmålet.'
      }
    })

    await executor.call(
      {
        input
      },
      {
        callbacks: [
          {
            handleLLMNewToken(token: string) {
              res.write(token)
            }
          }
        ]
      }
    )

    res.end()
  } catch (error) {
    console.error('Error occurred:', error)
    // Handle the error as needed: log, throw, or respond gracefully.
    // Example: throw the error to propagate it to the caller
    throw error
  }
}`

**Comment by andreasjoensson** [comment]
I just tried this, but it did not make a difference i still receive the same error.

**Comment by andreasjoensson** [comment]
This is the exact error that i receive:  ```
Error: input values have 1 keys, you must specify an input key or pass only 1 key as input
    at getInputValue (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain-core\dist\schema\memory.cjs:31:15)
    at OpenAIAgentTokenBufferMemory.saveContext (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\agents\toolkits\conversational_retrieval\token_buffer_memory.cjs:105:56)
    at AgentExecutor.call (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\chains\base.cjs:120:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error processing chat: Error: input values have 1 keys, you must specify an input key or pass only 1 key as input
    at getInputValue (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain-core\dist\schema\memory.cjs:31:15)
    at OpenAIAgentTokenBufferMemory.saveContext (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\agents\toolkits\conversational_retrieval\token_buffer_memory.cjs:105:56)
    at AgentExecutor.call (C:\Users\andre\Desktop\chatbotai-new\backend\api\node_modules\langchain\dist\chains\base.cjs:120:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  level: 'error',
  timestamp: '2023-11-24 21:58:48',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '{"level":"error","timestamp":"2023-11-24 21:58:48"}'
}
```

**Comment by ghost** [comment]
Olá, esse erro geralmente ocorre quando você tem dois dados chegando no seu node ou um valor vazio. Para resolver adicione um node Merge ou trate o dado vazio ( {{ $json.example || ‘ ND ‘ }} ).
