### ISSUE TITLE
Inserting vectors in Xata results in Bulk operation failed error

### ISSUE THREAD

**Issue by codenameakshay** [langchain-ai/langchainjs#3417]
I am using `"langchain": "^0.0.150"`, and `"@xata.io/client": "^0.27.0"`. So when I import the xata client and create a vector store from it
```javascript
    // Fetch vector store
    this.vectorStore = new XataVectorSearch(new OpenAIEmbeddings(), {
      client: this.client(),
      table: 'articles',
    });
```
and I try to call `addVectors` or `addDocs` method like this ->
```javascript
vectorStore.addVectors(embeddings, docs);
// vectorStore.addDocs(docs);
```
I get this error ->
```
Error: Bulk operation failed
    at /home/codenameakshay/Developer/kalam-ai/node_modules/@xata.io/client/src/api/fetcher.ts:222:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultTrace (/home/codenameakshay/Developer/kalam-ai/node_modules/@xata.io/client/src/schema/tracing.ts:17:10)
    at fetch$1 (/home/codenameakshay/Developer/kalam-ai/node_modules/@xata.io/client/src/api/fetcher.ts:149:10)
    at RestRepository.insertRecords_fn (/home/codenameakshay/Developer/kalam-ai/node_modules/@xata.io/client/src/schema/repository.ts:998:27)
    at /home/codenameakshay/Developer/kalam-ai/node_modules/@xata.io/client/src/schema/repository.ts:1544:21
    at defaultTrace (/home/codenameakshay/Developer/kalam-ai/node_modules/@xata.io/client/src/schema/tracing.ts:17:10)
    at XataVectorSearch.addVectors (/home/codenameakshay/Developer/kalam-ai/node_modules/langchain/dist/vectorstores/xata.cjs:66:21)
```

It says the error is in this line 66 in `xata.cjs` but I am not able to debug what went wrong.
![image](https://github.com/langchain-ai/langchainjs/assets/60510869/60db2605-51bf-4271-a35a-68c1d03f95ae)

Even if I try to add a single doc it fails with the same error.
I have tried to add docs through Postman calling Xata APIs and it works. Not sure why it is failing here though.

**Comment by codenameakshay** [comment]
Okay I was able to find out the problem, one of my column on xata had type mismatch. But it should've thrown that error, instead I had to manually one by one check which column has issue, as it just says `Bulk operation failed`.
