### ISSUE TITLE
`similaritySearchVectorWithScore` method on XataVectorSearch gives `TypeError: records.map is not a function`

### ISSUE THREAD

**Issue by codenameakshay** [langchain-ai/langchainjs#3418]
I am using `"langchain": "^0.0.150"`, and `"@xata.io/client": "^0.27.0"`. So when I import the xata client and create a vector store from it
```javascript
    // Fetch vector store
    this.vectorStore = new XataVectorSearch(new OpenAIEmbeddings(), {
      client: this.client(),
      table: 'articles',
    });
```
and I try to call `similaritySearchVectorWithScore` method like this ->
```javascript
const docs = await vectorStore.similaritySearchVectorWithScore(
          queryEmbeddings, // embeddings of the query
          10,
        );
```
I get this error ->
```
TypeError: records.map is not a function
    at XataVectorSearch.similaritySearchVectorWithScore (/home/codenameakshay/Developer/kalam-ai/node_modules/langchain/dist/vectorstores/xata.cjs:97:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/codenameakshay/Developer/kalam-ai/src/llm/agents/handleInternetSearch.ts:102:22
```
It says the error is in this line 97 in `xata.cjs`. I think the records are coming empty/null, and then the map function is not callable on that.
![image](https://github.com/langchain-ai/langchainjs/assets/60510869/0294f4e1-2d37-42b9-a6ef-f87f65cca279)

**Comment by codenameakshay** [comment]
The documents are being added correctly, and the fix was done for memory vector store and not xata. Please check.

**Comment by codenameakshay** [comment]
@jacoblee93 Please take a look at this, and also the PR I opened.
