### ISSUE TITLE
TypeError: this.pineconeIndex.namespace is not a function

### ISSUE THREAD

**Issue by RedouanAssakali** [langchain-ai/langchainjs#3434]
TypeError: this.pineconeIndex.namespace is not a function
 at PineconeStore._runPineconeQuery (/Users/redouanassakali/Desktop/school/specialization_se/unity/backend/node_modules/langchain/dist/vectorstores/pinecone.cjs:178:46)
    at PineconeStore.similaritySearchVectorWithScore (/Users/redouanassakali/Desktop/school/specialization_se/unity/backend/node_modules/langchain/dist/vectorstores/pinecone.cjs:197:36)
    at PineconeStore.similaritySearch (/Users/redouanassakali/Desktop/school/specialization_se/unity/backend/node_modules/langchain/dist/vectorstores/base.cjs:107:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async VectorStoreRetriever.getRelevantDocuments (/Users/redouanassakali/Desktop/school/specialization_se/unity/backend/node_modules/@langchain/core/dist/retrievers.cjs:69:29)
    at async ConversationalRetrievalQAChain._call (/Users/redouanassakali/Desktop/school/specialization_se/unity/backend/node_modules/langchain/dist/chains/conversational_retrieval_chain.cjs:169:22)
    at async ConversationalRetrievalQAChain.call (/Users/redouanassakali/Desktop/school/specialization_se/unity/backend/node_modules/langchain/dist/chains/base.cjs:120:28)
    at async /Users/redouanassakali/Desktop/school/specialization_se/unity/backend/src/api/chat.js:57:26

my versions:
    "@pinecone-database/pinecone": "1.1.0",   
  "langchain": "0.0.198",

**Comment by RedouanAssakali** [comment]
the problem now is: pinecone.init({
            apiKey: process.env.PINECONE_API_KEY,
            environment: process.env.PINECONE_ENVIRONMENT,
        });

error: Unresolved function or method init()

**Comment by silakironji** [comment]
Your index already exists. nice !!
Preparing chunks from PDF file
Loading 3 chunks into pinecone...
error  TypeError: this.pineconeIndex.namespace is not a function
    at PineconeStore.addVectors (C:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\node_modules\@langchain\community\dist\vectorstores\pinecone.cjs:141:46)
    at PineconeStore.addDocuments (C:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\node_modules\@langchain\community\dist\vectorstores\pinecone.cjs:95:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PineconeStore.fromDocuments (C:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\node_modules\@langchain\community\dist\vectorstores\pinecone.cjs:280:9)
    at embedAndStoreDocs (c:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\lib\vector-store.ts:21:9)
    at <anonymous> (c:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\scripts\pinecone-prepare-docs.ts:14:5)
Init client script failed  Error: Failed to load your docs !
    at embedAndStoreDocs (c:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\lib\vector-store.ts:27:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\sila\Desktop\Sqweya\intelli-chatbot\my-app\scripts\pinecone-prepare-docs.ts:14:5)
