### ISSUE TITLE
Bug: @langchain/mistralai - Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by gkhngyk** [langchain-ai/langchainjs#3662]
When I try to import ChatMistralAI I get the following error:

```
/Users/Desktop/xamax/server/node_modules/@langchain/mistralai/dist/chat_models.cjs:8
const mistralai_1 = __importDefault(require("@mistralai/mistralai"));
                                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Desktop/xamax/server/node_modules/@mistralai/mistralai/src/client.js from /Users/Desktop/xamax/server/node_modules/@langchain/mistralai/dist/chat_models.cjs not supported.
Instead change the require of client.js in /Users/Desktop/xamax/server/node_modules/@langchain/mistralai/dist/chat_models.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/Desktop/xamax/server/node_modules/@langchain/mistralai/dist/chat_models.cjs:8:37)
    at Object.<anonymous> (/Users/Desktop/xamax/server/node_modules/@langchain/mistralai/dist/index.cjs:17:14)
    at Object.<anonymous> (/Users/Desktop/xamax/server/node_modules/@langchain/mistralai/index.cjs:1:18)
    at Object.<anonymous> (/Users/Desktop/xamax/server/src/flows/index.js:22:27)
    at Object.<anonymous> (/Users/Desktop/xamax/server/src/server.js:75:5) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v19.9.0
```

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by bracesproul** [comment]
hey @gkhngyk the issue should be resolved if you bump your `@langchain/mistralai` package to `0.0.2`

**Comment by gkhngyk** [comment]
> hey @gkhngyk the issue should be resolved if you bump your `@langchain/mistralai` package to `0.0.2`

Thank you the problem seems to be solved.

**Comment by davidfant** [comment]
@bracesproul I'm running into this with @langchain/mistralai 0.0.8:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/fant/repos/ai/godmode/packages/node_modules/@mistralai/mistralai/src/client.js from /Users/fant/repos/ai/godmode/packages/node_modules/@langchain/mistralai/dist/chat_models.cjs not supported.
Instead change the require of client.js in /Users/fant/repos/ai/godmode/packages/node_modules/@langchain/mistralai/dist/chat_models.cjs to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/fant/repos/ai/godmode/packages/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/fant/repos/ai/godmode/packages/node_modules/@langchain/mistralai/dist/chat_models.cjs:7:37)
    at require.extensions.<computed> [as .js] (/Users/fant/repos/ai/godmode/packages/node_modules/ts-node/dist/index.js:851:20) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by bracesproul** [comment]
> @bracesproul I'm running into this with @langchain/mistralai 0.0.8:
> 
> ```
> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/fant/repos/ai/godmode/packages/node_modules/@mistralai/mistralai/src/client.js from /Users/fant/repos/ai/godmode/packages/node_modules/@langchain/mistralai/dist/chat_models.cjs not supported.
> Instead change the require of client.js in /Users/fant/repos/ai/godmode/packages/node_modules/@langchain/mistralai/dist/chat_models.cjs to a dynamic import() which is available in all CommonJS modules.
>     at require.extensions.<computed> [as .js] (/Users/fant/repos/ai/godmode/packages/node_modules/ts-node/dist/index.js:851:20)
>     at Object.<anonymous> (/Users/fant/repos/ai/godmode/packages/node_modules/@langchain/mistralai/dist/chat_models.cjs:7:37)
>     at require.extensions.<computed> [as .js] (/Users/fant/repos/ai/godmode/packages/node_modules/ts-node/dist/index.js:851:20) {
>   code: 'ERR_REQUIRE_ESM'
> }
> ```

whoops sorry about that, I thought they fixed that with their new sdk update...
Fix is here, will be released in a few min:
https://github.com/langchain-ai/langchainjs/pull/4561

**Comment by sneko** [comment]
@bracesproul when trying to use it I face this error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utils/function_calling' is not defined by "exports" in /.../node_modules/@langchain/core/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at a._resolveFilename (/.../node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/.../node_modules/@langchain/mistralai/dist/chat_models.cjs:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/.../node_modules/@langchain/mistralai/dist/index.cjs:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/.../node_modules/@langchain/mistralai/index.cjs:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at fullAnswer (/.../src/features/llm-langchain.ts:6:52)
    at Object.<anonymous> (/.../src/features/llm-langchain.ts:751:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at <anonymous> (/.../src/features/llm.ts:4:57)
    at Object.<anonymous> (/.../src/features/llm.ts:75:23)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at <anonymous> (/.../src/server/system.ts:3:36)
    at Object.<anonymous> (/.../src/server/system.ts:18:23)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at https (/.../src/features/domain.ts:26:41)
    at Object.<anonymous> (/.../src/features/domain.ts:1120:23)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at <anonymous> (/.../src/cli/program.ts:11:8)
    at Object.<anonymous> (/.../src/cli/program.ts:235:4)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at <anonymous> (/.../src/cli/index.ts:1:25)
    at Object.<anonymous> (/.../src/cli/index.ts:7:2)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/.../node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Anyone else?

**Comment by bracesproul** [comment]
> at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)

Have you installed core according to [this page](https://js.langchain.com/docs/get_started/installation#installing-integration-packages) and are on the latest version (0.1.40)?
