### ISSUE TITLE
Vector store not initialised yet but I have called `fromDocuments`

### ISSUE THREAD

**Issue by PierrickI3** [langchain-ai/langchainjs#3840]
When I run this code:

```javascript
    const { BedrockRuntimeClient, InvokeModelCommand } = require('@aws-sdk/client-bedrock-runtime');
    const { BedrockEmbeddings } = require('langchain/embeddings/bedrock');
    const { FaissStore } = require('langchain/vectorstores/faiss');
    
    const loader = new PDFLoader(`/tmp/${key}`, {
      splitPages: false,
    });

    const docs = await loader.load();

    // Create bedrock runtime client
    const client = new BedrockRuntimeClient({
      region,
    });

    // Load embeddings model
    const embeddings = new BedrockEmbeddings({
      model: 'amazon.titan-embed-text-v1',
      client,
      region,
    });

    const vectorStore = await FaissStore.fromDocuments(docs, embeddings);

    //FIXME: Fails with "Error: Vector store not initialised yet. Try calling `fromTexts`, `fromDocuments` or `fromIndex` first."
    await vectorStore.save('/tmp/index.faiss');
```

I get this error:
```
Error: Vector store not initialised yet. Try calling `fromTexts`, `fromDocuments` or `fromIndex` first.
    at get index [as index] (/Users/pierrick.lozach/Documents/GreenTeacket/backend/lambdas/securityqa/node_modules/langchain/node_modules/@langchain/community/dist/vectorstores/faiss.cjs:89:19)
    at FaissStore.save (/Users/pierrick.lozach/Documents/GreenTeacket/backend/lambdas/securityqa/node_modules/langchain/node_modules/@langchain/community/dist/vectorstores/faiss.cjs:164:18)
    at async module.exports.generateEmbeddings (/Users/pierrick.lozach/Documents/GreenTeacket/backend/lambdas/securityqa/ai/handler.js:85:5)
    at async MessagePort.<anonymous> (file:///Users/pierrick.lozach/Documents/GreenTeacket/backend/lambdas/securityqa/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
```

Could you help? I have searched and tried several things but can't fix it.

**Comment by PierrickI3** [comment]
The automated response is not correct. I am indeed using `await` already?

**Comment by PierrickI3** [comment]
I think I may have found the issue. `loader.load()` returns an empty array however the PDF file is valid. Investigating...

**Comment by PierrickI3** [comment]
So I have identified the issue with PDFLoader. It works for 1 PDF document but not for the other 2 that I have.
It does not seem to be a size issue as the one that works is 10 MB while the other 2 are 300 KB and 52 MB.

Any help would be appreciated.

**Comment by PierrickI3** [comment]
I found the issue. 2 of the PDFs were actually graphics as text and that's why it returned no text at all. Closing.

**Comment by sidharthsid7** [comment]
// Import the required modules from langchain
const { TextLoader } = require("langchain/document_loaders/fs/text");
const { CharacterTextSplitter } = require("langchain/text_splitter");
const {OpenAIEmbeddings} = require("langchain/embeddings/openai")
const { FaissStore } = require("langchain/vectorstores/faiss");

// Wrap your code in an async function and export it
async function processDocuments() {
  try {

    
    const loader = new TextLoader("./info.txt");
    const docs = await loader.load();

    const splitter = new CharacterTextSplitter({
      chunkSize: 100,
      chunkOverlap: 50,
    });

    const documents = await splitter.splitDocuments(docs);
  

    const embeddings = new OpenAIEmbeddings();
    console.log(embeddings,'vector',documents);
    const vectorstore = await FaissStore.fromDocuments(documents, embeddings);
   
    await vectorstore.save("./");
  } catch (error) {
    console.error("Error processing documents:", error);
  }
}

module.exports = { processDocuments };


Error processing documents: Error: Request failed with status code 429
for vector db , do we need to use paid apikeys?
