### ISSUE TITLE
Error while inserting data into chromaDB

### ISSUE THREAD

**Issue by tripurarisingh1** [langchain-ai/langchainjs#3853]
max_seq_length  512
Traceback (most recent call last):
  File "/home/ec2-user/windPower/InsertLatestArticles.py", line 222, in <module>
    db = Chroma.from_texts(texts=C_documents,metadatas=C_metadatas, embedding=embeddings, persist_directory="db")
  File "/home/ec2-user/anaconda3/envs/textgent/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 577, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/home/ec2-user/anaconda3/envs/textgent/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 187, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "/home/ec2-user/anaconda3/envs/textgent/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 170, in embed_documents
    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
  File "/home/ec2-user/anaconda3/envs/textgent/lib/python3.10/site-packages/InstructorEmbedding/instructor.py", line 535, in encode
    features = self.tokenize(sentences_batch)
  File "/home/ec2-user/anaconda3/envs/textgent/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 319, in tokenize
    return self._first_module().tokenize(texts)
  File "/home/ec2-user/anaconda3/envs/textgent/lib/python3.10/site-packages/InstructorEmbedding/instructor.py", line 334, in tokenize
    assert isinstance(texts[0][1],str)
AssertionError

**Comment by tripurarisingh1** [comment]
Thank you I am waiting for your reply.

**Comment by tripurarisingh1** [comment]
Thank you so much for your reply on this.

I already fixed the issue. Issue was when we are passing C_Document value that was is incorrect format. now it's resolve now.
