### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module \node_modules\srt-parser-2\dist\index.js from langchain\dist\document_loaders\fs\srt.cjs not supported

### ISSUE THREAD

**Issue by ladrians** [langchain-ai/langchainjs#4059]
I am trying to update to version 0.1 from 0.0.214. I am receiving the following error

```
C:\temp\packages\functions\node_modules\ts-node\dist\index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\temp\packages\functions\node_modules\srt-parser-2\dist\index.js from C:\temp\packages\functions\node_modules\langchain\dist\document_loaders\fs\srt.cjs not supported.
Instead change the require of index.js in C:\temp\packages\functions\node_modules\langchain\dist\document_loaders\fs\srt.cjs to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:851:20)      
    at Object.<anonymous> (C:\temp\packages\functions\node_modules\langchain\dist\document_loaders\fs\srt.cjs:7:40)       
    at require.extensions.<computed> [as .js] (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:851:20)      
    at Object.<anonymous> (C:\temp\packages\functions\node_modules\langchain\document_loaders\fs\srt.cjs:1:18)
    at require.extensions.<computed> [as .js] (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:851:20)      
    at Object.<anonymous> (C:\temp\packages\functions\src\ingest-document.ts:24:15)
    at m._compile (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .ts] (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:859:16)      
    at Object.<anonymous> (C:\temp\packages\functions\src\controllers\upsert-doc.ts:38:27)
    at m._compile (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .ts] (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:859:16)      
    at Object.<anonymous> (C:\temp\packages\functions\src\server.ts:9:22)
    at m._compile (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .ts] (C:\temp\packages\functions\node_modules\ts-node\dist\index.js:859:16) {    
  code: 'ERR_REQUIRE_ESM'
```

from this code, noticed the `srt-parser-2` dependency was updated.

```
import { SRTLoader } from "langchain/document_loaders/fs/srt";
...
documentLoader = new  SRTLoader(filePath);
...
```

thanks,

**Comment by jacoblee93** [comment]
Does this persist if you upgrade your peer dependency to the latest version?

I think this is related to folks running into #1554. Unfortunate that there was a breaking change in a patch in that package.

Please reopen if that doesn't fix it.

**Comment by ladrians** [comment]
@jacoblee93 if possible can you reopen it? I do not have the option.
