### ISSUE TITLE
Cannot use `@langchain/community` due to broken `package.json`

### ISSUE THREAD

**Issue by jsumners-nr** [langchain-ai/langchainjs#4084]
<details>
<summary>.npmrc</summary>

```
package-lock=false
install-strategy=nested
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "@langchain/community": "^0.0.18"
  }
}
```

</details>

<details>
<summary>index.js</summary>

```js
'use strict'

const lcc = require('@langchain/community')
console.dir(lcc)
```

</details>

Using the above reproduction, running `node index.js` results in:

```
❯ node index.js
node:internal/modules/cjs/loader:598
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /private/tmp/19/langchain-test/node_modules/@langchain/community/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:294:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:9)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/private/tmp/19/langchain-test/index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.10.0
```

-----

If we update `index.js` like so:

```js
'use strict'

const lcc = require('@langchain/community/load')
console.dir(lcc)
```

We instead get:

```
❯ node index.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '@gomomento/sdk-core'
Require stack:
- /private/tmp/19/langchain-test/node_modules/@langchain/community/dist/caches/momento.cjs
- /private/tmp/19/langchain-test/node_modules/@langchain/community/dist/load/import_map.cjs
- /private/tmp/19/langchain-test/node_modules/@langchain/community/dist/load/index.cjs
- /private/tmp/19/langchain-test/node_modules/@langchain/community/load.cjs
- /private/tmp/19/langchain-test/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/private/tmp/19/langchain-test/node_modules/@langchain/community/dist/caches/momento.cjs:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/19/langchain-test/node_modules/@langchain/community/dist/caches/momento.cjs',
    '/private/tmp/19/langchain-test/node_modules/@langchain/community/dist/load/import_map.cjs',
    '/private/tmp/19/langchain-test/node_modules/@langchain/community/dist/load/index.cjs',
    '/private/tmp/19/langchain-test/node_modules/@langchain/community/load.cjs',
    '/private/tmp/19/langchain-test/index.js'
  ]
}

Node.js v20.10.0
```

**Comment by jsumners-nr** [comment]
Please go away bot. I want a human to look at this.

**Comment by jacoblee93** [comment]
Thanks for the report!

I suppose the error could be clearer, but this is by design as there is no default entrypoint for `@langchain/community`.

**Comment by jsumners-nr** [comment]
Then how is this package supposed to be used?

**Comment by jacoblee93** [comment]
See e.g. https://js.langchain.com/docs/integrations/chat/fireworks
