### ISSUE TITLE
Issue with HuggingFaceTransformersEmbeddings in Obsidian plugin

### ISSUE THREAD

**Issue by logancyang** [langchain-ai/langchainjs#4091]
Hi I'm trying to follow this [instruction at LangchainJS](https://js.langchain.com/docs/integrations/text_embedding/transformers) to use the huggingface transformers embeddings in my Obsidian plugin [copilot](https://github.com/logancyang/obsidian-copilot), but am seeing an error regarding this package, not sure how to fix, any help is greatly appreciated! Let me know if anything else is needed to debug this.

## Reproduction
```js
// node_modules/@xenova/transformers/src/env.js
var import_meta = {};
var { env: onnx_env } = ONNX;
var VERSION2 = "2.14.0";
var WEB_CACHE_AVAILABLE = typeof self !== "undefined" && "caches" in self;
var FS_AVAILABLE = !isEmpty(import_fs.default);
var PATH_AVAILABLE = !isEmpty(import_path.default);
var RUNNING_LOCALLY = FS_AVAILABLE && PATH_AVAILABLE;
var __dirname = RUNNING_LOCALLY ? import_path.default.dirname(import_path.default.dirname(import_url.default.fileURLToPath(import_meta.url))) : "./";

Error:
Plugin failure: copilot TypeError: The "path" argument must be of type string or an instance of URL. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at Object.fileURLToPath (node:internal/url:1491:11)
    at anonymous (plugin:copilot:89293:110)
    at e.<anonymous> (app.js:1:2026677)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

## esbuild
Obsidian uses esbuild and here's my config
```js
import builtins from "builtin-modules";
import esbuild from "esbuild";
import svgPlugin from "esbuild-plugin-svg";
import process from "process";
import wasmPlugin from "./wasmPlugin.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [svgPlugin(), wasmPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
```

## System Info
transformers.js version: 2.14.0
MacOS Sonoma 14.2.1, M3 max
NodeJS: v19.8.1
React: v18.2.0

## Environment/Platform
Obsidian (Electron)

**Comment by logancyang** [comment]
Just confirmed with the Obsidian community, ESM is not an option now, all plugins must be in CJS format. I wonder what I can do here, can anybody give me some pointers?

**Comment by TommyX12** [comment]
Hi @logancyang, I am also seeing the same issue. Could you share how you have resolved it? Thanks!
