### ISSUE TITLE
Invalid PDF Structure

### ISSUE THREAD

**Issue by Adetimmy** [langchain-ai/langchainjs#4183]
pdf parser returning invalid PDf structure, meanwhile the returned pdf web browser view url works fine.  
![Welcome to Clerk Docs _ Clerk - Google Chrome 1_27_2024 7_49_09 AM](https://github.com/langchain-ai/langchainjs/assets/114164808/7eedc69f-0f8f-4037-913c-4b21a3b0820a)

**Comment by Adetimmy** [comment]
@dosubot what features or structures are not supported by the pdf-parser? Even if the pdf contains only text, yet it still throws same error "Invalid Pdf structure"

**Comment by Adetimmy** [comment]
@dosubot: here is the error output on the terminal "Warning: Indexing all PDF objects
Error
    at InvalidPDFExceptionClosure (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:437:49)
    at Object.eval (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:440:14)
    at __w_pdfjs_require__ (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:35:40)
    at Object.eval (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:7907:35)
    at __w_pdfjs_require__ (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:35:40)
    at eval (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:72:25)
    at eval (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:73:15)
    at webpackUniversalModuleDefinition (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:16:32)
    at eval (webpack-internal:///(sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:18:3)
    at (sc_server)/./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js (C:\Users\OGUNLE.OGUNLE\Desktop\Chatpdf_Cloudinary\task\.next\server\_sc_server_node_modules_pdf-parse_lib_pdf_js_v1_10_100_build_pdf_js.js:20:1)
    at __webpack_require__ (C:\Users\OGUNLE.OGUNLE\Desktop\Chatpdf_Cloudinary\task\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__.t (C:\Users\OGUNLE.OGUNLE\Desktop\Chatpdf_Cloudinary\task\.next\server\webpack-runtime.js:73:38)
    at async PDFLoader.PDFLoaderImports [as pdfjs] (webpack-internal:///(sc_server)/./node_modules/langchain/dist/document_loaders/fs/pdf.js:133:34)
    at async PDFLoader.parse (webpack-internal:///(sc_server)/./node_modules/langchain/dist/document_loaders/fs/pdf.js:62:42) {
  message: 'Invalid PDF structure'
}"

**Comment by Adetimmy** [comment]
@mundume No, i'm not. neither i'm i using aws, rather using cloudinary for the pdf storage and retrieval.

**Comment by mundume** [comment]
I'm sorry I'm not able to help you with that. good luck

**Comment by Adetimmy** [comment]
@mundume thank you😞

**Comment by ogagnon07** [comment]
I'm getting the exact same issue here. when I upload my pdf, i send it's base64Date to my api that converts it into a pdf with fs. then I try to upload it and i'm getting the same problem as @Adetimmy.
