### ISSUE TITLE
Chat bedrock model fails when invoked.

### ISSUE THREAD

**Issue by siddbima-1** [langchain-ai/langchainjs#4355]
When we invoke the bedrock chat model with an input, we get the following error:
```bash

/dist/node_modules/@langchain/core/dist/messages/index.cjs:50
        if (!fields.additional_kwargs) {
                    ^

TypeError: Cannot read properties of undefined (reading 'additional_kwargs')
    at new BaseMessage (/dist/node_modules/@langchain/core/dist/messages/index.cjs:50:21)
    at new AIMessage (/dist/node_modules/@langchain/core/dist/messages/index.cjs:223:1)
    at BedrockChat._generate (/dist/node_modules/@langchain/core/dist/language_models/chat_models.cjs:353:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async BedrockChat._generateUncached (/dist/node_modules/@langchain/core/dist/language_models/chat_models.cjs:114:25)
    at async BedrockChat.invoke (/dist/node_modules/@langchain/core/dist/language_models/chat_models.cjs:54:24)
    at async Assistant.sendPromptToLLM (/dist/src/Assistant.js)

Node.js v18.5.0
Langchain versions 0.0.169 - 0.0.214
```

**Comment by siddbima-1** [comment]
I tried the above by passing `HumanMessage` wrapped in array as suggested here: https://github.com/langchain-ai/langchainjs/blob/main/examples/src/models/chat/integration_bedrock.ts
But doesn't work. If you observe the call stack, the error is at `AIMessage` which is something the model returns instead of the value that we pass.

**Comment by jacoblee93** [comment]
Hey @siddbima-1, looking into this, thank you for the report!

**Comment by jacoblee93** [comment]
Ok, our integration tests pass. Can you share your code?

**Comment by siddbima-1** [comment]
Sure. Here's the code:

``` JavaScript
static async sendPromptToLLM(model: string | undefined, prompt: string) {
    const llm = LangChainLLMFactory.create(model);

    const response = await llm.invoke([new HumanMessage({ content: prompt, additional_kwargs: {} }, {})]);
    return response.content.toString();
  }
```

`LLMFactory` creates the following model:

```JavaScript
new BedrockChat({
    model: model,
    temperature: DEFAULT_TEMP,
    maxTokens: maxTokens,
    modelKwargs: {},
  });
```

`model: anthropic.claude-v2`

**Comment by jacoblee93** [comment]
You're passing a second empty object to `.invoke`.

**Comment by siddbima-1** [comment]
Based on the invoke function definition, the second argument is for call options and I can pass an empty object for call options. Not sure if that would affect the invoke call.

I removed the empty object:
```Javascript
 const response = await llm.invoke([new HumanMessage({ content: prompt, additional_kwargs: {} })]);
 return response.content.toString();
```
I run into the exact same issue.
```
TypeError: Cannot read properties of undefined (reading 'additional_kwargs')
    at new BaseMessage (/dist/node_modules/@langchain/core/dist/messages/index.cjs:50:21)
    at new AIMessage (/dist/node_modules/@langchain/core/dist/messages/index.cjs:223:1)
    at BedrockChat._generate (/dist/node_modules/@langchain/core/dist/language_models/chat_models.cjs:353:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async BedrockChat._generateUncached (/dist/node_modules/@langchain/core/dist/language_models/chat_models.cjs:114:25)
    at async BedrockChat.invoke (/dist/node_modules/@langchain/core/dist/language_models/chat_models.cjs:54:24)
    at async Assistant.sendPromptToLLM (/dist/src/Assistant.js)
```

**Comment by siddbima-1** [comment]
Could we please reopen the issue?

**Comment by jacoblee93** [comment]
> Based on the invoke function definition, the second argument is for call options and I can pass an empty object for call options. Not sure if that would affect the invoke call.

That only applies for runnables, not `HumanMessages`

I would suggest using TypeScript or something similar:

```ts
 const response = await llm.invoke([
    new HumanMessage({ content: "Hello there" })
 ]);
 console.log(response);
```

works just fine for me

**Comment by siddbima-1** [comment]
I am using TypeScript.  I get the above-mentioned error even if I set the `"additional_ kwargs"` to `undefined`.
Based on the call stack, looks like the error is coming from the return value. Where `fields` property of the `AIMessage` is `undefined` while trying to settle the promise. 
I am not sure if me passing the `HumanMessage` with/without `"additional_kwargs"` is a contributing factor or passing `"{}"` for call options in invoke is affecting the output.
I am using `@aws-sdk/client-bedrock-runtime` version `3.504.0`
What's the version of @aws-sdk/client-bedrock-runtime for integration tests?
