### ISSUE TITLE
Safety-blocked Gemini Pro requests causes failure

### ISSUE THREAD

**Issue by jarib** [langchain-ai/langchainjs#4375]
Not sure what's the correct fix for this, but [here's a](https://github.com/langchain-ai/langchainjs/pull/4374) is a draft PR with a  failing test.

```
  ● Mock ChatGoogle › 2. Blocked response

    TypeError: Cannot read properties of undefined (reading 'message')

      51 |         const chatGeneration = result.generations[0][0];
      52 |         // TODO: Remove cast after figuring out inheritance
    > 53 |         return chatGeneration.message;
         |                               ^
      54 |     }
      55 |     // eslint-disable-next-line require-yield
      56 |     async *_streamResponseChunks(_messages, _options, _runManager) {

      at ChatGoogle.invoke (../../langchain-core/dist/language_models/chat_models.js:53:31)
      at RunnableSequence.invoke (../../langchain-core/dist/runnables/base.js:1014:33)
      at Object.<anonymous> (src/tests/chat_models.test.ts:245:20)

 PASS  src/tests/llms.test.ts
 ```

**Comment by jacoblee93** [comment]
@afirstenberg

**Comment by afirstenberg** [comment]
@jacoblee93  - Please assign this to me. {:
(The other one was for the tests. This will remind me I need to make a fix.)

**Comment by jacoblee93** [comment]
Thank you so much!
