### ISSUE TITLE
WebPDFLoader: 'Invalid PDF structure'

### ISSUE THREAD

**Issue by ajaykrupalk** [langchain-ai/langchainjs#4448]
Currently I am uploading a pdf file in my frontend and creating an URL for it using URL.createObjectURL() and then I am passing this as a string to my backend (e.g. `"blob:http://localhost:5173/81373d30-ea1e-40c0-bf95-3fa38f5a3000"`). After which in my backend I am converting it to a blob using `const blob = new Blob([fileUrl], { type: 'application/pdf' });` When I am trying to load and split my pdf, using the below code:

```js
async function loadAndSplitChunks({
    fileUrl,
    chunkSize,
    chunkOverlap
}) {
    const blob = new Blob([fileUrl], { type: 'application/pdf' });

    const loader = new WebPDFLoader(blob, {splitPages: false})

    const rawCS229Docs = await loader.load();

    const splitter = new RecursiveCharacterTextSplitter({
        chunkSize,
        chunkOverlap,
    });

    const splitDocs = await splitter.splitDocuments(rawCS229Docs);
    return splitDocs;
}
```

**I am getting the following error:**

```
[1] Warning: Indexing all PDF objects
[1] Error
[1]     at InvalidPDFExceptionClosure (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:452:35)
[1]     at Object.<anonymous> (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:455:2)
[1]     at __w_pdfjs_require__ (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:45:30)
[1]     at Object.<anonymous> (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:7939:23)
[1]     at __w_pdfjs_require__ (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:45:30)
[1]     at D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:88:18
[1]     at D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:91:10
[1]     at webpackUniversalModuleDefinition (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:18:20)
[1]     at Object.<anonymous> (D:\rag-app\backend\node_modules\pdf-parse\lib\pdf.js\v1.10.100\build\pdf.js:25:3)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14) {
[1]   message: 'Invalid PDF structure'
[1] }
```

**Is there a better way to do this or to fix this?**

**Comment by ajaykrupalk** [comment]
@dosu-bot await fs.readFile(filePath); will not work in my case since my filePath is a blob object URL like "blob:http://localhost:5173/81373d30-ea1e-40c0-bf95-3fa38f5a3000". Please suggest how and what I should pass to filePath

**Comment by ajaykrupalk** [comment]
@dosu-bot

I am passing a blob URL and not an HTTP URL, with the below code:

import fetch from 'node-fetch';

const blobUrl = 'blob:http://localhost:5173/81373d30-ea1e-40c0-bf95-3fa38f5a3000';
const response = await fetch(blobUrl);
const blob = await response.blob();

const loader = new WebPDFLoader(blob);
const docs = await loader.load();

I am getting this error:

TypeError: node-fetch cannot load blob:http://localhost:5173/81373d30-ea1e-40c0-bf95-3fa38f5a3000. URL scheme "blob" is not supported
