### ISSUE TITLE
Bug: Azure Openai function calling in streaming mode

### ISSUE THREAD

**Issue by dkindlund** [langchain-ai/langchainjs#4488]
I think the same bug that happened in https://github.com/langchain-ai/langchain also is happening within https://github.com/langchain-ai/langchainjs.

The details of the bug are mentioned in https://github.com/langchain-ai/langchain/pull/13768

> This PR addresses an issue with the OpenAI API streaming response, where initially the key (arguments) is provided but the value is None. Subsequently, it updates with {"arguments": "{\n"}, leading to a type inconsistency that causes an exception. The specific error encountered is ValueError: additional_kwargs["arguments"] already exists in this message, but with a different type. This change aims to resolve this inconsistency and ensure smooth API interactions.

Specifically, if you compare this line in the Python code:
https://github.com/langchain-ai/langchain/pull/13768/files#diff-24da96d76a6879fdeae0c02dee3d6be7fee76cc49963d61123c01d85a9f5cec9L79

To this line in the JavaScript code:
https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/messages/index.ts#L248

I believe the *same* bug exists.

Can someone confirm and possibly fix this?  Thanks!

**Comment by dkindlund** [comment]
There's also another Python-based PR mentioning this bug as well:
https://github.com/langchain-ai/langchain/pull/13229

@dosubot, I don't think I'm familiar enough with the internals of the langchainjs code to submit a PR on this right now.  I'm hoping some other langchainjs expert can comment on 1) whether this issue exists and 2) if the python-based fix can be equally applied to this library as well.

**Comment by dkindlund** [comment]
Hey @jacoblee93 and @hcl242, since you guys both have recently handled similar issues with AzureOpenAI, could you possibly take a look at this one to see if you're also getting problems with langchainjs.

The (rough) steps to reproduce are:
* Use an Azure OpenAI model of `gpt-3.5-turbo-1106`
* Invoke the model using streaming mode *and* function calling.
* Obtain the following error:
```
Error: additional_kwargs[arguments] already exists in the message chunk, but with a different type.
    at AIMessageChunk._mergeAdditionalKwargs (/usr/src/packages/node_modules/@langchain/core/dist/messages/index.cjs:147:23)
    at AIMessageChunk._mergeAdditionalKwargs (/usr/src/packages/node_modules/@langchain/core/dist/messages/index.cjs:154:36)
    at AIMessageChunk.concat (/usr/src/packages/node_modules/@langchain/core/dist/messages/index.cjs:246:47)
    at ChatGenerationChunk.concat (/usr/src/packages/node_modules/@langchain/core/dist/outputs.cjs:55:35)
    at ChatOpenAI._generate (/usr/src/packages/node_modules/@langchain/openai/dist/chat_models.cjs:503:61)
```

The Python langchain developers *already* confirmed the problem existed in the Python version of langchain, as mentioned in the following PRs:
https://github.com/langchain-ai/langchain/pull/13229
https://github.com/langchain-ai/langchain/pull/13768

I'm simply trying to port this fix over to langchainjs as well.  Any thoughts would be appreciated -- thanks!

**Comment by dkindlund** [comment]
There exist unit tests for validating this edge case in the Python langchain library:
https://github.com/langchain-ai/langchain/blob/master/libs/core/tests/unit_tests/test_messages.py#L48

...but I don't know where such equivalent unit tests exist in the langchainjs library.

Hey @aymeric-roucher, @hwchase17, since you both were involved with the PR fix for this issue on the Python side, perhaps you could provide more context here on the issue for the JavaScript team?  Thanks in advance.

**Comment by dkindlund** [comment]
Update: We were able to work around this bug by having the LiteLLM OpenAI Proxy adjust its output during streaming function calls.

The OpenAI API returned streaming chunks in this format:
```
... "function_call":{"name":"web-browser","arguments":""} ...
... "function_call":{"arguments":"{\""} ...
... "function_call":{"arguments":"input"} ...
...
```

The LiteLLM proxy was returning those same chunks in this format:
```
... "function_call": {"arguments": "", "name": "web-browser"} ...
... "function_call": {"arguments": "{\"", "name": null} ...
... "function_call": {"arguments": "input", "name": null} ...
...
```

LangchainJS was throwing errors when processing those chunks from the LiteLLM proxy with this sort of error:
```additional_kwargs[name] already exists in the message chunk, but with a different type.```

The workaround is to have the LiteLLM proxy basically strip the `name` parameter from each streaming chunk if the value is set to `null`.

We suspect this problem does *not* exist in the Python version of Langchain, because additional handling of these corner cases was handled more robustly.

If/when the OpenAI function calling streaming format changes in the future, it would make sense for LangchainJS to eventually have the same robust logic added to it.

For now, though, we've got a successful workaround.

**Comment by jacoblee93** [comment]
Glad to hear it! Should tighten this up for sure.
