### ISSUE TITLE
value for argument "data" is not a valid Firestore document

### ISSUE THREAD

**Issue by RedouanAssakali** [langchain-ai/langchainjs#4492]
Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field "data.additional_kwargs.tool_calls"). If you want to ignore undefined values, enable `ignoreUndefinedProperties`.
    at validateUserInput (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/@google-cloud/firestore/build/src/serializer.js:279:19)
    at validateUserInput (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13)
    at validateUserInput (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13)
    at validateUserInput (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13)
    at validateDocumentData (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/@google-cloud/firestore/build/src/write-batch.js:598:40)
    at CollectionReference.add (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/@google-cloud/firestore/build/src/reference.js:2338:48)
    at FirestoreChatMessageHistory.upsertMessage (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/langchain/dist/stores/message/firestore.cjs:151:14)
    at async FirestoreChatMessageHistory.addMessage (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/langchain/dist/stores/message/firestore.cjs:139:9)
    at async OpenAIAgentTokenBufferMemory.saveContext (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/langchain/dist/agents/toolkits/conversational_retrieval/token_buffer_memory.cjs:110:13)
    at async AgentExecutor.call (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/langchain/dist/chains/base.cjs:136:13)
const {OpenAI} = require('langchain/llms/openai');
const {initializeAgentExecutorWithOptions} = require('langchain/agents');

const {PineconeStore} = require('langchain/vectorstores/pinecone');
const {OpenAIEmbeddings} = require('langchain/embeddings/openai');
const admin = require("firebase-admin");
const {Pinecone} = require('@pinecone-database/pinecone');

const {BufferMemory, ChatMessageHistory} = require('langchain/memory'); // Import BufferMemory
const {FirestoreChatMessageHistory} = require('langchain/stores/message/firestore'); // Import FirestoreChatMessageHistory
const {PromptTemplate} = require("langchain/prompts");

const {ChainTool, DynamicTool} = require("langchain/tools");
const {ConversationalRetrievalQAChain} = require('langchain/chains');
const {response} = require("express");
const {ChatOpenAI} = require("@langchain/openai");
const {makeChain} = require("./makechain");
const {MessagesPlaceholder} = require("@langchain/core/prompts");
const {OpenAIAgentTokenBufferMemory} = require("langchain/agents/toolkits");
const {getArabicExplanation} = require("./diwan");

const runChatbot = async (vectorStore, sessionId, uid, chatbotData) => {

    const model = new ChatOpenAI({
        temperature: 0.5,
        modelName: chatbotData.activeModel,
        openAIApiKey: "*******************"

    });

    const firestoreConfig = {
        collectionName: "chathistory",
        sessionId: sessionId,
        userId: uid,
        config: {projectId: "unity-352c6"},
    };

    // Initialize the FirestoreChatMessageHistory for chat history
    // Here a new sub collection for messages was made
    const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);

    const memory = new OpenAIAgentTokenBufferMemory({

        chatHistory,
        memoryKey: "chat_history",
        inputKey: "input",
        outputKey: "output",
    });
    // Create a conversational chain
    const retrievalChain = makeChain(vectorStore, sessionId, uid, chatbotData)

    const qaTool = new ChainTool({
        name: `qa_tool`,
        description: `Books of the ${chatbotData.name} QA - useful for when you need to ask questions about the opinion of ${chatbotData.name} ro about your life because you are ${chatbotData.name}.`,
        chain: retrievalChain,
        returnDirect: true,
        verbose: true
    })
    const arabicExplanationTool = new DynamicTool({
        name: "arabic-explanation",
        description: "Retrieve the Arabic explanation of a word in Cheikh Ahmad al-Alawi's poems. you need to write the word in Arabic with full diacritics (Tashkeel)",
        func: async (word) => {
            try {
                return await getArabicExplanation(word);
            } catch (error) {
                return `Error retrieving Arabic explanation: ${error.message}`;
            }
        }
    });

    const tools = [qaTool, arabicExplanationTool]

    return await initializeAgentExecutorWithOptions(tools, model, {
        agentType: 'openai-functions',
        memory: memory,
        returnIntermediateSteps: true,
        agentArgs: {
            prefix: `You are now embodying the wisdom of ${chatbotData.name}. Your role is to answer questions about his teachings and poetry. Utilize the tools at your disposal to access his books and writings, and respond with insights drawn from his profound works.`,

    // `You are ${chatbotData.name}  answering questions about ${chatbotData.name} you can use tools to read his books answer question with this information.`,
            memoryPrompts: [new MessagesPlaceholder("chat_history")],
        }
    })

}
module.exports = {runChatbot};

**Comment by RedouanAssakali** [comment]
ok here my route: router.post('/chat-agent', async (req, res) => {
    // Handles incoming chat requests
    const {question, history, sessionId, uid, chatbot} = req.body;


    // Validate input
    if (!sessionId || !uid) {
        return res.status(400).json({message: 'No session id in the request'});
    }

    // Check if a question is provided
    if (!question) {
        return res.status(400).json({message: 'No question in the request'});
    }

    // Check if a chatbot is provided
    if (!chatbot) {
        return res.status(400).json({message: 'No chatbot in the request'});
    }

    // Sanitize the question
    const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

    //Retrieve the chatbot from firestore
    const chatbotReference = await admin.firestore().collection('chatbots').doc(chatbot).get();
    const chatbotData = chatbotReference.data();

    history.forEach(msg => {
        console.log(`Type: ${msg.role}, Message: ${msg.content}`);
    });

    const transformedHistory = history.map(msg => {
        return msg.role === 'user'
            ? new CustomHumanMessage({ content: msg.content, name: "user", additional_kwargs: {} })
            : new CustomAIMessage({ content: msg.content, name: chatbotData.name, additional_kwargs: {} });
    });
    const jsonHistory = transformedHistory.map(msg => msg.toJSON());

    console.log('JSON Transformed History:', jsonHistory);

    console.log('Transformed History:', transformedHistory);


    try {
        // Pinecone setup and initialization
        const pinecone = new Pinecone({
            apiKey: process.env.PINECONE_API_KEY,
            environment: process.env.PINECONE_ENVIRONMENT,
        });

        const index = pinecone.Index(process.env.PINECONE_INDEX_NAME);


        // Create a vector store
        const vectorStore = await PineconeStore.fromExistingIndex(
            new OpenAIEmbeddings({}),
            {
                pineconeIndex: index,
                textKey: 'text',
                namespace: chatbot,
            }
        );
        // Create a conversational chain
        const executor = await runChatbot(vectorStore, sessionId, uid, chatbotData);

        // Query the chain
        const response = await executor.call(
            {
                author: chatbot,
                input: sanitizedQuestion,
                chat_history: jsonHistory
            },
        )

        console.log(response)
        // Send the response back to the client
        res.status(200).json(response);
    } catch (error) {
        console.error('Error in chat route:', error);
        res.status(500).json({error: error.message || 'Something went wrong'});
    }
});

**Comment by RedouanAssakali** [comment]
@dosu-bot ok here my route: router.post('/chat-agent', async (req, res) => {
// Handles incoming chat requests
const {question, history, sessionId, uid, chatbot} = req.body;

// Validate input
if (!sessionId || !uid) {
    return res.status(400).json({message: 'No session id in the request'});
}

// Check if a question is provided
if (!question) {
    return res.status(400).json({message: 'No question in the request'});
}

// Check if a chatbot is provided
if (!chatbot) {
    return res.status(400).json({message: 'No chatbot in the request'});
}

// Sanitize the question
const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

//Retrieve the chatbot from firestore
const chatbotReference = await admin.firestore().collection('chatbots').doc(chatbot).get();
const chatbotData = chatbotReference.data();

history.forEach(msg => {
    console.log(`Type: ${msg.role}, Message: ${msg.content}`);
});

const transformedHistory = history.map(msg => {
    return msg.role === 'user'
        ? new CustomHumanMessage({ content: msg.content, name: "user", additional_kwargs: {} })
        : new CustomAIMessage({ content: msg.content, name: chatbotData.name, additional_kwargs: {} });
});
const jsonHistory = transformedHistory.map(msg => msg.toJSON());

console.log('JSON Transformed History:', jsonHistory);

console.log('Transformed History:', transformedHistory);


try {
    // Pinecone setup and initialization
    const pinecone = new Pinecone({
        apiKey: process.env.PINECONE_API_KEY,
        environment: process.env.PINECONE_ENVIRONMENT,
    });

    const index = pinecone.Index(process.env.PINECONE_INDEX_NAME);


    // Create a vector store
    const vectorStore = await PineconeStore.fromExistingIndex(
        new OpenAIEmbeddings({}),
        {
            pineconeIndex: index,
            textKey: 'text',
            namespace: chatbot,
        }
    );
    // Create a conversational chain
    const executor = await runChatbot(vectorStore, sessionId, uid, chatbotData);

    // Query the chain
    const response = await executor.call(
        {
            author: chatbot,
            input: sanitizedQuestion,
            chat_history: jsonHistory
        },
    )

    console.log(response)
    // Send the response back to the client
    res.status(200).json(response);
} catch (error) {
    console.error('Error in chat route:', error);
    res.status(500).json({error: error.message || 'Something went wrong'});
}

});

**Comment by RedouanAssakali** [comment]
@dosu-bot still same error: Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field "data.additional_kwargs.tool_calls").  const {OpenAI} = require('langchain/llms/openai');
const {initializeAgentExecutorWithOptions} = require('langchain/agents');

const {PineconeStore} = require('langchain/vectorstores/pinecone');
const {OpenAIEmbeddings} = require('langchain/embeddings/openai');
const admin = require("firebase-admin");
const {Pinecone} = require('@pinecone-database/pinecone');

const {BufferMemory, ChatMessageHistory} = require('langchain/memory'); // Import BufferMemory
const {FirestoreChatMessageHistory} = require('langchain/stores/message/firestore'); // Import FirestoreChatMessageHistory
const {PromptTemplate} = require("langchain/prompts");

const {ChainTool, DynamicTool} = require("langchain/tools");
const {ConversationalRetrievalQAChain} = require('langchain/chains');
const {response} = require("express");
const {ChatOpenAI} = require("@langchain/openai");
const {makeChain} = require("./makechain");
const {MessagesPlaceholder} = require("@langchain/core/prompts");
const {OpenAIAgentTokenBufferMemory} = require("langchain/agents/toolkits");
const {getArabicExplanation} = require("./diwan");


const runChatbot = async (vectorStore, sessionId, uid, chatbotData) => {

    const model = new ChatOpenAI({
        temperature: 0.5,
        modelName: chatbotData.activeModel,
        openAIApiKey: "*********************"

    });

    const firestoreConfig = {
        collectionName: "chathistory",
        sessionId: sessionId,
        userId: uid,
        config: {projectId: "unity-352c6"},
        ignoreUndefinedProperties: true,
    };

    // Initialize the FirestoreChatMessageHistory for chat history
    // Here a new sub collection for messages was made
    const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);



    const memory = new OpenAIAgentTokenBufferMemory({
        llm: model,
        chatHistory: chatHistory,
        memoryKey: 'chat_history',
        outputKey: 'output',
        inputKey: 'input'
    })
    // Create a conversational chain
    const retrievalChain = makeChain(vectorStore, sessionId, uid, chatbotData)

    const qaTool = new ChainTool({
        name: `qa_tool`,
        description: `Books of the ${chatbotData.name} QA - useful for when you need to ask questions about the opinion of ${chatbotData.name} ro about your life because you are ${chatbotData.name}.`,
        chain: retrievalChain,
        returnDirect: true,
        verbose: true
    })
    const arabicExplanationTool = new DynamicTool({
        name: "arabic-explanation",
        description: "Retrieve the Arabic explanation of a word in Cheikh Ahmad al-Alawi's poems. you need to write the word in Arabic with full diacritics (Tashkeel)",
        func: async (word) => {
            try {
                return await getArabicExplanation(word);
            } catch (error) {
                return `Error retrieving Arabic explanation: ${error.message}`;
            }
        }
    });



    const tools = [qaTool, arabicExplanationTool]

    return await initializeAgentExecutorWithOptions(tools, model, {
        agentType: 'openai-functions',
        memory: memory,
        returnIntermediateSteps: true,
        agentArgs: {
            prefix: `You are now embodying the wisdom of ${chatbotData.name}. Your role is to answer questions about his teachings and poetry. Utilize the tools at your disposal to access his books and writings, and respond with insights drawn from his profound works. You can use the books as a tool `,

    // `You are ${chatbotData.name}  answering questions about ${chatbotData.name} you can use tools to read his books answer question with this information.`,
            memoryPrompts: [new MessagesPlaceholder("chat_history")],
        }
    })


}
module.exports = {runChatbot};
