### ISSUE TITLE
this.embeddings.embedDocuments is not a function

### ISSUE THREAD

**Issue by Slyke** [langchain-ai/langchainjs#4501]
What am I doing wrong here?
```
import { Ollama } from "@langchain/community/llms/ollama";
import { OllamaEmbeddings } from "@langchain/community/embeddings/ollama";
import weaviate, { ApiKey } from "weaviate-ts-client";
import { WeaviateStore } from "@langchain/weaviate";

const ollama = new Ollama({
  baseUrl: "http://localhost:11434",
  model: "llama2"
});

const embeddings = new OllamaEmbeddings({
  model: "llama2",
  baseUrl: "http://localhost:11434"
});

const weaviateClient = weaviate.client({
  scheme: process.env.WEAVIATE_SCHEME || "http",
  host: process.env.WEAVIATE_HOST || "localhost",
  port: process.env.WEAVIATE_PORT || "8080",
  apiKey: new ApiKey(process.env.WEAVIATE_API_KEY || ""),
});
const documents = ["hello world", "hi there", "bye now"];
const documentEmbeddings = await embeddings.embedDocuments(documents);

console.log({ documentEmbeddings }); // Prints out the array of vectors

const results = await WeaviateStore.fromTexts( // This block errors
  documents,
  [{ foo: "bar" }, { foo: "baz" }, { foo: "bar" }],
  documentEmbeddings, // Also tried with the embeddings variable here
  {
    client: weaviateClient,
    indexName: "Test",
    textKey: "text",
    metadataKeys: ["foo"],
  }
);

console.log({ results });
```

Errors with:
```
file:///.../dist/vectorstores.js:168
        return this.addVectors(await this.embeddings.embedDocuments(documents.map((d) => d.pageContent)), documents, options);
                                                     ^

TypeError: this.embeddings.embedDocuments is not a function
    at WeaviateStore.addDocuments (file:///home/slyke/path/to/app/node_modules/@langchain/weaviate/dist/vectorstores.js:168:54)
    at WeaviateStore.fromDocuments (file:///.../dist/vectorstores.js:322:24)
    at WeaviateStore.fromTexts (file:///.../dist/vectorstores.js:310:30)
    at file:///home/slyke/path/to/app/test.js:38:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm looking at: https://api.js.langchain.com/classes/langchain_weaviate.WeaviateStore.html and following this example: https://js.langchain.com/docs/integrations/vectorstores/weaviate while referencing https://js.langchain.com/docs/use_cases/question_answering/local_retrieval_qa and https://js.langchain.com/docs/integrations/text_embedding/ollama

The example is not clear on how `weaviateStore.fromTexts` uses `new OpenAIEmbeddings()` since it's just imported in. I believe there needs to be some OllamaEmbeddingsInterface passed into [here](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/embeddings.ts#L9). Passing `documentEmbeddings` and `embeddings` both cause errors and I'm unsure how to use `Ollama` or `OllamaEmbeddings` with `WeaviateStore.fromTexts`.

**Comment by Slyke** [comment]
Hey @dosubot,

I'm using the latest versions of the npm modules, just created a new project with `npm init` and ran all the npm installs. The `OllamaEmbeddings` class does have the `embedDocuments` function. This function returns:
```
{
  documentEmbeddings: [
    [
        1.1969940662384033, -0.052228473126888275,      1.546292781829834,
        // ... brevity snip
        1.4512828588485718,
      ... 3996 more items
    ],
    [
         2.5101842880249023,   -3.273963451385498, -0.14006204903125763,
        // ... brevity snip
       -0.19518393278121948, -0.40836334228515625,   -1.797864317893982,
          1.854506015777588,
      ... 3996 more items
    ],
    [
         2.894432783126831,   -2.758491039276123,  -0.43672826886177063,
        // ... brevity snip
       -0.1770072877407074,  0.12030475586652756,   -0.6426188945770264,
        1.7523319721221924,
      ... 3996 more items
    ]
  ]
}
```

From this line:
```
const documentEmbeddings = await embeddings.embedDocuments(documents);
```

So we can conclude that it's working.

However, when passing the object that's in the documentEmbeddings variable into `WeaviateStore.fromTexts` it errors with: `TypeError: this.embeddings.embedDocuments is not a function`.

So it seems like `WeaviateStore.fromTexts` does not accept the result from the `OllamaEmbeddings::embedDocuments()` function.

**Comment by Slyke** [comment]
This is what I initially tried, but was getting fetch errors. When I modify the code to what you provided I get the following error:
```
file:///...dist/vectorstores.js:155
            throw Error(`Error adding vectors: ${e}`);
                  ^

Error: Error adding vectors: TypeError: fetch failed
    at WeaviateStore.addVectors (file:///...dist/vectorstores.js:155:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WeaviateStore.fromDocuments (file:///...dist/vectorstores.js:322:9)
    at async file:///home/slyke/repos/llms/ollama/test.js:38:17

Node.js v20.11.0
```

I know that Weaviate is working correctly, because I can access it from my browser and it replies with:
```
{"links":[{ snipped a bunch of stuff }]}
```

It's also accessible with VectorAdmin, so I'm unsure why fetch is failing, as the error is not helpful.

**Comment by Slyke** [comment]
Figured out the solution, the code you provided was correct. The issue was that `weaviate.client` does not accept a `port` parameter, so I had to append 8080 onto the host field.

```
const weaviateClient = weaviate.client({
  scheme: process.env.WEAVIATE_SCHEME || "http",
  host: process.env.WEAVIATE_HOST || "localhost:8080" // <--- Here
  apiKey: new ApiKey(process.env.WEAVIATE_API_KEY || ""),
});
```
