### ISSUE TITLE
 [Agent] createRetrieverTool: Received tool input did not match expected schema

### ISSUE THREAD

**Issue by fvisticot** [langchain-ai/langchainjs#4527]
version 0.1.17

I have an error when using the tool created with createRetrieverTool.

```
const agentExecutor = new AgentExecutor({
    agent,
    tools,
    returnIntermediateSteps: true,
    verbose: true
});
```

```
    const res =await vectorstore.similaritySearch("what is langsmith");
    console.log(res);

    const retriever = vectorstore.asRetriever({ k: 1 });

    return createRetrieverTool(retriever, {
        name: "langsmith_search",
        description: "A search engine used for langsmith search. Useful for when you need to answer questions about langsmith. Input should be a search query.",
    });
```

` Received tool input did not match expected schema
    at DynamicStructuredTool.call (file:///Users/aaa/WebstormProjects/aaa/node_modules/@langchain/core/dist/tools.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/aaa/WebstormProjects/aaa/node_modules/langchain/dist/agents/executor.js:442:27
    at async Promise.all (index 0)
    at async AgentExecutor._call (file:///Users/aaa/WebstormProjects/aaa/node_modules/langchain/dist/agents/executor.js:434:30)
    at async AgentExecutor.invoke (file:///Users/aaa/WebstormProjects/aaa/node_modules/langchain/dist/chains/base.js:53:28)
    at async file:///Users/aaa/WebstormProjects/aaa/index.mjs:79:16 {
`

**Comment by egonSchiele** [comment]
For others running into this in the future: set `verboseParsingErrors: true` on your tool. Example:

```ts
const fields = {
    name: "some_name",
      description:
        "My amazing tool",
      schema: SomeZodSchema,
      verboseParsingErrors: true // <---
};
tool(
    async (params) => { ... do something },
    fields
);
```
