### ISSUE TITLE
USearch - Error: `dimensions`, `connectivity`, `expansion_add`, and `expansion_search` must be non-negative integers, with `dimensions` being positive

### ISSUE THREAD

**Issue by Candoyeya** [langchain-ai/langchainjs#4528]
I'm trying to build a node API to embed with xenova and USearch as a vector store.

The problem is that even if I follow the documentation or initialize manually, I always get the following error.

Case 1 - With Documentation
```
// Loaders
import {WebPDFLoader} from 'langchain/document_loaders/web/pdf';
import {Blob} from 'buffer';
// Embeddigs
import {HuggingFaceTransformersEmbeddings} from '@langchain/community/embeddings/hf_transformers';
import {RecursiveCharacterTextSplitter} from 'langchain/text_splitter';
import {USearch} from '@langchain/community/vectorstores/usearch';ç

export const uploadFileV2 = async (req: Request, res: Response) => {

...

// Set embedding Tools
const embeddings = new HuggingFaceTransformersEmbeddings({
	modelName: 'nomic-ai/nomic-embed-text-v1',
});

// Process the loaded documents
const blob = new Blob([file.buffer]);
const pdfLoader = new WebPDFLoader(blob, {parsedItemSeparator: ' '});
const docs = await pdfLoader.load();

const splitter = new RecursiveCharacterTextSplitter({
	chunkSize: 1000,
	chunkOverlap: 50,
});

const splitDocs = await splitter.splitDocuments(docs);

// Load the docs into the vector store
const vectorStore = await USearch.fromDocuments(docs, embeddings);

// Search for the most similar document
const resultOne = await vectorStore.similaritySearch("hello world", 1);
console.log(resultOne);
}
```

Case 2 - With manual initialization
```
// Loaders
import {WebPDFLoader} from 'langchain/document_loaders/web/pdf';
import {Blob} from 'buffer';
// Embeddigs
import {HuggingFaceTransformersEmbeddings} from '@langchain/community/embeddings/hf_transformers';
import {RecursiveCharacterTextSplitter} from 'langchain/text_splitter';
import {USearch} from '@langchain/community/vectorstores/usearch';
import {SynchronousInMemoryDocstore} from '@langchain/community/stores/doc/in_memory';

export const uploadFileV2 = async (req: Request, res: Response) => {

...

// Set embedding Tools
const embeddings = new HuggingFaceTransformersEmbeddings({
	modelName: 'nomic-ai/nomic-embed-text-v1',
});

const vectorStore = new USearch(embeddings, {
	docstore: new SynchronousInMemoryDocstore(),
});

// Process the loaded documents
const blob = new Blob([file.buffer]);
const pdfLoader = new WebPDFLoader(blob, {parsedItemSeparator: ' '});
const docs = await pdfLoader.load();

const splitter = new RecursiveCharacterTextSplitter({
	chunkSize: 1000,
	chunkOverlap: 50,
});

const splitDocs = await splitter.splitDocuments(docs);

// Load the docs into the vector store
await vectorStore.addDocuments(docs);

// Search for the most similar document
const resultOne = await vectorStore.similaritySearch("hello world", 1);
console.log(resultOne);
}
```

Both cases return the same error.
```
Error: `dimensions`, `connectivity`, `expansion_add`, and `expansion_search` must be non-negative integers, with `dimensions` being positive.
    at new Index (/private/var/www/html/generative-ai/node_modules/usearch/javascript/usearch.js:162:19)
    at USearch.addVectors (/private/var/www/html/generative-ai/node_modules/@langchain/community/dist/vectorstores/usearch.cjs:111:27)
    at USearch.addDocuments (/private/var/www/html/generative-ai/node_modules/@langchain/community/dist/vectorstores/usearch.cjs:84:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```
 
 Package.json
 ```
"dependencies": {
		"@langchain/community": "^0.0.31",
		"@langchain/openai": "^0.0.12",
		"@pinecone-database/pinecone": "^1.1.3",
		"@xenova/transformers": "^2.14.2",
		"usearch": "^2.9.0"
	}
``` 

Node v20.11.0

**Comment by Candoyeya** [comment]
@dosu-bot

Everything seems to indicate that the error does not come from within the `@langchain/community` dependency, because the values sent to create the `index` are positive.

The problem lies directly in the dependency on `USearch`, currently it is not correctly validating values of type `BigInt`, in the current validation, it only validates that they are `Integer`, but technically they are not equal types, which is why it causes this problem .

USearch Dependency - Line 169 (Before of Patch)
```
if (!Number.isInteger(dimensions) || !Number.isInteger(connectivity) || !Number.isInteger(expansion_add) || !Number.isInteger(expansion_search) || dimensions <= 0 || connectivity < 0 || expansion_add < 0 || expansion_search < 0) {
            throw new Error("`dimensions`, `connectivity`, `expansion_add`, and `expansion_search` must be non-negative integers, with `dimensions` being positive.");
}
```

USearch Dependency - Line 169 (After of Patch)
```
if ((typeof dimensions !== 'bigint' && (!Number.isInteger(dimensions) || dimensions <= 0)) || 
            (typeof connectivity !== 'bigint' && (!Number.isInteger(connectivity) || connectivity < 0)) ||
            (typeof expansion_add !== 'bigint' && (!Number.isInteger(expansion_add) || expansion_add < 0)) ||
            (typeof expansion_search !== 'bigint' && (!Number.isInteger(expansion_search) || expansion_search < 0))) {
            throw new Error("`dimensions`, `connectivity`, `expansion_add`, and `expansion_search` must be non-negative integers, with `dimensions` being positive.");
}
```

With this I managed to take the dimension values, now I am getting a new error, possibly it is necessary to notify the `USearch` dependency directly.

New error
```
Error: Error in native callback
    at new Index (/private/var/www/html/generative-ai/node_modules/usearch/javascript/usearch.js:188:31)
    at USearch.addVectors (/private/var/www/html/generative-ai/node_modules/@langchain/community/dist/vectorstores/usearch.cjs:120:27)
    at USearch.addDocuments (/private/var/www/html/generative-ai/node_modules/@langchain/community/dist/vectorstores/usearch.cjs:85:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.fromDocuments (/private/var/www/html/generative-ai/node_modules/@langchain/community/dist/vectorstores/usearch.cjs:224:9)
    ```
