### ISSUE TITLE
indexing - postgres record manager inconsistently identifies which documents already exist, causing error

### ISSUE THREAD

**Issue by arrested-developer** [langchain-ai/langchainjs#4851]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { PostgresRecordManager } from '@langchain/community/indexes/postgres';
import { index } from 'langchain/indexes';
import { PGVectorStore } from '@langchain/community/vectorstores/pgvector';
import { PoolConfig } from 'pg';
import { OpenAIEmbeddings } from '@langchain/openai';

import { ConfluencePagesLoader, ConfluencePagesLoaderParams } from '@canx-tools/document-loaders';

// I assume you can provide your own values for these
import { openAIEmbeddingsParams, dbUri, confluenceUser, confluenceAccessToken } from './env';

// for some reason, this occasionally fails with an error on the ID constraint for the documents table...
// on closer inspection, the postgres query used to find if the documents already exist is returning results out of order

const main = async () => {
    const postgresConfig: PoolConfig = {
        connectionString: dbUri,
    };

    const vectorStoreConfig = {
        postgresConnectionOptions: postgresConfig,
        tableName: 'documents_confluence',
        columns: {
            idColumnName: 'id',
            vectorColumnName: 'vector',
            contentColumnName: 'content',
            metadataColumnName: 'metadata',
        },
    };

    const vectorStore = await PGVectorStore.initialize(new OpenAIEmbeddings(openAIEmbeddingsParams), vectorStoreConfig);

    // Create a new record manager
    const recordManagerConfig = {
        postgresConnectionOptions: postgresConfig,
        tableName: 'record_manager_records',
    };

    const recordManager = new PostgresRecordManager('confluence', recordManagerConfig);

    // Create the schema if it doesn't exist
    await recordManager.createSchema();

    const confluenceLoaderParams: ConfluencePagesLoaderParams = {
        baseUrl: 'REDACTED',
        rootPageId: '2347204666',
        spaceKey: 'EN',
        username: confluenceUser,
        accessToken: confluenceAccessToken,
    };
    const confluenceLoader = new ConfluencePagesLoader(confluenceLoaderParams);

    const docs = await confluenceLoader.loadAndSplit();

    try {
        const report = await index({
            docsSource: docs,
            recordManager,
            vectorStore,
            options: {
                cleanup: 'full',
                sourceIdKey: 'id',
            },
        });
        console.log(report);
        console.log('done!');
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
```

### Error Message and Stack Trace (if applicable)

```
error: duplicate key value violates unique constraint "documents_confluence_pkey"
    at /Users/michael/beamery/canx-tools/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PGVectorStore.addVectors (/Users/michael/beamery/canx-tools/node_modules/@langchain/community/dist/vectorstores/pgvector.cjs:331:17)
    at index (/Users/michael/beamery/canx-tools/node_modules/langchain/dist/indexes/indexing.cjs:229:13)
    at main (/Users/michael/beamery/canx-tools/apps/index-sources/src/main.ts:63:24) {
  length: 260,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(63ccb6a2-754d-5596-aeb6-e1f5d09e1398) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'documents_confluence',
  column: undefined,
  dataType: undefined,
  constraint: 'documents_confluence_pkey',
  file: 'nbtinsert.c',
  line: '664',
  routine: '_bt_check_unique'
}

Error: Error inserting: duplicate key value violates unique constraint "documents_confluence_pkey"
    at PGVectorStore.addVectors (/Users/michael/beamery/canx-tools/node_modules/@langchain/community/dist/vectorstores/pgvector.cjs:335:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at index (/Users/michael/beamery/canx-tools/node_modules/langchain/dist/indexes/indexing.cjs:229:13)
    at main (/Users/michael/beamery/canx-tools/apps/index-sources/src/main.ts:63:24)
```

### Description

I'm trying to use pgvector, with langchain's provided record manager and indexer. I'm using a customised loader to load in pages from the confluence API.

I have had a really hard time trying to recreate this with mocked data. However consistently when loading from the confluence API, after first indexing all documents successfully, then modifying one page in confluence, publishing it and running a full index again, the second one crashes as it is trying to insert a document which already exists.

As far as I can see, the postgres query which is used for the `exists` method is returning the results out of order. These results are then returned as boolean values, and so some documents are incorrectly inserted when they should be skipped. this results in an error due to duplicate IDs.

### System Info

```
{
"@langchain/community": "^0.0.41",
    "@langchain/core": "^0.1.48",
    "@langchain/openai": "^0.0.22",
    "langchain": "^0.1.28"
}
```

node v20.11.1
yarn v1.22.22
ankane/pgvector:latest
MacOS 14.4

**Comment by arrested-developer** [comment]
@dosu-bot I have validated that the res.rows response from postgres is correct, in that it correctly identifies which rows have a key that already exists. However it is in an order which is not consistent with the array of `keys` provided to the `exists` method. 

I would suggest, for safety, mapping over the `keys` array and using the data from the postgres query response to produce the boolean value which corresponds to each key.

**Comment by arrested-developer** [comment]
@dosu-bot I like the suggestion of somehow better preserving order in the postgres query

ideally the values of the ordered keys would be escaped. this also does not produce a valid query, for me it produced the following error:

```
error: function return row and query-specified return row do not match
    at /Users/michael/beamery/canx-tools/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgresRecordManager.exists (/Users/michael/beamery/canx-tools/node_modules/@langchain/community/dist/indexes/postgres.cjs:137:21)
    at index (/Users/michael/beamery/canx-tools/node_modules/langchain/dist/indexes/indexing.cjs:205:29)
    at main (/Users/michael/beamery/canx-tools/apps/index-sources/src/main.ts:63:24) {
  length: 194,
  severity: 'ERROR',
  code: '42804',
  detail: 'Returned type unknown at ordinal position 1, but query expects text.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'execSRF.c',
  line: '964',
  routine: 'tupledesc_match'
}
```

**Comment by MJDeligan** [comment]
Hey @arrested-developer ,

Thanks for bringing this up! You're right that the order is not preserved. Curiously this has not really come up for me, but I can reproduce it.

I'm going to do some more testing (also for performance), but something like the following query should work:

```sql
WITH ordered_keys AS (
    SELECT * FROM unnest(ARRAY[${arrayPlaceholders}]) WITH ORDINALITY as t(key, o)
)
SELECT ok.key, (r.key IS NOT NULL) 
FROM ordered_keys ok 
LEFT JOIN ${this.finalTablename} r 
ON r.key = ok.key 
AND namespace = $1
ORDER BY ok.o;
```

Might have to compare with doing the order in post-processing to see if it's faster than pure SQL.

**Comment by macnibblet** [comment]
@MJDeligan I'm experiencing the same issue so please share if you find a solution!

**Comment by arrested-developer** [comment]
@MJDeligan query needed a little cleaning up - specifically the casing on `this.finalTableName` and the column name `ex`

```
WITH ordered_keys AS (
    SELECT * FROM unnest(ARRAY[${arrayPlaceholders}]) WITH ORDINALITY as t(key, o)
)
SELECT ok.key, (r.key IS NOT NULL) ex
FROM ordered_keys ok 
LEFT JOIN ${this.finalTableName} r 
ON r.key = ok.key 
AND namespace = $1
ORDER BY ok.o;
```

This seems to be working nicely for me, the postgres response appears to be in order now. Thanks!

I'm happy to contribute to testing/raising a PR if you like - let me know.

**Comment by MJDeligan** [comment]
Sorry for the delay. Sure that would be great!
