### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'additional_kwargs')

### ISSUE THREAD

**Issue by ptesny** [langchain-ai/langchainjs#4933]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const { ChatMistralAI } = require( "@langchain/mistralai" );
var lc_core = require(  "@langchain/core/messages" );

if (req.body.stream) {

      const model = new ChatMistralAI({apiKey: MistralClientModule.apiKey,modelName: req.body.model, });
      console.log('lc_core: ', lc_core)
      const response = await model.stream(new lc_core.ChatMessage(req.body.messages.content, false));

      return response;
}

```

### Error Message and Stack Trace (if applicable)

```
lc_core: {
BaseMessage: [class BaseMessage extends Serializable],
BaseMessageChunk: [class BaseMessageChunk extends BaseMessage],
HumanMessage: [class HumanMessage extends BaseMessage],
HumanMessageChunk: [class HumanMessageChunk extends BaseMessageChunk],
AIMessage: [class AIMessage extends BaseMessage],
AIMessageChunk: [class AIMessageChunk extends BaseMessageChunk],
SystemMessage: [class SystemMessage extends BaseMessage],
SystemMessageChunk: [class SystemMessageChunk extends BaseMessageChunk],
FunctionMessage: [class FunctionMessage extends BaseMessage],
FunctionMessageChunk: [class FunctionMessageChunk extends BaseMessageChunk],
ToolMessage: [class ToolMessage extends BaseMessage],
ToolMessageChunk: [class ToolMessageChunk extends BaseMessageChunk],
ChatMessage: [class ChatMessage extends BaseMessage],
isBaseMessage: [Function: isBaseMessage],
isBaseMessageChunk: [Function: isBaseMessageChunk],
coerceMessageLikeToMessage: [Function: coerceMessageLikeToMessage],
ChatMessageChunk: [class ChatMessageChunk extends BaseMessageChunk],
getBufferString: [Function: getBufferString],
mapStoredMessageToChatMessage: [Function: mapStoredMessageToChatMessage],
mapStoredMessagesToChatMessages: [Function: mapStoredMessagesToChatMessages],
mapChatMessagesToStoredMessages: [Function: mapChatMessagesToStoredMessages]
}
TypeError: Cannot read properties of undefined (reading 'additional_kwargs')
at new BaseMessage (/usr/src/app/function/node_modules/@langchain/core/dist/messages/index.cjs:57:21)
at new ChatMessage (/usr/src/app/function/node_modules/@langchain/core/dist/messages/index.cjs:441:9)
at mistralai_api (/usr/src/app/function/handler.js:68:53)
```

### Description

Trying to use @langchain/mistralai as a wrapper over the @mistralai/mistralai nodejs client.
Worth mentioning, the @mistralai/mistralai client is working fine....
I have tried to align the versions of @langchain/core using the caret notation in package.json; 
I've tried to use `ChatMessage`, `HumanMessage` and `BaseMessage` as well. 
Always the same error. Thank you

### System Info

  * nodejs version 18
  * package.json
```
{ 
  "name": "mistral-gagnant",
  "version": "1.1.0",

   "dependencies": {
    "axios": "latest",
    "qs":"latest",
    "util": "latest",
    "cookie": "latest", 
    "btoa": "latest",         
    "lodash": "latest",    
    "@kubernetes/client-node": "latest",
    "@mistralai/mistralai": "latest",
    "@langchain/mistralai": "latest",
    "@langchain/core": "latest"
  },
  "devDependencies": {
    "cheerio": "latest"
  }  
}
```

**Comment by ptesny** [comment]
I have tried to use the code snippet from https://www.npmjs.com/package/@langchain/mistralai#streaming; it is quite different from the code samples above
