### ISSUE TITLE
The sql generated using the package langchain/chains/sql_db is incorrect

### ISSUE THREAD

**Issue by Johnsonliuz** [langchain-ai/langchainjs#4977]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:
```js
const { AzureChatOpenAI } = require("@langchain/azure-openai");
const { createSqlQueryChain } = require("langchain/chains/sql_db");
const { SqlDatabase } = require("langchain/sql_db");
const { DataSource } = require("typeorm");

const datasource = new DataSource({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "admin",
    database: "students",
})

const llm = new AzureChatOpenAI({
    azureOpenAIEndpoint: 'https://xxxx.openai.azure.com/',
    azureOpenAIApiKey: 'xxxx',
    azureOpenAIApiDeploymentName: 'gpt-35-turbo',
    modelName: 'gpt-35-turbo',
    temperature: 0
});


async function doSomething() {

    const db = await SqlDatabase.fromDataSourceParams({
        appDataSource: datasource,
    });

    const chain = await createSqlQueryChain({
        llm,
        db,
        dialect: "mysql",
    });
    const response = await chain.invoke({
        question: "I want to know everyone's test scores.",
    });

    console.log("db run result", await db.run(response));
}

doSomething();
```

### Error Message and Stack Trace (if applicable)

```
/Users/liuqiangsen/Documents/company/useLangChain/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165
                        return fail(new QueryFailedError_1.QueryFailedError(query, parameters, err));
                                    ^

QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': 
name score
Alex 100
Alice 70
Jack 75
Answer: Alex scored 100, Alice scored 70' at line 2
    at Query.<anonymous> (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.<anonymous> (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/Connection.js:88:28) {
  query: 'SELECT `name`, `score` FROM `students`\n' +
    'SQLResult: \n' +
    'name score\n' +
    'Alex 100\n' +
    'Alice 70\n' +
    'Jack 75\n' +
    'Answer: Alex scored 100, Alice scored 70, and Jack scored 75 on their tests.',
  parameters: undefined,
  driverError: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': 
  name score
  Alex 100
  Alice 70
  Jack 75
  Answer: Alex scored 100, Alice scored 70' at line 2
      at Sequence._packetToError (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      --------------------
      at Protocol._enqueue (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/mysql/lib/Connection.js:198:25)
      at /Users/liuqiangsen/Documents/company/useLangChain/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:154:36
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': \n" +
      'name score\n' +
      'Alex 100\n' +
      'Alice 70\n' +
      'Jack 75\n' +
      "Answer: Alex scored 100, Alice scored 70' at line 2",
    sqlState: '42000',
    index: 0,
    sql: 'SELECT `name`, `score` FROM `students`\n' +
      'SQLResult: \n' +
      'name score\n' +
      'Alex 100\n' +
      'Alice 70\n' +
      'Jack 75\n' +
      'Answer: Alex scored 100, Alice scored 70, and Jack scored 75 on their tests.'
  },
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': \n" +
    'name score\n' +
    'Alex 100\n' +
    'Alice 70\n' +
    'Jack 75\n' +
    "Answer: Alex scored 100, Alice scored 70' at line 2",
  sqlState: '42000',
  index: 0,
  sql: 'SELECT `name`, `score` FROM `students`\n' +
    'SQLResult: \n' +
    'name score\n' +
    'Alex 100\n' +
    'Alice 70\n' +
    'Jack 75\n' +
    'Answer: Alex scored 100, Alice scored 70, and Jack scored 75 on their tests.'
}

Node.js v20.11.1
```

### Description

My database has five pieces of information, and the name of the table is students
| id | name | score |
|--------|--------|--------|
| 1 | Alex | 100 |
| 2 | Alice | 70 |
| 3 | Jack | 75 |
| 4 | Ophelia | 0 |
| 5 | Zack | 60 | 

When I get the correct sql syntax through "createSqlQueryChain" in "langchain/chains/sql_db", it should be
```
sql: 'SELECT `name`, `score` FROM `students`'
```

But what I got was
```
  sql: 'SELECT `name`, `score` FROM `students`\n' +
    'SQLResult: \n' +
    'name score\n' +
    'Alex 100\n' +
    'Alice 70\n' +
    'Jack 75\n' +
    'Answer: Alex scored 100, Alice scored 70, and Jack scored 75 on their tests.'
```

<img width="587" alt="截圖 2024-04-05 01 25 15" src="https://github.com/langchain-ai/langchainjs/assets/56908475/c88b3da8-9992-471d-ac22-0b2b323813a9">

It was pieced together with some information obtained after searching, resulting in the information I finally got being incorrect.

### System Info

Node.js v20.11.1
"@langchain/azure-openai": "^0.0.6",
"@langchain/core": "^0.1.53",
"langchain": "^0.1.31",
"mysql": "^2.18.1",
"typeorm": "^0.3.20"

**Comment by Johnsonliuz** [comment]
If I replace the question with
```js
     const response = await chain.invoke({
         question: "I want to know alex test scores.",
     });
```
Correct sql syntax can be obtained
```
sql: SELECT score FROM students WHERE name = 'Alex' LIMIT 5;
```
I'm not sure what caused it

-----------------------

I found that sometimes the following code fails to properly filter out text that shouldn't appear in SQL strings. Therefore, I attempted to make some adjustments to node_modules/langchain/dist/chains/sql_db/sql_db_chain.cjs, keeping only the string before SQLResult, which seems to yield better results. Here's the code before and after the adjustment:

Before adjustment:
```js
const strip = (text) => {
    // Replace escaped quotes with actual quotes
    let newText = testNewText.replace(/\\"/g, '"').trim();
    // Remove wrapping quotes if the entire string is wrapped in quotes
    if (newText.startsWith('"') && newText.endsWith('"')) {
        newText = newText.substring(1, newText.length - 1);
    }
    return newText;
};
```

After adjustment:
```js
const strip = (text) => {
    // Replace escaped quotes with actual quotes
    let match = text.match(/(.+)(?=SQLResult)/s);
    let testNewText = match ? match[0] : text;
    let newText = testNewText.replace(/\\"/g, '"').trim();
    // Remove wrapping quotes if the entire string is wrapped in quotes
    if (newText.startsWith('"') && newText.endsWith('"')) {
        newText = newText.substring(1, newText.length - 1);
    }
    return newText;
};
```

The issue should now be resolved, and the statement "I want to know everyone's test scores." should work correctly.
I hope this issue can be fixed.
Thanks.
