### ISSUE TITLE
parseResult on OpenAIFunctionsAgentOutputParser only works on ChatGeneration output

### ISSUE THREAD

**Issue by hemanth** [langchain-ai/langchainjs#5095]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```javascript
import "npm:duck-duck-scrape"
import { DuckDuckGoSearch } from "npm:@langchain/community/tools/duckduckgo_search";
import { ChatOpenAI } from "npm:@langchain/openai";
import type { ChatPromptTemplate } from "npm:@langchain/core/prompts";

import { pull } from "npm:langchain/hub";
import { AgentExecutor, createOpenAIFunctionsAgent } from "npm:langchain/agents";

const tools = [new DuckDuckGoSearch({ maxResults: 1 })];

const prompt = await pull<ChatPromptTemplate>(
  "hwchase17/openai-functions-agent"
);

const agent = await createOpenAIFunctionsAgent({
  llm:model,
  tools,
  prompt,
});
const agentExecutor = new AgentExecutor({
  agent,
  tools,
});
const result = await agentExecutor.invoke({
  input: "Who is Hemanth HM?",
});

console.log(result);
```

### Error Message and Stack Trace (if applicable)

```
Stack trace:
Error: parseResult on OpenAIFunctionsAgentOutputParser only works on ChatGeneration output
    at OpenAIFunctionsAgentOutputParser.parseResult (file:///deno/npm/registry.npmjs.org/langchain/0.1.30/dist/agents/openai_functions/output_parser.js:58:15)
    at OpenAIFunctionsAgentOutputParser._callWithConfig (file:///deno/npm/registry.npmjs.org/@langchain/core/0.1.53/dist/output_parsers/base.js:39:72)
    at OpenAIFunctionsAgentOutputParser._callWithConfig (file:///deno/npm/registry.npmjs.org/@langchain/core/0.1.53/dist/runnables/base.js:193:33)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async OpenAIFunctionsAgentOutputParser._streamIterator (file:///deno/npm/registry.npmjs.org/@langchain/core/0.1.53/dist/runnables/base.js:146:9)
    at async OpenAIFunctionsAgentOutputParser.transform (file:///deno/npm/registry.npmjs.org/@langchain/core/0.1.53/dist/runnables/base.js:362:9)
    at async RunnableSequence._streamIterator (file:///deno/npm/registry.npmjs.org/@langchain/core/0.1.53/dist/runnables/base.js:1098:30)
 ```

### Description

Trying agents with gemma

### System Info

`v0.1.53`
`mac`
`deno@latest`

**Comment by hemanth** [comment]
Fetched the model from `HuggingFaceInference`

**Comment by jacoblee93** [comment]
This is by design, this output parser is specifically tuned for OpenAI chat models with function calling. Anything else will be a bit fluky.

**Comment by jacoblee93** [comment]
Try this one:

https://js.langchain.com/docs/modules/agents/agent_types/tool_calling

Only works with providers that support tool calling (so no Ollama yet!)

**Comment by 03bgls25** [comment]
I'm working with Langchain.js v2 and trying to use the Ollama LLM to build a custom tool and agent using the createToolCallingAgent. However, I am encountering the following error:

`Error: parseResult on ToolCallingAgentOutputParser only works on ChatGeneration output`

I've tried to follow the documentation and create a simple custom tool that adds 2 to the input number. My full code is below:

```
import { tool } from "@langchain/core/tools";
import { z } from "zod";
import { Ollama } from "@langchain/ollama";
import { ChatPromptTemplate,  MessagesPlaceholder } from "@langchain/core/prompts";
import { createToolCallingAgent } from "langchain/agents";
import { AgentExecutor } from "langchain/agents";

const llm = new Ollama({
    model: "llama3",
    temperature: 0.7,
});

const magicTool = tool(
    async (input) => {
        return `${ input + 2}`;
    },
    {
        name: "magic_function",
        description: "Applies a magic function to an input",
        schema: z.object({
            input: z.number(),
        })
    }
);

const tools = [magicTool];

// Prompt Template
const prompt = ChatPromptTemplate.fromMessages([
    ["system", "You are a helpful assistant called iHelp"],
    ["placeholder", "{chat_history}"],
    ["human", "{input}"],
    ["placeholder", "{agent_scratchpad}"],
]);

const agent = createToolCallingAgent({
    llm,
    tools,
    prompt,
});

const agentExecutor = new AgentExecutor({
    agent,
    tools,
});

const query = "What is the value of magic_function(3)?";

await agentExecutor.invoke({ input: query });
```

**Comment by jacoblee93** [comment]
Use `ChatOllama` with a chat tuned model - tool calling doesn't work with text in/text out LLMs:

https://js.langchain.com/docs/concepts#functiontool-calling
