### ISSUE TITLE
Error: Single '}' in template

### ISSUE THREAD

**Issue by GoldenDragon0710** [langchain-ai/langchainjs#5308]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const getReply = async (messages, namespaceId) => {
  let user_question = messages.pop();
  user_question = JSON.stringify(user_question.content);
  let chat_history = JSON.stringify(messages);
  try {
    const pinecone = new Pinecone({
      apiKey: process.env.PINECONE_API_KEY,
    });
    const pineconeIndex = pinecone.Index(process.env.PINECONE_INDEX);

    const vectorStore = await PineconeStore.fromExistingIndex(
      new OpenAIEmbeddings(),
      { pineconeIndex, namespace: namespaceId }
    );

    let systemPrompt = process.env.ANALYZE_SUMMARIZE_PROMPT.replace(
      /\\n/g,
      "\n"
    );

    const CONDENSE_PROMPT =
      PromptTemplate.fromTemplate(`Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

        Chat History:
        {chat_history}
        Human: {question}
        Standalone question:`);

    const QA_PROMPT = PromptTemplate.fromTemplate(
      `You are a legal assistant bot. The bot's output must strictly follow this format:
          \`\`\`
            {result: true, response: {name: <xxx>, gender: <xxx>}}
          \`\`\`
        The bot must not deviate from this output JSON style under any circumstances to ensure consistency and clarity in user interactions.
        Replace <xxx> with bot's response.
      =========
      Question: {question}
      =========
      {context}
      =========
      Answer in Markdown: `
    );

    const questionGenerator = new LLMChain({
      llm: new ChatOpenAI({
        temperature: 0,
        openAIApiKey: process.env.OPENAI_API_KEY,
      }),
      prompt: CONDENSE_PROMPT,
    });

    const llm = new ChatOpenAI({
      modelName: "gpt-4-turbo-preview",
      temperature: 0,
      openAIApiKey: process.env.OPENAI_API_KEY,
    });

    const docChain = loadQAChain(llm, {
      prompt: QA_PROMPT,
      type: "stuff",
    });

    const chain = new ConversationalRetrievalQAChain({
      retriever: vectorStore.asRetriever(),
      returnSourceDocuments: true,
      combineDocumentsChain: docChain,
      questionGeneratorChain: questionGenerator,
    });

    const result = await chain.invoke({
      question: user_question,
      chat_history,
    });
    console.log(result);

    return result;
  } catch (err) {
    console.log(err);
  }
};
```
When running this code, I received this error: `Error: Single '}' in template.`
How to fix this error?

### Error Message and Stack Trace (if applicable)

Error: Single '}' in template.
```
at Object.parseFString [as f-string] (D:\Working\backend\node_modules\@langchain\core\dist\prompts\template.cjs:45:19)
at parseTemplate (D:\Working\backend\node_modules\@langchain\core\dist\prompts\template.cjs:103:99)
at PromptTemplate.fromTemplate (D:\Working\backend\node_modules\@langchain\core\dist\prompts\prompt.cjs:99:41)
at getReply (D:\Working\backend\controllers\analyze.controller.js:96:38)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async exports.analyzation (D:\Working\backend\controllers\analyze.controller.js:49:22)
```
"undefined" is not valid JSON

### Description

Now I am trying to generate the response from datasets I already trained into Pinecone by using Langchain

### System Info

Platform: Windows
Node version: v21.2.0

**Comment by bracesproul** [comment]
The issue lies in the use of your JSON prompting --side note, you should be using tool calling instead of prompting to get JSON, this will get you better results.

Since we use curly braces for template string variables, you must escape any additional curly braces that are not intended to be an input variable with another curly brace.

You should replace this:
```
{result: true, response: {name: <xxx>, gender: <xxx>}}
```

with an escaped version like this:
```
{{result: true, response: {{name: <xxx>, gender: <xxx>}}}}
```

Then, if you inspect the langsmith trace, you can see the escaping curly braces were removed before the prompt was sent to the LLM API. See [here](https://smith.langchain.com/public/9bd3132f-217b-4e8e-82b6-e15a68d94bb1/r) for an example
