### ISSUE TITLE
Add support for GPT-4o

### ISSUE THREAD

**Issue by ahm750** [langchain-ai/langchainjs#5346]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import { OpenAIEmbeddings, ChatOpenAI } from "@langchain/openai";
import { ConversationalRetrievalQAChain } from "langchain/chains";
import { PromptTemplate } from "@langchain/core/prompts";
import {
  HumanMessage,
  AIMessage,
  SystemMessage,
} from "@langchain/core/messages";

const qaGeneratorModel = new ChatOpenAI({
  modelName: "gpt-4o",
  temperature: 0,
  streaming: false,
});

const baseModel = new ChatOpenAI({
  temperature: temperature,
  modelName: "gpt-4o",
  streaming: true,
  callbacks: [
    {
      async handleLLMNewToken(token) {
        callback(token);
      },
      async handleLLMEnd(output) {
        // End of stream
        callback("===END===");
      },
    },
  ],
});

let options = {
  returnSourceDocuments: true,
  questionGeneratorChainOptions: {
    llm: qaGeneratorModel,
    template: CONDENSE_PROMPT_STRING,
  },
  qaChainOptions: {
    type: "stuff",
    prompt: QA_PROMPT,
    verbose: QA_CHAIN_VERBOSE,
  },
};

let chain = ConversationalRetrievalQAChain.fromLLM(
  baseModel,
  vectorstore.asRetriever(),
  options,
);

const response = await chain.call({
  question: sanitizedText,
  chat_history: chatHistoryParsedArray,
});
```

### Error Message and Stack Trace (if applicable)

Failed to calculate number of tokens, falling back to approximate count Error: Unknown model
    at getEncodingNameForModel (file:///node_modules/js-tiktoken/dist/chunk-HXW345QN.js:224:13)
    at encodingForModel (file:///node_modules/@langchain/core/dist/utils/tiktoken.js:19:24)
    at ChatOpenAI.getNumTokens (file:///node_modules/@langchain/core/dist/language_models/base.js:174:40)
    at file:///node_modules/@langchain/openai/dist/chat_models.js:642:42
    at Array.map (<anonymous>)
    at ChatOpenAI.getNumTokensFromMessages (file:///node_modules/@langchain/openai/dist/chat_models.js:641:60)
    at ChatOpenAI.getEstimatedTokenCountFromPrompt (file:///node_modules/@langchain/openai/dist/chat_models.js:589:34)
    at ChatOpenAI._generate (file:///node_modules/@langchain/openai/dist/chat_models.js:536:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
Failed to calculate number of tokens, falling back to approximate count Error: Unknown model
    at getEncodingNameForModel (file:///node_modules/js-tiktoken/dist/chunk-HXW345QN.js:224:13)
    at encodingForModel (file:///node_modules/@langchain/core/dist/utils/tiktoken.js:19:24)
    at ChatOpenAI.getNumTokens (file:///node_modules/@langchain/core/dist/language_models/base.js:174:40)
    at file:///node_modules/@langchain/openai/dist/chat_models.js:643:42
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ChatOpenAI.getNumTokensFromMessages (file:///node_modules/@langchain/openai/dist/chat_models.js:641:33)
    at async ChatOpenAI.getEstimatedTokenCountFromPrompt (file:///node_modules/@langchain/openai/dist/chat_models.js:589:23)
    at async ChatOpenAI._generate (file:///node_modules/@langchain/openai/dist/chat_models.js:536:38)
    at async Promise.allSettled (index 0)
Failed to calculate number of tokens, falling back to approximate count Error: Unknown model
    at getEncodingNameForModel (file:///node_modules/js-tiktoken/dist/chunk-HXW345QN.js:224:13)
    at encodingForModel (file:///node_modules/@langchain/core/dist/utils/tiktoken.js:19:24)
    at ChatOpenAI.getNumTokens (file:///node_modules/@langchain/core/dist/language_models/base.js:174:40)
    at file:///node_modules/@langchain/openai/dist/chat_models.js:623:35
    at Array.map (<anonymous>)
    at ChatOpenAI.getNumTokensFromGenerations (file:///node_modules/@langchain/openai/dist/chat_models.js:617:64)
    at ChatOpenAI._generate (file:///node_modules/@langchain/openai/dist/chat_models.js:537:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async ChatOpenAI._generateUncached (file:///node_modules/@langchain/core/dist/language_models/chat_models.js:114:25)

### Description

Hi, OpenAI just released GPT-4o and langchain needs to be updated to support this model. At the moment, it throws the above error when using the new model.

### System Info

Langchain: 0.1.37
Platform: macos
Node: 21.7.3
Yarn: 4.2.2

**Comment by jeasonnow** [comment]
It seems that js-Tiktoken does not yet support gpt-4o, but I found the implementation in their repository:
https://github.com/dqbd/tiktoken/blob/a7cce9922b10bca567be8453f1ef0489428fa02f/js/src/core.ts#L277C4-L280C6

But they haven’t released a new version yet, I will submit a pr to solve this problem after they release it

**Comment by jeasonnow** [comment]
#5354 
This is the same issue, please wait for the new version of langchainjs.

**Comment by ahm750** [comment]
When would the update be released?

**Comment by sanjiv-upgiant** [comment]
NEED THE UPDATE TO BE RELEASED........

**Comment by ahm750** [comment]
@jacoblee93 Any ETA on the new release?

**Comment by jacoblee93** [comment]
Hey the fix should be live if you update to the latest @langchain/core! The tiktoken dep is there.

**Comment by jacoblee93** [comment]
https://x.com/philippec_me/status/1790142477141147884?s=46&t=pBOviutddr6W7u_gV0VQqg

**Comment by maikosantos** [comment]
Hi, 

Now, It's working for me!

Thanks!

**Comment by ahm750** [comment]
Thank you, it works now!

**Comment by adeenrabbani1** [comment]
guys I have only installed langchain npm. does this install langchain core?

**Comment by jacoblee93** [comment]
> guys I have only installed langchain npm. does this install langchain core?

It does as a dependency, yes. See this guide:

https://js.langchain.com/v0.2/docs/how_to/installation/#installing-integration-packages

**Comment by adeenrabbani1** [comment]
@jacoblee93 even though I have updated to version 0.2.6, I still get weird context length errors which are not valid, as the context len for gpt-4o is 128k.

I have also raise an issue here. [https://github.com/langchain-ai/langchainjs/issues/5888](url)

it seems to start at version of langchain 0.1.37
