### ISSUE TITLE
DOC:  For QA how to pass chat history in stream mode and also get source with rag chain?

### ISSUE THREAD

**Issue by djaffer** [langchain-ai/langchainjs#5569]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

  Getting this error
TypeError: str.normalize is not a function
    at processInput (/app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/tokenizer/index.js:65:26)
    at Tokenizer.encode (/app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/tokenizer/index.js:87:17)
    at /app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/index.js:128:86
    at Array.map (<anonymous>)
    at UniversalSentenceEncoder.<anonymous> (/app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/index.js:128:44)
    at step (/app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/index.js:48:23)
    at Object.next (/app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/index.js:29:53)
    at /app/node_modules/@tensorflow-models/universal-sentence-encoder/dist/index.js:23:71
    at new Promise (<anonymous>)
 
    const questionPrompt = PromptTemplate.fromTemplate(
    ```
  ----------------
  CONTEXT: {context}
  ----------------
  CHAT HISTORY: {chatHistory}
  ----------------
  QUESTION: {question}
  ----------------
  Helpful Answer:`
      );

      const ragChainFromDocs = RunnableSequence.from([
        {
          question: (input) => input.question,
          chatHistory: (input) => input.chatHistory ?? '',
          context: async (input) => {
            const relevantDocs = await retriever.invoke(input.question);

            const serialized = formatDocumentsAsString(relevantDocs);
            return serialized;
          },
        },
        questionPrompt,
        this.llm,
        new StringOutputParser(),
      ]);

      let ragChainWithSource = new RunnableMap({
        steps: {
          context: retriever,
          question: new RunnablePassthrough(),
        },
      });
      ragChainWithSource = ragChainWithSource.assign({
        answer: ragChainFromDocs,
      });
      
      
      ragChainWithSource.invoke({question,chatHistory}) doesn't work
      

### Idea or request for content:

_No response_

**Comment by djaffer** [comment]
any update?
