### ISSUE TITLE
Is the SqlToolkit agent toolkit only supported for OpenAI LLMs?

### ISSUE THREAD

**Issue by mikebars** [langchain-ai/langchainjs#563]
I see that in the `SqlToolkit` constructor it creates a `QueryCheckerTool` without arguments:
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/agents/agent_toolkits/sql/sql.ts#L29

Which causes the `else` branch of the `QueryCheckerTool` constructor to run:
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/agents/tools/sql.ts#L104

Which then creates the default `OpenAI` LLMChain

Here's a reproduction of the issue (attempting to use the `HuggingFaceInference` LLM):
- https://gist.github.com/mikebars/3c0fad5f9e3cd1cedd31e3fc2e489ae4

And here is a patch I made that appears to allow the functionality to progress further:
- https://gist.github.com/mikebars/c4aca3595c03e1da1ba71e3b0e4edd53

And here is my patched code that is able to reach a different error state:
- https://gist.github.com/mikebars/64951dd57e771bc3a46fec961e117866

However, I still get an error as output, which makes me think perhaps these cases are not yet supported:
```
Error: Could not parse LLM output: Action: list-tables-sql
Action Input:
Observation: a list of tables
Th
    at ZeroShotAgent.extractToolAndInput (file:///home/user/langchain-projects/projects/langchain-test/node_modules/langchain/src/agents/mrkl/index.ts:111:13)
    at ZeroShotAgent._plan (file:///home/user/langchain-projects/projects/langchain-test/node_modules/langchain/src/agents/agent.ts:159:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentExecutor._call (file:///home/user/langchain-projects/projects/langchain-test/node_modules/langchain/src/agents/executor.ts:75:22)
    at async AgentExecutor.call (file:///home/user/langchain-projects/projects/langchain-test/node_modules/langchain/src/chains/base.ts:94:22)
```

**Comment by hkd987** [comment]
I’ve been running into the same issues as you and came to mostly the same conclusions as you. I’ve found this comment on the[langchain](https://github.com/hwchase17/langchain/issues/1358#issuecomment-1453262328) repo that makes me think so very custom fine tuning is going to be be needed to get a SQL agent with a huggingface model to work the way we want.

**Comment by hkd987** [comment]
I’m actually thinking of using OpenAI SQL Agent questions/answers and building a fine tuning data set, that I can then plug into a Huggingface model.

If you have any other ideas or find a better solution I’d love to hear about it.
