### ISSUE TITLE
Issue with RemoteRunnable and custom 'LangServe' endpoint...   The issue seems to be in reviving the results of my BaseMessages

### ISSUE THREAD

**Issue by mcgear** [langchain-ai/langchainjs#5791]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:
```
console.log(JSON.parse(JSON.stringify(new HumanMessage('This is a test'))));
```

### Error Message and Stack Trace (if applicable)

Not so much an error message, as i don't think i am getting the right ouput from serialization:
C:\ProgramData\chocolatey\lib\deno\deno.exe run --config ./deno.jsonc --inspect-wait --inspect-brk=127.0.0.1:53819 --allow-all .\main.ts
Initialized esbuild with standard build.
Unable to connect to the EaC service, falling back to local config.
Initializing DenoKV at ./denoKv/thinky.db
Loading DenoKV instance for ./denoKv/thinky.db
Initializing DenoKV at ./denoKv/thinky.db
Loading DenoKV instance for ./denoKv/thinky.db
Inititialized DenoKV database: ./denoKv/thinky.db
Inititialized DenoKV database: ./denoKv/thinky.db
projectGraph: 0 ms
Timer 'azureContainerCheck' already exists
azureContainerCheck: 0 ms
Timer 'azureContainerCheck' does not exist
circuits: 0 ms
thinky: 0 ms
appGraph: 0 ms
 🐙 EaC Runtime Ready 
	http://localhost:6132
{"lc":1,"type":"constructor","id":["langchain_core","messages","HumanMessage"],"kwargs":{"content":"This is a test","additional_kwargs":{},"response_metadata":{}}}
{lc: 1, type: 'constructor', id: Array(3), kwargs: {…}}

As you can see, the type is set to 'constructor':
"type":"constructor"

The issue is that when i look at the logic for RemoteRunnable:
https://github.com/langchain-ai/langchainjs/blob/9822a5c6d4a5e01b7f4746114696d81670c9331e/langchain-core/src/runnables/remote.ts#L259

It requires the 'type' to be the class name of the instance:
https://github.com/langchain-ai/langchainjs/blob/9822a5c6d4a5e01b7f4746114696d81670c9331e/langchain-core/src/runnables/remote.ts#L62

As you can see, the type is always constructor, so when the remote tries to unpack it, it see string 'constructor' instead of something like 'HumanMessage' or 'ToolMessageChunk'... So i feel like i am missing something in our attempt to replicate LangServe, in the attemp to provide our own hosts that can meet the RemoteRunnable interface

### Description

Maybe i put to much in the error message section...

### System Info

deno
https://github.com/fathym-deno/thinky-runtime

**Comment by mcgear** [comment]
Should i have to do this when using the built in message classes like HumanMessasge @dosu?

**Comment by mcgear** [comment]
The issue seems to be in the serialization toJSON implementation:
https://github.com/langchain-ai/langchainjs/blob/ac204f845ba4a94a8f446cfc5d3906ff776af858/langchain-core/src/load/serializable.ts#L211

It seems like this code needs to be updated to return the class name, or use the lc_name as the type, in order to match up with the revive logic in the RemoteRunnable.

**Comment by mcgear** [comment]
I'm now getting some issue from this line:
https://github.com/langchain-ai/langchainjs/blob/9822a5c6d4a5e01b7f4746114696d81670c9331e/langchain-core/src/runnables/remote.ts#L185

Reading the comment:
```
if (isSuperset(keys, new Set(["messages"]))) {
      // TODO: Start checking for type: ChatPromptValue and ChatPromptValueConcrete
      // when LangServe bug is fixed
      return new ChatPromptValue({
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        messages: obj.messages.map((msg: any) => revive(msg)),
      });
    }
    ```

I'm wondering what bug in LangServe is being referenced here, and how to deal with the error i am getting:

```
remote.js:162 Uncaught (in promise) TypeError: obj.messages.map is not a function
    at revive (remote.js:162:40)
    at innerRevive (remote.js:173:13)
    at Array.map (<anonymous>)
    at revive (remote.js:175:48)
    at innerRevive (remote.js:173:13)
    at Array.map (<anonymous>)
    at revive (remote.js:175:48)
    at innerRevive (remote.js:173:13)
    at Array.map (<anonymous>)
    at revive (remote.js:175:48)
```
