### ISSUE TITLE
Issue in ChatGroq chat_model.js (completionWithRetry function) returning null because it is not waiting for promise to finish

### ISSUE THREAD

**Issue by spanish25** [langchain-ai/langchainjs#6287]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    async completionWithRetry(request, options) {
        return this.caller.call(async () => this.client.chat.completions.create(request, options));
    }

### Error Message and Stack Trace (if applicable)

ERROR TypeError: Cannot use 'in' operator to search for 'usage' in null
    at ChatGroq.<anonymous> (chat_models.js:361:13)
    at Generator.next (<anonymous>)
    at fulfilled (chunk-5F2WBKE3.js?v=a40c21e6:69:24)
    at _ZoneDelegate.invoke (zone.js:365:28)
    at Object.onInvoke (core.mjs:15931:33)
    at _ZoneDelegate.invoke (zone.js:364:34)
    at _ZoneImpl.run (zone.js:111:43)
    at zone.js:2498:40
    at _ZoneDelegate.invokeTask (zone.js:398:33)
    at core.mjs:15616:55

### Description

The function should actually be

async completionWithRetry(request, options) {
        return this.caller.call(async () => await this.client.chat.completions.create(request, options));
    }

Because the await statement is missing, it is not waiting for the promise to resolve and hence returning the null pointer seen in the stacktrace. This works if I edit the Javascript file and add the await statement.

Please can you fix this?

### System Info

Windows
Node v20.15.0
"langchain": "^0.2.11",
"@langchain/community": "^0.2.21",
"@langchain/groq": "^0.0.15",

**Comment by juzarantri** [comment]
@jacoblee93 Can you please assign me this  issue to resolve?

**Comment by juzarantri** [comment]
@jacoblee93 Can you please assign me this issue to resolve?

**Comment by jacoblee93** [comment]
Thank you @juzarantri!

**Comment by juzarantri** [comment]
@jacoblee93 I am facing issue while installing **yarn install**. It is stuck at couchbase. This is the build log file. I tried to install openssl and all but I am failing to resolving since yesterday. Can you please help me here?

`# This file contains the result of Yarn building a package (couchbase@npm:4.4.2)
# Script name: install

info find VS using VS2019 (16.11.33529.622) found at:
info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
info find VS run with --verbose for detailed information
info TOOL Using Visual Studio 16 2019 generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   'C:\\Users\\Juzar\\Desktop\\langchainjs\\node_modules\\couchbase\\build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  couchbase_backtrace.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\deps\couchbase-cxx-client\core\platform\couchbase_backtrace.dir\Release\couchbase_backtrace.lib
  jsonsl.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\deps\couchbase-cxx-client\jsonsl.dir\Release\jsonsl.lib
  asio.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\deps\couchbase-cxx-client\Release\asio.lib
  fmt.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\_deps\fmt-build\Release\fmt.lib
  hdr_histogram_static.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\_deps\hdr_histogram-build\src\Release\hdr_histogram_static.lib
  llhttp_static.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\_deps\llhttp-build\Release\llhttp.lib
  snappy.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\_deps\snappy-build\Release\snappy.lib
  spdlog.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\_deps\spdlog-build\Release\spdlog.lib
  couchbase_cxx_client_static.vcxproj -> C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\deps\couchbase-cxx-client\Release\couchbase_cxx_client_static.lib
LINK : fatal error LNK1104: cannot open file 'OpenSSL::SSL.lib' [C:\Users\Juzar\Desktop\langchainjs\node_modules\couchbase\build\couchbase_impl.vcxproj]
ERR! OMG Process terminated: 1
`

**Comment by jacoblee93** [comment]
SEems it's something system level - are you able to install without peer deps?

**Comment by juzarantri** [comment]
Yes I too think its system level. Shall I switch to ubuntu and try? I am currently on windows. I am just running the command yarn install. By default I guess it skips peer dependencies
