### ISSUE TITLE
@langchain/aws Bug: ChatBedrockConverse fails when ToolMessage is returned after AI Message that has both content and tool_use

### ISSUE THREAD

**Issue by satoshim222** [langchain-ai/langchainjs#6349]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
...
const model = new ChatBedrockConverse({
  model: "anthropic.claude-3-haiku-20240307-v1:0",
  region: process.env.AWS_REGION,
  maxTokens: config.maxTokens,
  temperature: 0,
  streaming: true,
});

const retrieveDocumentsToolSchema = z.object({
  question: z.string().describe('The question asked by the human to search documents on.'),
});

const retrieve_documents_tool = tool(searchFunc, {
  name: 'document_retrieval',
  description: toolDescriptions,
  schema: retrieveDocumentsToolSchema,
});
const tools = [retrieve_documents_tool];

async function generatePrompt() {
  return ChatPromptTemplate.fromMessages([
      ['system', formattedInstructions],
      ['placeholder', '{chat_history}'],
      ['human', '{input}'],
      ['placeholder', '{agent_scratchpad}'],
    ]);
}

const agent = createToolCallingAgent({
  llm: model,
  tools,
  prompt: await generatePrompt(),
  streamRunnable: true,
});

const executor = new AgentExecutor({
  agent,
  tools,
  maxIterations: 3,
  verbose: true,
});

const eventStream = await executor.streamEvents(
  {
    input: userPrompt,
    chat_history: chatHistory,
  },
  { version: 'v2' },
);

...
```

### Error Message and Stack Trace (if applicable)

[31m[llm/error][39m [[90m1:chain:AgentExecutor > 10:chain:ToolCallingAgent > [1m15:llm:ChatBedrockConverse[22m[39m] [230ms] LLM run errored with error: "The number of toolResult blocks at messages.6.content exceeds the number of toolUse blocks of previous turn.\n\nValidationException: The number of toolResult blocks at messages.6.content exceeds the number of toolUse blocks of previous turn.\n    at de_ValidationExceptionRes (/var/task/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:1082:21)\n    at de_CommandError (/var/task/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:937:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/task/node_modules/@aws-sdk/client-bedrock-runtime/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /var/task/node_modules/@aws-sdk/client-bedrock-runtime/node_modules/@smithy/core/dist-cjs/index.js:165:18\n    at async /var/task/node_modules/@aws-sdk/client-bedrock-runtime/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /var/task/node_modules/@aws-sdk/client-bedrock-runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22\n    at async ChatBedrockConverse._streamResponseChunks (/var/task/node_modules/@langchain/aws/dist/chat_models.cjs:250:26)\n    at async ChatBedrockConverse._streamIterator (/var/task/node_modules/@langchain/core/dist/language_models/chat_models.cjs:93:34)\n    at async ChatBedrockConverse.transform (/var/task/node_modules/@langchain/core/dist/runnables/base.cjs:394:9)"

### Description

This issue seems to be similar to https://github.com/langchain-ai/langchainjs/issues/6173 but this seems to happen when the AI Message has both content and tool_use and toolMessage is constructed after calling the tool. 

The code that I have succeeds except for the time where tool_use AI message is returned with content.

Agent Executor verbose

```
{
    "messages": [
        [
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "SystemMessage"
                ],
                "kwargs": {
                    "content": "System Prompt...",
                    "additional_kwargs": {},
                    "response_metadata": {}
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "HumanMessage"
                ],
                "kwargs": {
                    "content": "How should I get started on this?",
                    "additional_kwargs": {},
                    "response_metadata": {}
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "AIMessage"
                ],
                "kwargs": {
                    "content": "",
                    "tool_calls": [
                        {
                            "name": "document_retrieval",
                            "args": {
                                "question": "How should I get started on this?"
                            },
                            "id": "0"
                        }
                    ],
                    "invalid_tool_calls": [],
                    "additional_kwargs": {},
                    "response_metadata": {}
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "ToolMessage"
                ],
                "kwargs": {
                    "tool_call_id": "0",
                    "content": "<context>...</context>",
                    "additional_kwargs": {},
                    "response_metadata": {}
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "AIMessage"
                ],
                "kwargs": {
                    "content": "Based on the search results, here are the key steps to get started ...",
                    "tool_calls": [],
                    "invalid_tool_calls": [],
                    "additional_kwargs": {},
                    "response_metadata": {}
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "HumanMessage"
                ],
                "kwargs": {
                    "content": "Can you give me a step by step?",
                    "additional_kwargs": {},
                    "response_metadata": {}
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "AIMessageChunk"
                ],
                "kwargs": {
                    "content": "Sure, here are the step-by-step instructions to get started:",
                    "additional_kwargs": {},
                    "response_metadata": {
                        "messageStart": {
                            "p": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL",
                            "role": "assistant"
                        },
                        "contentBlockStop": {
                            "contentBlockIndex": 0,
                            "p": "abcdefghijklmnopqrstuvwxyzABCDEFabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234"
                        },
                        "messageStop": {
                            "stopReason": "tool_use"
                        },
                        "metadata": {
                            "metrics": {
                                "latencyMs": 1289
                            },
                            "p": "abcdefghijklmnopqrstuvwxyzABCDEFG",
                            "usage": {
                                "inputTokens": 5462,
                                "outputTokens": 62,
                                "totalTokens": 5524
                            }
                        }
                    },
                    "tool_call_chunks": [
                        {
                            "name": "document_retrieval",
                            "id": "tooluse_UjZqr4HCQtqQepmSMIWptw",
                            "index": 1,
                            "type": "tool_call_chunk",
                            "args": "{\"question\": \"step by step instructions to get started\"}"
                        }
                    ],
                    "usage_metadata": {
                        "input_tokens": 5462,
                        "output_tokens": 62,
                        "total_tokens": 5524
                    },
                    "tool_calls": [
                        {
                            "name": "document_retrieval",
                            "args": {
                                "question": "step by step instructions to get started"
                            },
                            "id": "tooluse_UjZqr4HCQtqQepmSMIWptw",
                            "type": "tool_call"
                        }
                    ],
                    "invalid_tool_calls": []
                }
            },
            {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain_core",
                    "messages",
                    "ToolMessage"
                ],
                "kwargs": {
                    "tool_call_id": "tooluse_UjZqr4HCQtqQepmSMIWptw",
                    "content": "<context>...</context>",
                    "additional_kwargs": {
                        "name": "document_retrieval"
                    },
                    "response_metadata": {}
                }
            }
        ]
    ]
}
```

Error Message throws after awards

### System Info

Node v18.15.0

"@langchain/aws": "^0.0.6",
"@langchain/core": "^0.2.18",
"@langchain/community": "^0.2.20",

**Comment by jacoblee93** [comment]
@bracesproul

**Comment by satoshim222** [comment]
Hi, any updates here? Happy to debug or provide any more information necessary.

**Comment by baobo5625** [comment]
same here for 
"@langchain/aws": "^0.1.7",
"@langchain/core": "^0.3.40",

while calling claude 3.7

**Comment by phpmac** [comment]
Same experience

**Comment by baobo5625** [comment]
it seems pythong has fixed this one, but not for js 
https://python.langchain.com/api_reference/_modules/langchain_aws/chat_models/bedrock_converse.html

**Comment by jonathanfds** [comment]
is there any workaround for this ? I'm getting the same error when I use `streaming = true`
