### ISSUE TITLE
Request entity too large using loadSummarizationChain

### ISSUE THREAD

**Issue by yackinn** [langchain-ai/langchainjs#6354]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```ts

const summarizeChain = loadSummarizationChain(this.llm, {
      type: 'refine',
      verbose: false,
      questionPrompt: PromptTemplate.fromTemplate(summaryTemplate),
      refinePrompt: PromptTemplate.fromTemplate(summaryRefineTemplate),
    });
    
await summarizeChain.run(splitDocs
```

### Error Message and Stack Trace (if applicable)
```
Error: Failed to create run: 413 Request Entity Too Large <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

at raiseForStatus (..../node_modules/langsmith/dist/client.cjs:79:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Client.createRun (..../node_modules/langsmith/dist/client.cjs:570:9)
at Client.batchIngestRuns (..../node_modules/langsmith/dist/client.cjs:619:17)
at Client.drainAutoBatchQueue (..../node_modules/langsmith/dist/client.cjs:480:17)
```
### Description

I added these env variables.
```
LANGCHAIN_API_KEY=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
LANGCHAIN_ENDPOINT="https://eu.smith.langchain.com/"
LANGCHAIN_TRACING_V2="true"
LANGCHAIN_CALLBACKS_BACKGROUND="true"
```

the message is 200kb. I measure the text size.

### System Info

langchain@0.2.12 | MIT | deps: 16 | versions: 284

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.2.12.tgz
.shasum: 3fac0b9519a070689b6dd679d5854abc57824dcf
.integrity: sha512-ZHtJrHUpridZ7IQu7N/wAQ6iMAAO7VLzkupHqKP79S6p+alrPbn1BjRnh+PeGm92YiY5DafTCuvchmujxx7bCQ==
.unpackedSize: 5.4 MB

dependencies:
@langchain/core: >=0.2.11 <0.3.0  js-tiktoken: ^1.0.12              langsmith: ~0.1.30                uuid: ^10.0.0
@langchain/openai: >=0.1.0 <0.3.0 js-yaml: ^4.1.0                   ml-distance: ^4.0.0               yaml: ^2.2.1
@langchain/textsplitters: ~0.0.0  jsonpointer: ^5.0.1               openapi-types: ^12.1.3            zod-to-json-schema: ^3.22.3
binary-extensions: ^2.2.0         langchainhub: ~0.0.8              p-retry: 4                        zod: ^3.22.4

dist-tags:
latest: 0.2.12    next: 0.2.3-rc.0

published 3 days ago by basproul <braceasproul@gmail.com>

**Comment by anch13** [comment]
Hi there, is anyone still working on this? If not our team would love to investigate.
