### ISSUE TITLE
Agent executor tool invocation doesn't recognize ToolInputParsingException error

### ISSUE THREAD

**Issue by mamlukishay** [langchain-ai/langchainjs#6374]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following tool always returns as successful (with empty observation), even if it fails schema validation.

```typescript
enum CampaignOptimizationKPI {
  None = 'none',
  Conversions = 'conversions',
  Clicks = 'clicks',
  CTC = 'ctc',
  VideoCompletion = 'video-complation',
  Other = 'other',
}

const briefSchema = z.object({
  requestedKPIs: z.nativeEnum(CampaignOptimizationKPI).optional(),
});

const toolName = 'submit-campaign-brief';

const tool = new DynamicStructuredTool({
  name: toolName,
  description: 'submit incremental/full updates about the campaign brief object',
  schema: briefSchema,
  returnDirect: false,
  func: async (input) => {
    console.log('[2]', '|', toolName, '|', 'calling onChange with:', updatedBriefData);

    return 'OK, brief updated';
  },
});
```

### Description

I'm invoking a langchain tool through an agent executor, with a wrong schema.
Langchain doesn't identify the error as a `ToolInputParsingException`, therefore my chain proceeds and I get wrong results.

This is my tool definition (simplified for the example):
```typescript
enum CampaignOptimizationKPI {
  None = 'none',
  Conversions = 'conversions',
  Clicks = 'clicks',
  CTC = 'ctc',
  VideoCompletion = 'video-complation',
  Other = 'other',
}

const briefSchema = z.object({
  requestedKPIs: z.nativeEnum(CampaignOptimizationKPI).optional(),
});

const toolName = 'submit-campaign-brief';

const tool = new DynamicStructuredTool({
  name: toolName,
  description: 'submit incremental/full updates about the campaign brief object',
  schema: briefSchema,
  returnDirect: false,
  func: async (input) => {
    console.log(input);
    return 'OK, brief updated';
  },
});
```

The following input fails schema validation:
```
 {
    requestedKPIs: 'ctr',
  }
```

This is the stack trace:
```
Error: Received tool input did not match expected schema
    at DynamicStructuredTool.call (index.js:85:1)
    at async executor.js:474:1
    at async Promise.all (:5555/acc/5/campaigns/344/v/1/index 0)
    at async AgentExecutor._call (executor.js:466:1)
    at async AgentExecutor.invoke (base.js:55:1)
    at async RunnableSequence.invoke (base.js:1140:1)
    at async Object.getAssistantResponse (openai.api.ts:61:15)
```

This error is checked in executor.js for its instance type, but not recognized as the correct instance.

![image](https://github.com/user-attachments/assets/efb5cbb2-0bfb-4416-b193-05371b8a07ab)

![image](https://github.com/user-attachments/assets/d1fa0129-1a9c-4674-9180-2f55488965ad)

With this error being swallowed and never thrown, I don't have no ways to handle schema validation problems. This is bad, 
Please assist. 🙏

### System Info

langchain@0.2.12
node v20.11.0
yarn v1.22.22

**Comment by mamlukishay** [comment]
This is not helpful, I need a human hand here

**Comment by obround** [comment]
The issue is in the output parser. For example, if you are using react, then [this line](https://github.com/langchain-ai/langchainjs/blob/a14ae7bcb11f7e9f3736a6c0e9f4f8eddd7e2710/langchain/src/agents/react/output_parser.ts#L98) is to blame for raising an Error instead of an OutputParserException. Changing:
```ts
throw new Error(`Could not parse LLM output: ${text}`);
```
to
```ts
throw new OutputParserException(`Could not parse LLM output: ${text}`);
```
solves the issue for me. If you can validate that this works for you too, I'll submit a pr.

**Comment by mamlukishay** [comment]
Your fix works and looks good, I think you should open a PR, although it's not exactly my case as I'm using open ai functions agents and not a react agent
