### ISSUE TITLE
Node warning after langchain upgrade to 0.2.13 Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use events.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by djaffer** [langchain-ai/langchainjs#6461]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Getting error when running langchain

### Error Message and Stack Trace (if applicable)

(node:62032) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use events.setMaxListeners() to increase limit
    at [kNewListener] (node:internal/event_target:566:17)
    at [kNewListener] (node:internal/abort_controller:240:24)
    at EventTarget.addEventListener (node:internal/event_target:679:23)
    at /home/langchainnode_modules/@langchain/core/dist/utils/signal.cjs:18:20
    at new Promise (<anonymous>)
    at raceWithSignal (/home/langchainnode_modules/@langchain/core/dist/utils/signal.cjs:17:9)
    at RunnableMap._transform (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:1397:79)
    at _transform.next (<anonymous>)
    at RunnableMap._transformStreamWithConfig (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:307:30)
    at _transformStreamWithConfig.next (<anonymous>)
    at PromptTemplate.transform (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:390:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatOpenAI.transform (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:390:26)
    at async wrapInputForTracing (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:274:30)
    at async pipeGeneratorWithSetup (/home/langchainnode_modules/@langchain/core/dist/utils/stream.cjs:260:19)
    at async StringOutputParser._transformStreamWithConfig (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:295:26)

### Description

Getting the warning in node after upgrading langchain to latest versions. 

"@langchain/community": "0.2.25",
"@langchain/openai": "0.2.6",
"langchain": "0.2.13",

### System Info

"@langchain/community": "0.2.25",
"@langchain/openai": "0.2.6",
"langchain": "0.2.13",

**Comment by jacoblee93** [comment]
Hey @djaffer - could you share the code that triggers this?

**Comment by jacoblee93** [comment]
Hey @djaffer, thanks for reporting this - could you share the code that triggers this?

**Comment by jacoblee93** [comment]
Hey @djaffer, thanks for reporting this - could you share the code that triggers this?

**Comment by djaffer** [comment]
const ragChainFromDocs = RunnableSequence.from([
        {
          question: (input) => {
            return input.question;
          },
          chatHistory: (input) => {
            return input?.chatHistory ?? '';
          },
          context: async (input) => {
            const relevantDocs = await retriver.invoke(input.question);
  
            const serialized = formatDocumentsAsString(relevantDocs);
            return serialized;
          },
        },
        questionPrompt,
        chatModel,
        new StringOutputParser(),
      ]);

**Comment by djaffer** [comment]
```
const ragChainFromDocs = RunnableSequence.from([
        {
          question: (input) => {
            return input.question;
          },
          chatHistory: (input) => {
            return input?.chatHistory ?? '';
          },
          context: async (input) => {
            const relevantDocs = await retriver.invoke(input.question);
            console.log('relevantDocs', relevantDocs.length);
            if (relevantDocs.length > 0) {
              source = relevantDocs.map((doc) => doc.metadata);
            }
            const serialized = formatDocumentsAsString(relevantDocs);
            return serialized;
          },
        },
        questionPrompt,
        chatModel,
        new StringOutputParser(),
      ]);
```

**Comment by jacoblee93** [comment]
And then you pass a signal?

**Comment by djaffer** [comment]
updated response. I am not passing any signal.
