### ISSUE TITLE
StructuredOutputParser can't handle nested triple backticks

### ISSUE THREAD

**Issue by hnykda** [langchain-ai/langchainjs#6734]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { StructuredOutputParser } from 'langchain/output_parsers';
import { z } from 'zod';

async function main() {
  const c =
    '{  "revisedOutput": "long markdown text with example ```javascript\\nfunction(){}``` here"}';

  const parser = StructuredOutputParser.fromZodSchema(
    z.object({
      revisedOutput: z.string(),
    }),
  );
  // the following line will throw an error
  const response = await parser.parse(c);
  console.log(response);
}

main();
```

### Error Message and Stack Trace (if applicable)
```
/Users/dan/work/varuna/code/varuna/node_modules/langchain/dist/output_parsers/structured.cjs:83
            throw new output_parsers_1.OutputParserException(`Failed to parse. Text: "${text}". Error: ${e}`, text);
                  ^

OutputParserException [Error]: Failed to parse. Text: "{  "revisedOutput": "long markdown text with example ```javascript\nfunction(){}``` here"}". Error: SyntaxError: Unexpected token 'j', "javascript"... is not valid JSON
    at StructuredOutputParser.parse (/Users/dan/work/varuna/code/varuna/node_modules/langchain/dist/output_parsers/structured.cjs:83:19)
    at main (/Users/dan/work/varuna/code/varuna/app/dev/parse.tsx:15:33)
    at <anonymous> (/Users/dan/work/varuna/code/varuna/app/dev/parse.tsx:19:1)
    at Object.<anonymous> (/Users/dan/work/varuna/code/varuna/app/dev/parse.tsx:19:6)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.transformer (/Users/dan/work/varuna/code/varuna/node_modules/tsx/dist/register-C1urN2EO.cjs:2:1122)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24) {
  llmOutput: '{  "revisedOutput": "long markdown text with example ```javascript\\nfunction(){}``` here"}',
  observation: undefined,
  sendToLLM: false
}
```

### Description

1. I am parsing a simple markdown, but that markdown might contain triple backticks.
2. using `StructuredOutputParser` fails on that scenario, partly because this will [just randomly split the string in the middle](https://github.com/langchain-ai/langchainjs/blob/08092cdd6c2e8a443acf55e650ca0e8a185b02a9/langchain/src/output_parsers/structured.ts#L102)...

### System Info

```
$ npm info langchain

langchain@0.2.18 | MIT | deps: 14 | versions: 291
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.2.18.tgz
.shasum: f43e9aa8588048bfee38bf2d39e508c0410c4295
.integrity: sha512-7+5Y2FsdjlUBKJf1N+MyHn1PrGZQ9m87l3du7IeH4RiQp4j8Bz7mGV+Bjhr8FEXFjo85zLrbnpsN87pZCstubA==
.unpackedSize: 3.5 MB

dependencies:
@langchain/core: >=0.2.21 <0.3.0  langsmith: ~0.1.40                
@langchain/openai: >=0.1.0 <0.3.0 openapi-types: ^12.1.3            
@langchain/textsplitters: ~0.0.0  p-retry: 4                        
binary-extensions: ^2.2.0         uuid: ^10.0.0                     
js-tiktoken: ^1.0.12              yaml: ^2.2.1                      
js-yaml: ^4.1.0                   zod-to-json-schema: ^3.22.3       
jsonpointer: ^5.0.1               zod: ^3.22.4                      

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.2.18    next: 0.3.0-rc.0  

published 6 days ago by jacoblee93 <jacoblee93@gmail.com>
```

**Comment by hnykda** [comment]
Well, I know bot, that's what I linked. 

I am sharing this because I think this is unexpected behavior, and took me an hour to figure what's happening because I didn't expect that langsmith is going to just split the string if there is something in between. I am not sure how to solve this, but maybe at least the error message could be improved, or one could try to first parse "as is" and only then remove those backticks.

**Comment by CarlosSLoureiro** [comment]
I'm having same issue. I'm trying to Build an Extraction Chain but sometimes even with same prompt it throws the parse error.

An **not good** way that I'm using to try to prevent while it isn't fixed is creating a retry logic. For example:

For example:

```
const tryExtract = async (prompt: string, retries = 0) => {
  try {
    return await extract(prompt); // Here is the Extraction Chain logic
  } catch (error) {
     if (retries <= 5) {
       return tryExtract(prompt, retries + 1);
     }
     throw error;
  }
}

tryExtract("prompt here").then(console.log);
```

**Comment by johnguirgis** [comment]
Hello, I'm working with @tlandart on this.

It seems @hnykda's idea could work, though we think it is probably cleaner to explicitly handle this case in the try block by only splitting when triple back ticks are outside of the curly brackets. It could look something like this:

```ts
...
try {
        const pattern = /```\s*\{/;
        const json = pattern.test(text)
            ? text.trim().split(/```(?:json)?/)[1]
            : text.trim();
        return await this.schema.parseAsync(JSON.parse(json));
    }
...
```

We have tested this approach with some possible values and it seems to behave as expected, but, if there is anything we have overlooked, please let us know.

We're first time contributors so if anyone has any comments on this it would be appreciated!

**Comment by hnykda** [comment]
Looks valid to me
