### ISSUE TITLE
npm error @langchain/community v3.0.0 "Cannot read properties of null (reading 'edgesOut')"

### ISSUE THREAD

**Issue by vindex10** [langchain-ai/langchainjs#6790]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

fails on

`npm install @langchain/community -dd`

and

`npm install @langchain/community@0.3.0 -dd`

but, succeeds on

`npm install @langchain/community@0.2.19 -dd`

### Error Message and Stack Trace (if applicable)

```
npm http fetch GET 200 https://registry.npmjs.org/typeorm 27ms (cache hit)
npm verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
npm verbose stack     at #loadPeerSet (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1286:38)
npm verbose stack     at async #buildDepStep (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
npm verbose stack     at async Arborist.buildIdealTree (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
npm verbose stack     at async Promise.all (index 1)
npm verbose stack     at async Arborist.reify (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
npm verbose stack     at async Install.exec (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/commands/install.js:150:5)
npm verbose stack     at async Npm.exec (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/npm.js:207:9)
npm verbose stack     at async module.exports (/opt/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
npm error Cannot read properties of null (reading 'edgesOut')
npm verbose cwd /home/...
npm verbose os Linux 6.9.3-76060903-generic
npm verbose node v20.17.0
npm verbose npm  v10.8.3
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: /home/vindex10/.npm/_logs/2024-09-14T09_53_23_240Z-debug-0.log
```

### Description

I'm trying to install `@langchain/community`. The latest release fails, but the previous one works OK.

Possibly related issue: 
https://github.com/langchain-ai/langchainjs/issues/5673

### System Info

linux Linux 6.9.3-76060903-generic
node version v20.17.0
npm version v10.8.3

**Comment by vindex10** [comment]
closed as duplicate of: https://github.com/langchain-ai/langchainjs/issues/6789
