### ISSUE TITLE
Issue in ChatVertexAI Generation: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by jeloi** [langchain-ai/langchainjs#7171]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

A very basic chain:
```
  const runnable = RunnableSequence.from<ChainInputs, DecomposeChainOutput>([
    {
      input: (i: ChainInputs) => i.input,
      chat_history: (i: ChainInputs) =>
        i.chat_history?.length
          ? formatChatHistoryForPrompt(i.chat_history)
          : [],
      customizationPrompt: () => {
        return fullConfigs.customizationPrompt;
      },
    },
    promptTemplate,
    model,
    new StringOutputParser(),
    }),
    ```
    
    Only potential relevant callout is using a custom safetyHandler:
    ```
        return new ChatVertexAI({
      modelName: modelParams.modelName,
      safetyHandler: {
        handle: (response) => {
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore
          if (response.data?.candidates[0].finishReason === "SAFETY") {
            throw new InvalidRequestError(
              "Safety error - Gemini blocked response",
              response.data,
            );
          }
          return response;
        },
      },
      ...devAuthOptions,
      ...modelParams,
    });
    ```

### Error Message and Stack Trace (if applicable)

```
TypeError: Cannot read properties of undefined (reading 'text')
    at ChatVertexAI._generate (file:///Users/user/code/projects/internal1/node_modules/.pnpm/@langchain+google-common@0.1.1_@langchain+core@0.3.0_zod@3.23.5/node_modules/@langchain/google-common/dist/chat_models.js:275:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async ChatVertexAI._generateUncached (file:///Users/user/code/projects/internal1/node_modules/.pnpm/@langchain+core@0.3.0_openai@4.40.0/node_modules/@langchain/core/dist/language_models/chat_models.js:182:29)
    at async ChatVertexAI.invoke (file:///Users/user/code/projects/internal1/node_modules/.pnpm/@langchain+core@0.3.0_openai@4.40.0/node_modules/@langchain/core/dist/language_models/chat_models.js:56:24)
    at async RunnableSequence.invoke (file:///Users/user/code/projects/internal1/node_modules/.pnpm/@langchain+core@0.3.0_openai@4.40.0/node_modules/@langchain/core/dist/runnables/base.js:1144:33)
    at async RunnableSequence.invoke (file:///Users/user/code/projects/internal1/node_modules/.pnpm/@langchain+core@0.3.0_openai@4.40.0/node_modules/@langchain/core/dist/runnables/base.js:1150:27)
    at async RunnableSequence.invoke (file:///Users/user/code/projects/internal1/node_modules/.pnpm/@langchain+core@0.3.0_openai@4.40.0/node_modules/@langchain/core/dist/runnables/base.js:1150:27)
    at async _forward (file:///Users/user/code/projects/internal1/node_modules/.pnpm/langsmith@0.1.41_@langchain+core@0.3.0_langchain@0.3.5_openai@4.40.0/node_modules/langsmith/dist/evaluation/_runner.js:670:9)
    at async RetryOperation._fn (/Users/user/code/projects/internal1/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)
```

### Description

Encountering an issue with ChatVertexAI where the above error is thrown.

This is after bumping to google-common 0.1.1.

Appears to be coming from this line: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-google-common/src/chat_models.ts#L350

Unclear what the conditions are that cause this, it happens intermittently.

Context from Allen: If you want to hack it, I'd change it to ret?.generations?.[0]?.text ?? "" but I'll have a slightly better fix in (hopefully) a few days

cc @afirstenberg 

### System Info

    "@langchain/community": ">=0.3.0 <0.4.0",
    "@langchain/core": "^0.3.16",
    "@langchain/google-vertexai": "0.1.0",
    
    Node v21.7.3

**Comment by afirstenberg** [comment]
@jacoblee93 - Please assign this to me, but I hope to have the fix in place as part of #6999

**Comment by jacoblee93** [comment]
Thank you @afirstenberg!

**Comment by afirstenberg** [comment]
@jacoblee93 - I believe this can actually be closed as part of #6999

**Comment by thushanth-bengre-langchain** [comment]
Fixed in #6999
