### ISSUE TITLE
Chroma RAG Example from Documentation Results in Error

### ISSUE THREAD

**Issue by wessankey** [langchain-ai/langchainjs#7194]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { Chroma } from "@langchain/community/vectorstores/chroma";
import { OpenAIEmbeddings } from "@langchain/openai";

const embeddings = new OpenAIEmbeddings({
  model: "text-embedding-3-small",
});

const vectorStore = new Chroma(embeddings, {
  collectionName: "a-test-collection",
  url: "http://localhost:8000",
  collectionMetadata: { "hnsw:space": "cosine" },
});

const documents = [
  {
    pageContent: "The powerhouse of the cell is the mitochondria",
    metadata: { source: "https://example.com" },
  },
  {
    pageContent: "Buildings are made out of brick",
    metadata: { source: "https://example.com" },
  },
];

await vectorStore.addDocuments(documents, { ids: ["1", "2"] });

const retriever = vectorStore.asRetriever({ k: 2 });
await retriever.invoke("biology");
```

### Error Message and Stack Trace (if applicable)

```
ChromaClientError: Bad request to http://localhost:8000/api/v1/collections/ca57da1e-f666-41a8-b3b8-cce8372c6cdd/query with status: Bad Request
    at chromaFetch (/Users/wessankey/Documents/code/conflence-rag/node_modules/.pnpm/chromadb@1.9.2_encoding@0.1.13_openai@4.71.1_encoding@0.1.13_zod@3.23.8_/node_modules/chromadb/dist/chromadb.mjs:2604:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Collection.query (/Users/wessankey/Documents/code/conflence-rag/node_modules/.pnpm/chromadb@1.9.2_encoding@0.1.13_openai@4.71.1_encoding@0.1.13_zod@3.23.8_/node_modules/chromadb/dist/chromadb.mjs:2295:12)
    at Chroma.similaritySearchVectorWithScore (/Users/wessankey/Documents/code/conflence-rag/node_modules/.pnpm/@langchain+community@0.3.12_@ibm-cloud+watsonx-ai@1.1.2_@langchain+core@0.3.17_openai@4.71.1__kioffgpmnh3q2ibstqorthwtay/node_modules/@langchain/community/dist/vectorstores/chroma.js:321:24)
    at async Chroma.similaritySearch (file:///Users/wessankey/Documents/code/conflence-rag/node_modules/.pnpm/@langchain+core@0.3.17_openai@4.71.1_encoding@0.1.13_zod@3.23.8_/node_modules/@langchain/core/dist/vectorstores.js:104:25)
    at async VectorStoreRetriever.getRelevantDocuments (file:///Users/wessankey/Documents/code/conflence-rag/node_modules/.pnpm/@langchain+core@0.3.17_openai@4.71.1_encoding@0.1.13_zod@3.23.8_/node_modules/@langchain/core/dist/retrievers/index.js:69:29)
    at <anonymous> (/Users/wessankey/Documents/code/conflence-rag/src/chroma-repro.ts:32:1) {
  cause: undefined
}
```

### Description

I'm using LangChain to build a RAG pipeline with a Chroma vector store. The minimal reproducible example provided is a slightly modified version from the [documentation](https://js.langchain.com/docs/integrations/vectorstores/chroma/).

The error occurs when calling `retriever.invoke()`.

### System Info

Node version: 18.16.0
`@langchain/community`: `0.3.12`
`@langchain/core`: `0.3.17`
`@langchain/openai`: `0.3.12`
`@chromadb`: `1.9.2`

**Comment by wessankey** [comment]
The code runs successfully when the `chromadb` dependency is downgraded to `1.5.3`

**Comment by Mageenz** [comment]
> The code runs successfully when the `chromadb` dependency is downgraded to `1.5.3`

After `demoted` to `1.5.3`, there were many errors where modules were not found, even the `path` and `fs` modules were not referenced
