### ISSUE TITLE
Failed to pull hub prompt with anthropic model

### ISSUE THREAD

**Issue by yowpark** [langchain-ai/langchainjs#7328]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import * as hub from "langchain/hub";
import { ChatAnthropic } from "@langchain/anthropic";

const prompt = await hub.pull("blahblah", { includeModel: true }); // this prompt has anthropic model
```

### Error Message and Stack Trace (if applicable)

```
[1] >  Exception occurs: Error: Invalid namespace: $.kwargs.last.kwargs.bound -> {"lc":1,"type":"constructor","id":["langchain","chat_models","anthropic","ChatAnthropic"],"kwargs":{"temperature":0.5,"max_tokens":1024,"top_p":1,"top_k":-1,"anthropic_api_key":{"id":["ANTHROPIC_API_KEY"],"lc":1,"type":"secret"},"model":"claude-3-5-haiku-20241022"}}
[1] >      at Object.reviver (file:///some-directory/node_modules/@langchain/core/dist/load/index.js:117:19)
[1] >      at file:///some-directory/node_modules/@langchain/core/dist/load/index.js:153:31
[1] >      at Array.map (<anonymous>)
[1] >      at Object.reviver (file:///some-directory/node_modules/@langchain/core/dist/load/index.js:151:79)
[1] >      at Object.reviver (file:///some-directory/node_modules/@langchain/core/dist/load/index.js:131:38)
[1] >      at file:///some-directory/node_modules/@langchain/core/dist/load/index.js:153:31
[1] >      at Array.map (<anonymous>)
[1] >      at Object.reviver (file:///some-directory/node_modules/@langchain/core/dist/load/index.js:151:79)
[1] >      at Object.reviver (file:///some-directory/node_modules/@langchain/core/dist/load/index.js:131:38)
[1] >      at load (file:///some-directory/node_modules/@langchain/core/dist/load/index.js:161:20) {
```

### Description

This appears to be an issue that chat_models__anthropic isn't exported at import_map.ts, unlike openai.
https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/load/import_map.ts#L126

![image](https://github.com/user-attachments/assets/661d4b7c-cda6-4b00-bdce-9deb4b6f14ce)

### System Info

platform mac
node v18.19.0
npm 10.2.3

**Comment by jacoblee93** [comment]
Thanks for reporting - will dig in and patch, thanks!

**Comment by guypy** [comment]
This issue also happens for Google models

```
Error: Invalid namespace: $.kwargs.last.kwargs.bound -> {"lc":1,"type":"constructor","id":["langchain_google_genai","chat_models","ChatGoogleGenerativeAI"],"kwargs":{"temperature":0,"top_p":1,"google_api_key":{"id":["GOOGLE_API_KEY"],"lc":1,"type":"secret"},"model":"gemini-2.0-flash-exp"}}
    at Object.reviver (/Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:120:23)
    at /Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:179:31
    at Array.map (<anonymous>)
    at Object.reviver (/Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:177:79)
    at Object.reviver (/Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:157:38)
    at /Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:179:31
    at Array.map (<anonymous>)
    at Object.reviver (/Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:177:79)
    at Object.reviver (/Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:157:38)
    at load (/Users/guypinchuk/Projects/cubic/node_modules/@langchain/core/dist/load/index.cjs:187:20)
```

**Comment by KoreanThinker** [comment]
azure open ai too...

**Comment by Jeremy-Magical** [comment]
Is there any update on this? We can only pull OpenAI prompts without this fixed.

**Comment by jacoblee93** [comment]
Not-so-ideal fix merged where you have to do this:

```ts
import { ChatAnthropic } from "@langchain/anthropic";

const prompt = await pull("my-prompt", {
  includeModel: true,
  modelClass: ChatAnthropic,
});
```

Will work on something more automatic in a future release where we can make breaking changes.

**Comment by guypy** [comment]
@jacoblee93 thanks for the attention to this!

Unfortunately, this keeps changing models in LangSmith obsolete, and very error-prone as it may break applications.
Passing on the `modelClass` is not that different from just piping the pulled prompt to to the wanted model, and still requires code changes.

In the UI and docs, it seems as if you can easily deploy model changes without requiring code changes, but in reality changing the model to anything other than OpenAI will break applications, potentially in production.

A note in the UI and docs is necessary IMO, or perhaps just removing the includeModel option all together until this is properly fixed is best.

**Comment by jacoblee93** [comment]
> Unfortunately, this keeps changing models in LangSmith obsolete, and very error-prone as it may break applications.
Passing on the modelClass is not that different from just piping the pulled prompt to to the wanted model, and still requires code changes.

Yeah fair point, it's not great. I suppose I can make a separate entrypoint with beta functionality that attempts to pull in from your installed packages for now - will think through naming.

**Comment by jacoblee93** [comment]
Going out soon

**Comment by rmarquet21** [comment]
I have the same error with Mistral AI
```
    err: {
      "type": "Error",
      "message": "Invalid namespace: $.kwargs.last.kwargs.bound -> {\"lc\":1,\"type\":\"constructor\",\"id\":[\"langchain\",\"chat_models\",\"mistralai\",\"ChatMistralAI\"],\"kwargs\":{\"temperature\":0.6,\"top_p\":1,\"model\":\"mistral-large-latest\",\"mistral_api_key\":{\"id\":[\"MISTRAL_API_KEY\"],\"lc\":1,\"type\":\"secret\"},\"max_tokens\":16384}}",
      "stack":
          Error: Invalid namespace: $.kwargs.last.kwargs.bound -> {"lc":1,"type":"constructor","id":["langchain","chat_models","mistralai","ChatMistralAI"],"kwargs":{"temperature":0.6,"top_p":1,"model":"mistral-large-latest","mistral_api_key":{"id":["MISTRAL_API_KEY"],"lc":1,"type":"secret"},"max_tokens":16384}}
              at Object.reviver (file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:117:19)
              at file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:153:31
              at Array.map (<anonymous>)
              at Object.reviver (file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:151:79)
              at Object.reviver (file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:131:38)
              at file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:153:31
              at Array.map (<anonymous>)
              at Object.reviver (file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:151:79)
              at Object.reviver (file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:131:38)
              at load (file:///Users/robinmarquet/Documents/hirify/main/node_modules/@langchain/core/dist/load/index.js:161:20)
    }
```

With this code
```js
  const chain = await pull<Runnable>('my_repo_commit', {
    includeModel: true,
  })
```

**Comment by jacoblee93** [comment]
@rmarquet21 note that you will need to import from `"langchain/hub/node"` - can you confirm you're doing this?

**Comment by rmarquet21** [comment]
> [@rmarquet21](https://github.com/rmarquet21) note that you will need to import from `"langchain/hub/node"` - can you confirm you're doing this?

I import `"langchain/hub/node"`, of course
