### ISSUE TITLE
Error: Vectors must have the same length as the number of dimensions (undefined)

### ISSUE THREAD

**Issue by baunov** [langchain-ai/langchainjs#733]
I'm trying to create embeddings for a documentation and store it in Chroma.
As soon as the first chunk of Documents is written using `Chroma.fromDocuments`, the next chunk (with `addDocuments`) throws that error:

```
 Error: Vectors must have the same length as the number of dimensions (undefined)
    at Chroma.addVectors (/Users/baunov/Documents/dev/langchain-ts-starter/node_modules/langchain/dist/vectorstores/chroma.js:74:19)
    at Chroma.addDocuments (/Users/baunov/Documents/dev/langchain-ts-starter/node_modules/langchain/dist/vectorstores/chroma.js:39:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at vectorizeDocs (/Users/baunov/Documents/dev/langchain-ts-starter/src/vectorize-docs.ts:52:13)
    at <anonymous> (/Users/baunov/Documents/dev/langchain-ts-starter/src/index.ts:23:1)
```

Here's the full code for this:

```
export const vectorizeDocs = async (dir: string, collection: string) => {
    const files: string[] = await readFilesInFolder(path.join(__dirname, '..', dir));
    const json = files.map((f) => JSON.parse(f)).filter((j) => j.content.length > 0);

    const textSplitter = new RecursiveCharacterTextSplitter({chunkSize: 1000, chunkOverlap: 0});

    const docs: Document[] = await textSplitter.createDocuments(
        json.map((j) => j.content),
        json.map((j => ({url: j.url, category: collection})))
    );

    const exists = Boolean(await chromaClient.getCollection(collection));

    const embeddings = new OpenAIEmbeddings();
    let docsChunks = splitIntoChunks(docs, 30);
    const store = exists ? await Chroma.fromExistingCollection(embeddings, {
        collectionName: collection
    }) : await Chroma.fromDocuments(docsChunks[0], embeddings, {
        collectionName: collection
    }).then((s) => {
        docsChunks = docsChunks.slice(1);
        return s;
    });
    console.log('Chunk 1 successfully written');

    for (const chunk of docsChunks) {
        try {
            await store.addDocuments(chunk);
            console.log('Added chunk');
        }
        catch (e) {
            console.log('Error adding chunk', chunk, e);
        }
    }
};
```

And interestingly, this doesn't happen to all docs. Some docs are vectorised without errors. But I can't tell why.

Here's the data I'm feeding into that function (basically scraped langchain docs):

[langchain.zip](https://github.com/hwchase17/langchainjs/files/11197116/langchain.zip)

**Comment by jerryzhu8888** [comment]
I have the same question

**Comment by apoorvcodes** [comment]
Having same issues!

**Comment by teddybee** [comment]
Same error here.

**Comment by 0xmmo** [comment]
I had this issue as well. For me it was due to passing a documents array of length === 0. So make sure that the split docs you provide to the vector store and then the retriever are of length >= 1.
